### ISSUE TITLE
Keyboard goes down when changing line in Android Chrome

### ISSUE THREAD

**Issue by ChoSeoHwan** [ckeditor/ckeditor4#4252] opened 2020-09-03 03:15 UTC
## Type of report

Bug

## Provide detailed reproduction steps (if any)

The same symptom appears on the [demo page.](https://ckeditor.com/ckeditor-4/demo/)

1. enter any alphabet
2. press enter key 
3. android keyboard goes down. - issue 
4. press backspace key to remove line
5. android keyboard goes down. - issue 

### Expected result

Android keyboard keeps when creating or removing line.

### Actual result

Android keyboard goes down when creating or removing line

## Other details

* Browser: Chrome 85.0.4183.81
* OS: Android 10
* CKEditor version: 4.14 or higher

**Comment by JimVT** [comment] 2020-09-05 06:29
Same thing is happening to me, it is very annoying and discouraging me from using CKEditor.

**Comment by jackwickham** [comment] 2020-09-05 09:41
This is a chrome bug, fixed by Google in https://bugs.chromium.org/p/chromium/issues/detail?id=1121179

**Comment by Comandeer** [comment] 2020-09-06 16:05
I can confirm that it seems to be a Chrome bug.

**Comment by f1ames** [comment] 2020-11-02 13:58
Hi @ChoSeoHwan, @JimVT and @jackwickham. The issue was indeed a regression in Chrome v85 and is already fixed in Chrome v86.

**Closed by f1ames** 2020-11-02 13:58 UTC
Labels: browser:android, resolution:upstream, status:confirmed, type:bug
