### ISSUE TITLE
iOS: Remove autofocus after tap on disabled button

### ISSUE THREAD

**Issue by KarolDawidziuk** [ckeditor/ckeditor4#4766] opened 2021-06-17 11:09 UTC
## Type of report

Task

## Provide description of the task

Disabled buttons fix on iOS it's no longer needed because since iOS8 this problem not occurs and it's changed behaves of editor compared to other systems. 

The change looks simple. We need just remove 2 piece of unnecessary code from:
1. https://github.com/ckeditor/ckeditor4/blob/master/plugins/button/plugin.js#L199-L201
2. https://github.com/ckeditor/ckeditor4/blob/master/plugins/dialog/plugin.js#L1151-L1153

## Other details

* Browser: ...
* OS: iOS
* CKEditor version: …
* Installed CKEditor plugins: …

**Comment by f1ames** [comment] 2021-06-22 10:39
Blocked by #4767.

**Comment by f1ames** [comment] 2021-07-27 08:52
It turns out it's not related nor blocked by #4767 as mentioned in https://github.com/ckeditor/ckeditor4/issues/4766#issuecomment-865871308.

**Comment by jacekbogdanski** [comment] 2021-08-04 14:11
It seems like we are supporting iOS 6+ https://ckeditor.com/docs/ckeditor4/latest/guide/dev_browsers.html so let's check if the difference between maximize feature between Android and iOS is problematic (#4767) because we will introduce regression with this refactoring.

**Comment by jacekbogdanski** [comment] 2021-09-14 11:05
We don't want to introduce regression for older iOS devices, so I'm closing this ticket.

**Closed by jacekbogdanski** 2021-09-14 11:05 UTC
Labels: resolution:wontfix, type:task, status:confirmed, browser:ios, plugin:toolbar, size:XS
