### ISSUE TITLE
Copy paste content with max limit characters into CKEditor-4 and then pressing any character on keyboard erases all content from CKEditor

### ISSUE THREAD

**Issue by sridharravva** [ckeditor/ckeditor4#4899] opened 2021-09-20 20:02 UTC
I am using CKEditor Standard Package Version 4.16.1/4.16.2 and getting some issue with copy paste content.
Whenever copy paste content with max limit characters into CKEditor-4 and then pressing any character on keyboard in the CKEditor in order to try add more content, **it erases all the content from CKEditor body.** Instead it should have throw some error message saying max limit reached and should not let enter any more characters or something into the CKEditor.
Could there be some issue with below wordcount/plugin.js code?
**function limitReached(editorInstance, notify) {**
                limitReachedNotified = true;
                limitRestoredNotified = false;

                if (!config.warnOnLimitOnly) {
                    if (config.hardLimit) {
                        if (editor.mode === "source" && editor.plugins.codemirror) {							
                            window["codemirror_" + editor.id].undo();
                        } else {
				                      editorInstance.execCommand("undo");                            					
                                                      editorInstance.execCommand("undo");
                        }                           
                    }
                }

                if (!notify) {
                    counterElement(editorInstance).className = "cke_path_item cke_wordcountLimitReached";
                    editorInstance.fire("limitReached", { firedBy: "wordCount.limitReached" }, editor);
                }
            }

**Comment by KarolDawidziuk** [comment] 2021-09-22 09:25
Hi @sridharravva!

I cannot reproduce this in the basic version of the editor.
`wordcount` plugins is a 3-rd party plugin made by the community, so in this case, it is best to report this to the plugin owner.

`wordcount` issue tracker: https://github.com/w8tcha/CKEditor-WordCount-Plugin/issues

In that case, I close this issue.

**Closed by KarolDawidziuk** 2021-09-22 09:25 UTC
Labels: type:bug
