### ISSUE TITLE
[SEO] CKE4 Docs pages have wrong canonical points

### ISSUE THREAD

**Issue by wwalc** [ckeditor/ckeditor4#3603] opened 2019-10-28 05:30 UTC
Wrong: https://ckeditor.com/docs/examples/latest/examples/fileupload.html
Correct: https://ckeditor.com/docs/ckeditor4/latest/examples/fileupload.html

There are more CKEditor 4 pages with a similar issue (at least all examples).

**Comment by msamsel** [comment] 2019-11-04 09:41
Canonical paths are created by Umberto automatically. That's why we won't be able to make anything to fix it on our side.

**Comment by f1ames** [comment] 2019-11-28 13:58
Closing as it needs to be fixed in Umberto as mentioned in previous comment.

**Comment by f1ames** [comment] 2019-12-03 16:13
Reopening so we have an eye on this issue.

**Comment by f1ames** [comment] 2020-01-10 12:57
Issue in Umberto was fixed, we just need to wait for new Umberto version release and check if it works as intended.

**Comment by f1ames** [comment] 2020-01-16 15:58
Docs with updated Umberto version already deployed.

**Closed by f1ames** 2020-01-16 15:58 UTC
Labels: resolution:upstream, status:confirmed, type:docs, workload:low
