### ISSUE TITLE
Failing test: tests/plugins/widget/manual/deleteparagraphbetween

### ISSUE THREAD

**Issue by LukaszGudel** [ckeditor/ckeditor4#4697] opened 2021-05-13 07:36 UTC
## Type of report

Failing test

## Provide detailed reproduction steps (if any)

1. Connect external keyboard with delete button to iOS device.
2. Open manual test on iOS device.
3. Try to remove empty paragraph between widgets with delete key.

### Expected result

The paragraph is removed.

### Actual result

Nothing happens

## Other details

* Browser: Safari 12
* OS: iPadOS 12.4.8
* CKEditor version: 4.16.1
* Installed CKEditor plugins: full-all preset
* There is no `delete` key on iOS virtual keyboard and external keyboard is needed
* `Delete` key worked correctly on `tests/plugins/widget/manual/deleteparagraph` manual test

**Comment by f1ames** [comment] 2021-05-14 14:37
I would say this is a duplicate of #4705. There is no `Delete` key on mobiles and external keyboard is really an edge case so we should just ignore this test on mobiles.

Of course it doesn't full work as mentioned in the issue description but "external keyboard is really an edge case" and it's behaviour may be a little different than desktop one (since there is no native equivalent too) so I'm for closing this one.

**Closed by f1ames** 2021-05-14 14:37 UTC
Labels: browser:ios, status:confirmed, type:failingtest
