### ISSUE TITLE
Italic title

### ISSUE THREAD

**Issue by Tejatr** [ckeditor/ckeditor4#3432] opened 2019-09-18 10:45 UTC
## Styles
when we select heading automatically changes and in styles we can see that font in Italic title..but if we change heading 2 to heading3 or 1 or any we can get Italic title in style so user cannot understand  font is italic or not

## Provide detailed reproduction steps (if any)

1 write content in header or footer  select it and add style italic title
2.now change  heading
3. now we cannot find here italic title in styles so user cannot identify the content in italic
Expected
In styles we need to get italic title if we change heading also

### Actual result

if heading changes italic title is missing in styles

## Other details

* Browser: …chrome
* OS: …windows7
* CKEditor version: …4.11

**Comment by Dumluregn** [comment] 2019-09-18 11:51
Duplicate of #3431. 
As I've already stated there, it's a desired behaviour. To give another example, if you choose predefined style `Subtitle` and then change heading level from `h3` to `h1`, this can no longer be subtitle (as there can be no higher level heading than `h1`), so this style's name is no longer appropriate. Following the same logic, after changing any style in `Italic Title`, it's no longer predefined `Italic Title`, so this style name is not displayed. You can try creating your own predefined styles following [this guide](https://ckeditor.com/docs/ckeditor4/latest/features/styles.html) or just use `Italic` button instead.

**Closed by Dumluregn** 2019-09-18 11:51 UTC
Labels: type:bug
