### ISSUE TITLE
CKEDITOR.dom.selection#getCommonAncestor() not always working in Firefox 69

### ISSUE THREAD

**Issue by dataform** [ckeditor/ckeditor4#3636] opened 2019-11-08 10:53 UTC
## Type of report

Bug - getCommonAncestor() doesn't always return a CKEDITOR.dom.element.

## Provide detailed reproduction steps (if any)

Download CKEditor basic package, install and add following:
`CKEDITOR.on('instanceReady', function( ev ) {
	ev.editor.on('paste', function( ev ) {
		var selection = ev.editor.getSelection();
		var ancestor = selection.getCommonAncestor();
		if(ancestor instanceof CKEDITOR.dom.element) {
			console.log(ancestor.getName());
		} else {
			console.log(ancestor); // Text?
		}
	});
});`

### Expected result

Any paste when no selection will always write an element name to the console.

### Actual result

Pasting to the end of a line doesn't give an element name, i.e. getCommonAncestor() not returning an element.

## Other details

* Browser: Firefox 69.0.3
* OS: Windows 10.
* CKEditor version: 4.13.0
* Installed CKEditor plugins: Basic

Appears to work in IE 11.

**Comment by Dumluregn** [comment] 2019-11-08 12:15
Hello, let's take a look at our [API Docs](https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_dom_selection.html#method-getCommonAncestor) for this method:

```
returns
    element
        The common ancestor of the selection or null if selection is empty.
```

So it seems to work exactly the way it should?

**Comment by dataform** [comment] 2019-11-08 14:36
Not on Firefox 69 or 70 it appears (for me anyhow). If I paste to the end of a line (no selection), it returns an object as shown in the console.
![image](https://user-images.githubusercontent.com/13889403/68484328-f9292680-0234-11ea-8dd7-1b7cdc09ac24.png)

**Comment by Dumluregn** [comment] 2019-11-08 15:10
Ok, so I guess you swapped `Expected` and `Actual` results - we'll investigate this issue and let you know, thanks for reporting anyway!

**Comment by Dumluregn** [comment] 2019-11-12 08:46
Ok, so a bit of clarification:

* [getCommonAncestor()](https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_dom_selection.html#method-getCommonAncestor) method returns null when `selection` is empty
* `selection` is empty if it has no `ranges`. As a collapsed selection at the end of line still has one `range`, such a `selection` is not empty and therefore `getCommonAncestor` returns just the current element.

I hope it will be helpful for you. For now I'm closing this issue as the method works as intended.

**Closed by Dumluregn** 2019-11-12 08:46 UTC
Labels: status:pending, type:bug
