### ISSUE TITLE
On changing the color of characters in the Table in CKEditor causes the scroll to move to the top the page

### ISSUE THREAD

**Issue by Vivek2393** [ckeditor/ckeditor4#3834] opened 2020-02-04 04:50 UTC
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. Create 10*2 table
2. insert content in every cell such that Scroll bar appears.
3. Scroll down and Go to last cell.
4. Change the text color of cell.
5. Right click on table and change alignment to Right.

### Expected result

*Scroll moves to the top of editor window

### Actual result

*Scroll should remain in that place

## Other details

* Browser: Specific to FireFox
* OS: Win 10 
* CKEditor version : 4.13.1
* Installed CKEditor plugins: Tested on ckeditor 4 Demo

**Comment by jacekbogdanski** [comment] 2020-02-11 08:50
I'm not able to reproduce the issue using:
* https://ckeditor.com/latest/samples
* https://ckeditor.com/ckeditor-4/demo/#document

Could you link the demo you used and provide some gif image so we can make sure we follow the same path? Some online demo provided via https://codepen.io or other JS editor would be also helpful.

**Comment by Comandeer** [comment] 2020-02-25 10:23
Hi, It's been a while since we last heard from you. We're closing this issue for now. Still, feel free provide us requested feedback, so that we can reopen this issue.

**Closed by Comandeer** 2020-02-25 10:23 UTC
Labels: status:pending, type:bug
