### ISSUE TITLE
Accessibility: NVDA reading unnecessary details when selecting an item of dropdown

### ISSUE THREAD

**Issue by lumills** [ckeditor/ckeditor4#4050] opened 2020-05-13 18:22 UTC
## Type of report

Bug

## Provide detailed reproduction steps (if any)
 
1)Launch a ckeditor instance with the Link plugin and button

2)Navigate to "Editor Tool Bar" section.

3)Navigate to Button "Link" and click on it.

4)Navigate To tab panel "Link Info" option.

5)Start NVDA and navigating Link type combo box.

### Expected result

​It should not read unnecessary content while selecting any list option. It should read only selected content.

### Actual result

NVDA announced unnecessary content while selecting any list item from Combo box.

## Other details
Same issue is also observed in following screens :

1)Image: When we select any item from "target" combo box.

2)Target:When we select any item from "Target" combo box.

3)Table Properties:When we select any item from combo boxes.

4)Advance :When we select any item from "Language Direction access key" combo boxes

***Seems that the issue is rooted in the fact that the element role is listed as presentation rather than combobox: role\x3d"presentation"' ****
* Browser: All I believe (testing mostly in Firefox)
* CKEditor version: 4

**Comment by Comandeer** [comment] 2020-05-14 13:23
Hi [**@lumills**](https://github.com/lumills),

does it occurs only in NVDA or in any other screen reader too?

**Comment by lumills** [comment] 2020-05-14 16:32
Hi @Comandeer ,

Bug and repro that I'm seeing appears to be NVDA specifically

**Comment by Comandeer** [comment] 2020-05-21 12:19
I can't reproduce it in NVDA 2020.1. For changing selected options inside collapsed `select` element, only the selected option is read. For open `select` only the selected option + the number of the option ("x of y") is announced. I don't hear any unnecessary info. Could you provide more info about the actual output and the expected one?

**Comment by Dumluregn** [comment] 2020-06-08 08:40
Hi, it's been a while since we last heard from you. We're closing this issue for now. Still, feel free provide us requested feedback, so that we can reopen this issue.

**Closed by Dumluregn** 2020-06-08 08:40 UTC
Labels: accessibility, status:pending, support:2, type:bug, workload:medium
