### ISSUE TITLE
Mention does not work with some languages(Arabic or Persian)

### ISSUE THREAD

**Issue by parsysm** [ckeditor/ckeditor4#5398] opened 2023-01-01 22:06 UTC
Set a feed with some Hebrew text:

feed: [ 'علی', 'امین', 'Barney', 'Lily', 'Marshall', 'Robin', 'Ted' ]
Switch the keyboard to persian,
Try to autocomplete them (they correspond to "hldk" and "ugd" in an English keyboard).

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

![83935745-9ea77700-a7d1-11ea-922f-c75fe54a1b8b](https://user-images.githubusercontent.com/13693626/210185925-81bcb7ab-3164-4c9c-b376-b79ae02931e0.gif)

As you can see, There is no problem with English letters. But autocomplete does not work in Persian letters.

my config:

CKEDITOR.replace( 'editor', { extraPlugins: 'mentions', mentions: [ { feed:  ['amin', 'امین','علی', 'John'], marker: '@', minChars: 0 }] } );

version: "4.18.0"

**Comment by KarolDawidziuk** [comment] 2023-01-02 10:58
Hi @parsysm and thank you for the report.

I can confirm this issue.

**Comment by parsysm** [comment] 2023-01-02 16:38
> Hi @parsysm and thank you for the report.
> 
> I can confirm this issue.

hi @KarolDawidziuk i fixed it this problem with Regexp on createPattern function method with This pattern [_a-zA-Z0-9À-ž\u0600-\u06FF\s]

**Comment by KarolDawidziuk** [comment] 2023-01-12 11:07
Hello @parsysm 
Good to hear that you solved your issue. 

The [pattern property](https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_plugins_mentions.html#property-pattern) was introduced to handle such cases because it is difficult to cover all possible cases.

Also, since this report is outdated, I'm closing it.

**Closed by KarolDawidziuk** 2023-01-12 11:07 UTC
Labels: type:bug, status:confirmed, plugin:mentions
