### ISSUE TITLE
Wrong format or font family in div editor BR mode

### ISSUE THREAD

**Issue by woody-li** [ckeditor/ckeditor4#5355] opened 2022-10-21 08:38 UTC
## Type of report

2 Bugs

## Provide detailed reproduction steps (if any)

* CodePen: https://codepen.io/Woody-lxf/pen/rNvXxgO

Bug 1:
* Focus in a empty or text-only editor, then the format will recognize as "Normal(DIV)".
* But it should be "normal".

------

Bug 2:
>Easier to reproduce in BR mode, sometimes in default.

1. Set text content as a font-family.
2. Select all content and delete them.
3. Input text again.

### Expected result
The text content displays as default font, and font selector in toolbar shows as default.

### Actual result
The text content displays as the last font.

>But blur editor before input again will works well.

## Other details

* CKEditor version: 4.20.0
* Installed CKEditor plugins: divarea

**Comment by KarolDawidziuk** [comment] 2022-10-21 11:06
Hi @woody-li and thank you for the report.

Bug1: You've added `divarea` plugin and `ENTER_BR` mode to the editor config, so the format `Normal(DIV)` is a proper value because the given content is wrapped by `div` no paragraph.

I'm not sure about Bug2

What do you mean by "Set text content as font family". Is it changing the font from the default to a different one? if yes, it is not a bug, but as with the first report correct behavior as this font is applied to the selected item and not to the whole editor. After removing all the content, i.e. the element on which this style was added, the font will also be removed.

I'm closing this issue as by-design behavior but if you feel that there is still an issue with the editor, feel free to reopen this issue.

**Closed by KarolDawidziuk** 2022-10-21 11:06 UTC
Labels: type:bug

**Comment by woody-li** [comment] 2022-10-24 01:56
@KarolDawidziuk Thanks for your reply.

I'm confused with the Bug2.
For example():

1. Input some text, and set it to "Georgia" font.
2. Select all text and delete them.
3. The editor is empty for now and the font selector displays default.
4. The next inputed text is expected as default font, but it still displays as "Georgia" and font selector is default.



![cke-font-family](https://user-images.githubusercontent.com/16889642/197432639-5a6dfea2-ada3-4cbf-b050-1a05989d598e.gif)
