### ISSUE TITLE
Failing test: tests/plugins/widget/manual/inline

### ISSUE THREAD

**Issue by sculpt0r** [ckeditor/ckeditor4#4696] opened 2021-05-12 23:08 UTC
## Type of report

Failing test

## Provide detailed reproduction steps (if any)

1. Select inlined Lenna picture with a single mouse click
2.  Drag & drop inlined anchor to another place. It is important to drag it from the beginning. Without previous selecting

![DnD inline widgets](https://user-images.githubusercontent.com/6498567/118055001-95cb0800-b387-11eb-802b-717a6904c383.gif)

### Expected result

Anchor is moved to the new location

### Actual result

The previously selected (in step 1) image was moved to the new location and the anchor remains in the same position.

## Other details

* Browser: IE11
* OS: Windows 10
* CKEditor version: 4.16.1
* Installed CKEditor plugins: -

**Comment by f1ames** [comment] 2021-05-14 14:43
Interesting finding - looking at the gif the image widget is selected the entire time (with our fake selection which you can tell by the blue border). And the anchor get native IE11 "object selection/resizer" which doesn't affect our widget selection.

It might be a little confusing (since you have to selections at the same time) but I would say it is intended behavior that widget is moved instead of anchor. And AFAIR there is no reasonable way to get rid of the native IE11 resizer so that's the only reason it's there. Thus I'm closing this issue.

**Closed by f1ames** 2021-05-14 14:43 UTC
Labels: browser:ie11, resolution:upstream, status:confirmed, type:failingtest
