### ISSUE TITLE
"Source" code button not clickable in Internet Explorer 11

### ISSUE THREAD

**Issue by Tomcraft1980** [ckeditor/ckeditor4#3746] opened 2019-12-19 15:06 UTC
The "Source" button is currently not clickable in Internet Explorer 11

Steps to reproduce:

1. Downloas latest (4.13.1) full package of CKEditor and unzip
2. Navigate to samples folder and open index.html
3. Click button "Source"

Expected result:

Exprected result is that the source view will appear as it does in Firefox for example.

Actual result:

The "Source" button just fades grey and the source view is not displayed.

Other details:

* Browser: Internet Explorer 11.0.9600.19463
* OS: Windows 8
* CKEditor version: 4.13.1
* Installed CKEditor plugins: Standard default plugins downloaded as part of full package

**Comment by jacekbogdanski** [comment] 2019-12-20 08:43
Hello, I can't reproduce the issue as you can see on the enclosed gif image:

![ie11clickable](https://user-images.githubusercontent.com/10279586/71241880-f417c680-230c-11ea-9fa2-c8f9cf15a015.gif)

Could you provide minimal CKEditor4 demo with the issue e.g. using https://codepen.io ?

**Comment by Tomcraft1980** [comment] 2019-12-20 12:03
What browser did you test?
I tested in:
* Browser: Internet Explorer 11.0.9600.19463
* OS: Windows 8.1

and:
* Browser: Internet Explorer 11.950.17134.0
* OS: Windows 10

I tested again with a custom minimal basic build:

![Bildschirmfoto 2019-12-20 um 12 10 04](https://user-images.githubusercontent.com/5065393/71253691-e2dcb300-2328-11ea-8195-ba4ecf1e7344.png)

On Windows 10 it works in Microsoft Edge 42.17134.1.0 but not in Internet Explorer.

Internet Explorer:

![IE10](https://user-images.githubusercontent.com/5065393/71253551-8d080b00-2328-11ea-91d2-ec46c9d64fc9.gif)

Microsoft Edge:

![Edge42](https://user-images.githubusercontent.com/5065393/71253558-942f1900-2328-11ea-9398-be3961909775.gif)

I cannot use codepen in Internet Explorer:

![Bildschirmfoto 2019-12-20 um 11 09 02](https://user-images.githubusercontent.com/5065393/71253625-bfb20380-2328-11ea-9023-e4ecad28b669.png)

**Comment by jacekbogdanski** [comment] 2019-12-23 10:20
Works fine for me on Windows 8.1 IE `11.0.9600.18953` and Windows 10 IE `11.785.16299.0`. You can use any other tool like e.g. https://jsbin.com/ which should work with IE11.

**Comment by Tomcraft1980** [comment] 2019-12-24 13:42
Does the downloaded index.html from sample folder work for you?
I can confirm that it works in jsbin.com but not the local executed demo from the samples folder.
See: https://jsbin.com/fadalemaka/1/edit?html,js,output
Any other ideas?

**Comment by jacekbogdanski** [comment] 2019-12-29 13:10
Yes, it works fine when opening `samples/index.html` file for Edge and IE11. @Dumluregn could you try to reproduce the issue? I could miss something but works fine for me, also it's unlikely that such an issue would pass our testing phase.

**Comment by Tomcraft1980** [comment] 2019-12-29 14:01
Ah! It works when executing from C:\ckeditor\samples\index.html but **not** in my virtual machine from path \\Mac\Home\Desktop\ckeditor\samples\index.html (parallels shared folder).

**Comment by jacekbogdanski** [comment] 2019-12-29 14:23
So, it may seem like there are some missing static files when using a shared folder for VM, but it's rather 3rd party software issue, not CKEditor4 itself. Due that I'm closing the issue, but if you still consider it as a CKE4 bug @Tomcraft1980, please, provide us feedback so we can reopen the issue again.

**Closed by jacekbogdanski** 2019-12-29 14:23 UTC
Labels: status:pending, type:bug
