### ISSUE TITLE
CKEDITOR v4.14.1 - enterMode: CKEDITOR.ENTER_BR vs Chrome for Android v85.0.4183.81

### ISSUE THREAD

**Issue by DaveGYNWA** [ckeditor/ckeditor4#4261] opened 2020-09-06 10:44 UTC
## Type of report

Bug

## Provide detailed reproduction steps (if any)

https://test.ynwa.tv/ckeditor/ck4.html

1) Upgrade Chrome to latest version on Android
2) Access above link
3) Press Enter key

### Expected result

*What is the expected result of the above steps?*

Expected result: new line inserted as <br>

### Actual result

Actual result: On-screen keyboard disappears, requiring tapping in to the textarea to return to view

## Other details

Originally reported on Invision Community site, but reproducible on stock-CKEDITOR installation

* Browser: Chrome for Android, v85.0.4183.81
* OS: Tested on Android 10
* CKEditor version: 4.14.1
* Installed CKEditor plugins: None

**Comment by DaveGYNWA** [comment] 2020-09-06 11:08
Looks like a duplicate of https://github.com/ckeditor/ckeditor4/issues/4252

**Comment by Comandeer** [comment] 2020-09-06 15:59
Yes, it's a duplicate of #4252.

**Closed by Comandeer** 2020-09-06 15:59 UTC
Labels: type:bug
