### ISSUE TITLE
Code and characters instead of plain text

### ISSUE THREAD

**Issue by hikingcycler** [ckeditor/ckeditor4#5098] opened 2022-02-19 19:29 UTC
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. Typed message/text into the editor using plain text, click "done" and then exit. 
2. Go back into the program, reopen the editor and all the plain text is now a series of characters and code instead of the plain text that was typed in.

[CK Editor Weird Characters Issue](https://user-images.githubusercontent.com/99500351/153646848-f548943c-7e58-4960-ab72-ce34a36dfc5a.png)

[CK Editor Weird Characters Issue example 2](https://user-images.githubusercontent.com/99500351/153646927-7de2e8e7-200a-49fc-ae28-a42b444ce42a.png)

%3Cp%3EThank+you+for+registering+your+scouts+and+adults+as+participants+or+staff+for+our+Potawatomi+Klondike+Derby+this+weekend.+The+weather+should+be+perfect+for+the+Klondike+Derby.+Boots+are+a+necessity%2C+the+snow+is+deep%2C+2%2B+feet.%26nbsp%3B%3C%2Fp%3E%0A%0A%3Cp%3EEach+person+must+remember+to+bring+at+least+one+mask+with+them+to+this+event.%3C%2Fp%3E%0A%0A%3Cp%3EPlease+read+the+UPDATED+%3Ca+href%3D%22https%3A%2F%2Fscoutingevent.com%2Fattachment%2FBSA129%2Fdocument_16438405360_4182.pdf%22+target%3D%22_blank%22%3E%3Cstrong%3EPW+Klondike+Derby+Program+Guidebook%3C%2Fstrong%3E%3C%2Fa%3E+for+a+more+comprehensive+%26quot%3BWhat+to+Bring%26quot%3B+list+and+other+important+information.%3C%2Fp%3E%0A%0A%3Cp%3EBelow+is+a%26nbsp%3Blink+to+your+Registration+Summary.%26nbsp%3B+If+you+have+not+yet+added+the+names+of+your+participants%2C+use+it+to+add+them+now.%3C%2Fp%3E%0A%0A%3Cp%3ENOTE%3A%26nbsp%3B+This+email+will+be+sent+again+after+registration+closes+at+4+PM.%3C%2Fp%3E%0A%0A%3Cp%3E%3Cstrong%3E%7B%24registrationSummary%7D%3C%2Fstrong%3E%3C%2Fp%3E%0A

## Other details

* Browser: … Chrome
* OS: … Windows 10
* CKEditor version: … 445
* Installed CKEditor plugins: …

**Comment by Comandeer** [comment] 2022-02-19 21:09
Duplicate of #5086.

**Closed by Comandeer** 2022-02-19 21:09 UTC
Labels: type:bug
