### ISSUE TITLE
Merged table cells difficult to select

### ISSUE THREAD

**Issue by JeroenAtWorkI** [ckeditor/ckeditor4#4119] opened 2020-06-22 09:48 UTC
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. Go to the [guide](https://ckeditor.com/docs/ckeditor4/latest/examples/table.html#!/guide/dev_table)
2. Merge 2 cells (top/bottom)
3. Move your cursor where the bottom cell was.
4. Right click
_The browsers context menu is shown._
5. Close the context menu
6. Click the bottom half off the cell.
_The entire column is selected._
7. Click the cell, drag and release.
_The column get resized._

### Expected result
4. The ckeditor contextmenu was expected
6. I expected to select the text and be able to modify the text.
7. I expected the text to be selected.

### Actual result
4 The browsers context menu is shown.
6 The entire column is selected.
7 The column get resized.

![ckeditor-bug](https://user-images.githubusercontent.com/67258429/85273448-e7bc2400-b47d-11ea-805b-73d2f7284d6b.gif)

## Other details
* Browser: Chrome and Internet Explorer 11
* OS:Windows 10
* CKEditor version: v4.3.0-master-d769233
- plugins: tableselection, tableresize

It looks like the cursor is wrong in the bottom cell, and that's the cause of the problems.

**Comment by jacekbogdanski** [comment] 2020-06-23 13:14
Duplicate of https://github.com/ckeditor/ckeditor4/issues/3961

**Closed by jacekbogdanski** 2020-06-23 13:14 UTC
Labels: type:bug
