### ISSUE TITLE
Anchor is duplicated when edited

### ISSUE THREAD

**Issue by AlexanderMur** [ckeditor/ckeditor4#3863] opened 2020-02-16 19:45 UTC
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. go to https://ckeditor.com/latest/samples/index.html
2. make some bold text
3. make it anchor
4. try to edit anchor - double click 
5. press ok

example: https://i.gyazo.com/fa442d930a3b59eec754ca0b5956b8b5.mp4

Every time when you anchor is edited with style like bold underline etc. - this makes a doubled anchor instead of just editing.

### Expected result
anchor is edited

### Actual result
anchor is doubled

## Other details

* Browser: Chrome 80.0.3987.106
* OS: Windows 10 1903
* CKEditor version: 4

**Comment by Comandeer** [comment] 2020-02-17 17:18
I can confirm the issue. Seems like internal `getSelectedAnchor` function assumes that text can be surrounded only by the link itself, not considering more complex situations like:

```html
<a><strong>Text</strong></a>
```

**Comment by AlexanderMur** [comment] 2020-03-16 06:48
How can I fix this without modifying source code?

**Comment by deyankush** [comment] 2021-01-20 08:18
Any updates on this defect? I am facing the same issue. This was working in v4.7. Since we migrated to v4.13 its stopped working.

**Comment by Dumluregn** [comment] 2021-01-20 09:17
Hello @deyankush, thank you for bringing to our attention that it's a regression. It was indeed introduced in `4.13.0`, which means we probably try to handle it in the near future.

**Comment by vinaydhakre** [comment] 2021-01-20 10:00
@Dumluregn - I am facing the same issue. Could you take this defect on priority so that we can get this fix ASAP?

**Comment by Dumluregn** [comment] 2021-01-20 10:03
Unfortunately we've just froze the branches before release, so this issue will have to wait for the next one. However if nothing unexpected happens we should be able to fix this for then.

**Comment by vaibhav198989** [comment] 2021-01-20 12:30
@Dumluregn when is the next release expected ?

**Comment by deyankush** [comment] 2021-01-20 13:03
> Hello @deyankush, thank you for bringing to our attention that it's a regression. It was indeed introduced in `4.13.0`, which means we probably try to handle it in the near future.

Is it possible to get a patch on 4.13?

**Comment by Dumluregn** [comment] 2021-01-20 13:36
@vaibhav198989 we do not have a date set, probably in a few months.
@deyankush we do not provide backwards patches, but if you have a commercial license you can reach [our support team](https://ckeditor.com/contact/) for workaround or help in your own development of this fix.

**Comment by deyankush** [comment] 2021-01-28 05:55
@Dumluregn this commit seems to have caused the regression: https://github.com/ckeditor/ckeditor4/commit/7c93a77f42b757207398549f68153e36d773929e
@jacekbogdanski could you please confirm?

**Comment by jacekbogdanski** [comment] 2021-08-13 10:14
Closed in https://github.com/ckeditor/ckeditor4/pull/4733

**Closed by jacekbogdanski** 2021-08-13 10:14 UTC
Labels: type:bug, status:confirmed, plugin:link, regression, size:M
