### ISSUE TITLE
onChange event can report invalid HTML

### ISSUE THREAD

**Issue by masonwheeler** [ckeditor/ckeditor4#3785] opened 2020-01-15 20:27 UTC
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. Create a `contenteditable` ckeditor div, with its `onChange` event bound to a function that will write the raw HTML out to the console.
2. Open in Chrome (most recent version) and open the Chrome dev tools.
3. Click into the editable div to edit it.
4. Press <kbd>Enter</kbd> to insert a new line.
5. Paste in the following: `<h1>Bad nesting`
6. Observe the result printed to the console, with the `<h1>` element wrapped in the `<p>` element that the editor creates by default.
7. Click out of the editable div, then switch to the "Elements" tab in dev tools.  Inspect the div's DOM.
8. A `<h1>` nested inside a `<p>` is invalid per the HTML standard, so the browser has automagically repaired it into a valid DOM.
9. Observe that the corrected DOM is never printed to the console.

### Expected result

It is expected that when the editor's content is changed, the `onChange` event will fire.

### Actual result

The `onChange` event reports the invalid HTML, but fails to report the corrected version.

## Other details

* Browser: Chrome
* OS: Windows 10
* CKEditor version: version:"4.6.2 (Full)", revision:"20af917"

**Comment by f1ames** [comment] 2020-01-16 06:48
Hello @masonwheeler,
I have some difficulties reproducing your scenario. How do you paste the broken markup (step 5)? If you copy/paste it from here as a plain text it is also pasted as a plain text in CKEditor and `getData()` call returns:

```
<p>&lt;h1&gt;Bad nesting</p>
```

so it is not treated as HTML element, which can be also seen in dev console:

![image](https://user-images.githubusercontent.com/1061942/72500269-6f00ce00-3834-11ea-817a-e792c9233892.png)

Can you elaborate a little more on this one? Here is the codepen for easy reproduction - https://codepen.io/f1ames/pen/WNbgGZe.

**Comment by jacekbogdanski** [comment] 2020-01-29 09:24
Hi, It's been a while since we last heard from you. We're closing this issue for now. Still, feel free provide us requested feedback, so that we can reopen this issue.

**Closed by jacekbogdanski** 2020-01-29 09:24 UTC
Labels: status:pending, type:bug
