### ISSUE TITLE
Bleeding tests – Uncaught TypeError: Cannot read property 'find' of null

### ISSUE THREAD

**Issue by Comandeer** [ckeditor/ckeditor4#4620] opened 2021-04-14 15:51 UTC
## Type of report

Failing test

## Provide detailed reproduction steps (if any)

Our tests are [bleeding with error](https://travis-ci.com/github/ckeditor/ckeditor4/jobs/498000243#L454):

> Uncaught TypeError: Cannot read property 'find' of null

### Expected result

There is no error.

### Actual result

There is some uncaught error.

## Other details

* CKEditor version: `master`

**Comment by Dumluregn** [comment] 2021-04-15 08:42
Similar to https://github.com/ckeditor/ckeditor4/issues/3772, but different error message 🤔

**Comment by sculpt0r** [comment] 2021-04-28 05:23
Looks like each dot `.` in CI is one unit test. Based on that it could be easier to find which tests throws an error :)

**Comment by sculpt0r** [comment] 2021-09-06 09:13
Currently, I cannot reproduce this error (especially we are using bender runner on CI). Even our full test runs don't show these errors. Can we close this one @jacekbogdanski ?

**Comment by jacekbogdanski** [comment] 2021-09-06 11:09
Sure, I can also confirm that it looks stable https://app.travis-ci.com/github/ckeditor/ckeditor4/jobs/535717870 we can reopen the ticket if we will see it's bleeding again.

**Closed by jacekbogdanski** 2021-09-06 11:09 UTC
Labels: status:confirmed, type:failingtest, size:S
