### ISSUE TITLE
CKEditor is not usable once you detach and attach its parent div from DOM

### ISSUE THREAD

**Issue by arpangn** [ckeditor/ckeditor4#3509] opened 2019-09-27 14:42 UTC
## Bug

Bug

## Provide detailed reproduction steps (if any)

[sample.zip](https://github.com/ckeditor/ckeditor4/files/3663183/sample.zip)

1. Download attached file and place sample.html in your CKEditor folder
2. Click LoadCK button
3. Click Detach button
4. Click Attach button

Notice that CKEditor is not usable.

In my application, I really have a need to detach and attach the parent div from DOM. I understand it can be solved by creating a new instance of CKEditor but i want to reuse the existing instance.

Could you please check and suggest if there is any workaround/solution?

* Browser: All browsers
* OS:Windows 10
* CKEditor version: 4.10.1
* Installed CKEditor plugins:None

**Comment by Comandeer** [comment] 2019-09-27 14:53
Detaching and attaching node with the initialized editor seems like an edge case. Fortunately there seems to be a simple workaround: use [Div Editing Area plugin](https://ckeditor.com/cke4/addon/divarea). The issue is connected with the fact that default editable area is inside `iframe` and its content is reloaded after reattaching. However CKEditor does not detect the reloading, therefore not updating the reference to the editable. Switching to editable based on `div` should fix the issue.

**Comment by sculpt0r** [comment] 2022-05-23 11:05
Since the [`4.17.0` release](https://github.com/ckeditor/ckeditor4/blob/master/CHANGES.md#ckeditor-417) - we introduce a MutationObserver that should handle this case (even the `iframe` usage). Please notice that we have a [config option](https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_config.html#cfg-observableParent) that helps to adjust the efficiency of this solution.

For a wider knowledge about editor behavior with detaching, please take a look at [documentation](https://ckeditor.com/docs/ckeditor4/latest/features/delayed_creation.html).

Since the issue is solved with `4.17.0` and we have now even the newest versions (that also include some improvements and bug fixes in this area) - I'm closing this issue.

**Closed by sculpt0r** 2022-05-23 11:05 UTC
Labels: type:bug, status:confirmed, plugin:wysiwygarea
