### ISSUE TITLE
When inserting a link with bbcode tag the display part is removed

### ISSUE THREAD

**Issue by xillibit** [ckeditor/ckeditor4#4945] opened 2021-10-30 19:26 UTC
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. Use the button link in ckeditor toolbar to open the link options
2. Paste a link in URL and display text part and submit
3. Look at source it look like that : [url]https://github.com/ckeditor/ckeditor4[/url]

### Expected result

Link with display text should be displayed like that in source : [url=https://github.com/ckeditor/ckeditor4]https://github.com/ckeditor/ckeditor4[/url]
 
*What is the expected result of the above steps?*

### Actual result

In all cases the links are like that in source : [url]https://github.com/ckeditor/ckeditor4[/url]

*What is the actual result of the above steps?*

Use the button in ckeditor toolbar to insert a link in message area

## Other details

* Browser: Firefox 93.0
* OS: win 10 20H1
* CKEditor version: 4.16.2
* Installed CKEditor plugins: bbcode

**Comment by KarolDawidziuk** [comment] 2021-11-03 07:19
Hello @xillibit, thank you for the report.

This doesn't look like a bug because once you want to display the link only, you don't need to add anything to the `Display Text` field.
In your example, link and display text would be the same, which is unnecessary that's why this is removed. 
This field is used when we want to display links somehow differently like "Click me".

At this point, I'm closing this issue with a resolution: `by design`. If you can prove this behavior as invalid - feel free to open another issue.

**Closed by KarolDawidziuk** 2021-11-03 07:19 UTC
Labels: type:bug, resolution:by-design
