### ISSUE TITLE
Pasting plain text over existing data fails in Firefox

### ISSUE THREAD

**Issue by jackwickham** [ckeditor/ckeditor4#3475] opened 2019-09-22 16:25 UTC
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. Enter several words into the editor, such as 
> Some test content
2. Select a section from the middle of the text, such as "test"
3. Paste plain-text content, such as from the URL bar or a search box

### Expected result

The selected text is replaced with the clipboard contents

### Actual result

An `IndexSizeError` is thrown usually. When stepping through with the dev tools, it instead inserts the clipboard contents just before the selection, without removing it.

## Cause
I think there are a couple of issues here. The first is that the Firefox-specific error handed in [`selection.selectRanges`](https://github.com/ckeditor/ckeditor4/blob/94bb29757020dc6111927a14d9ef201c2f6da136/core/selection.js#L2240) no longer matches because they have replaced it with a more user-friendly error string. Fixing this error means that the behaviour when stepping through with the dev tools (inserting the clipboard contents just before the selection rather than replacing it) occurs instead.

That Firefox error is caused by trying to call `Range.setEnd` (on a native range) with an outdated reference to the end container, I think from before the container was split to move the selected content into its own TextNode. That means that endIndex is > TextNode.length, so it is a nonsense range and the exception is triggered.

I've been trying to debug the issue further, but because it behaves differently when breakpoints are used I haven't been able to figure out more than that.

## Other details

* Browser: Firefox 69
* OS: At least Windows and Linux
* CKEditor version: major
* Installed CKEditor plugins: default

**Comment by f1ames** [comment] 2019-09-23 06:29
Hello @jackwickham,
I'm not able to reproduce the above issue in Firefox 69 - tested it on Basic, Standard and Full preset (see here - https://ckeditor.com/docs/ckeditor4/latest/examples/basicpreset.html).

Are you able to reproduce the issue on our docs linked above? Do you use any 3rd-party plugins or have specific editor configuration?

**Comment by jackwickham** [comment] 2019-09-24 21:45
@f1ames I also can't reproduce it on the examples editor that you linked. However, I can reproduce it with my local clone, and I have hosted a reproducible demo at https://www.jackw.net/cke-firefox-paste-demo/ - it is running the latest major commit there, 9ea9e9615, with no changes to plugins or any other wierdness.

To reproduce in that demo in Firefox:
* Select "copyme" and copy it to your clipboard
* Double click on "demo" in the editor, so that just "demo" is selected
* Paste

**Comment by msamsel** [comment] 2019-09-25 15:00
I was able to confirm the issue. I also made a bisect to check when it was introduced. It appeard with this commit: b659fbaa352fb57852e90196535b183c9772f271
The issue can be reproduced on night build:
https://nightly.ckeditor.com/

**Comment by msamsel** [comment] 2019-10-01 14:03
I'm pretty sure that issue is caused because of text node manipulation.
There is stored a selection, before paste operation. Then there is insert a plain text, which divides text node into 2 text nodes and inserts new content between them. So as a result from 1 text node we obtained 3.
Then there is a mechanism to restore selection for FF, which tries to put selection in a non-existing place as the node is now shorter.

**Comment by f1ames** [comment] 2019-10-02 12:41
Fixed in https://github.com/ckeditor/ckeditor4/commit/7d48d2b30f5a9d29033cb63a135fddb1b23b5164.

**Closed by f1ames** 2019-10-02 12:41 UTC
Labels: browser:firefox, regression, status:confirmed, target:minor, type:bug
