### ISSUE TITLE
Chrome 89 display problem for iframedialog plugin

### ISSUE THREAD

**Issue by Wizard13** [ckeditor/ckeditor4#4561] opened 2021-03-08 16:55 UTC
## Type of report

Bug

Chrome 88 and 89 (latest) display a small height of the webpage inside iframedialog. When title bar is clicked, the webpage is displayed correctly. Problem appeared since v88.

1. Go to https://jsfiddle.net/14gn8o2x/
2. Click question mark button to launch iframedialog with an embedded wikipedia page

### Expected result

Webpage is displayed using whole height of dialog.

### Actual result

Webpage is displayed using a smaller height. Clicking on title bar, restores the height.

## Other details

* Browser: Chrome 88 and 89 (latest)
* OS: Windows 10 x64
* CKEditor version: 4.16.0
* Installed CKEditor plugins: full

**Comment by sculpt0r** [comment] 2021-03-10 10:38
Hi @Wizard13 ,

Thank you for the report.

I can confirm this issue. It looks more like a bug introduced by chrome - not the editor itself. However, we will try to put this issue in our schedule.

**Comment by Wizard13** [comment] 2021-06-13 07:46
@sculpt0r can you confirm that the bug no longer exists with Chrome 91? I'm using Chrome 91.0.4472.101 and it seems it's all good now.

**Comment by sculpt0r** [comment] 2021-06-17 05:56
Hi @Wizard13 
Thank you for pinging me. It looks like Chrome 91 fixed this issue, so I'm closing it.

Thank you for your involvement :)

**Closed by sculpt0r** 2021-06-17 05:56 UTC
Labels: browser:chrome, plugin:dialog, size:?, status:confirmed, type:bug
