### ISSUE TITLE
Additional styles preserved when copy/paste or drag/drop text from external source

### ISSUE THREAD

**Issue by f1ames** [ckeditor/ckeditor4#986] opened 2017-09-29 12:30 UTC
## Are you reporting a feature request or a bug?

Bug

## Provide detailed reproduction steps (if any)

1. Go to https://sdk.ckeditor.com/samples/fullpreset.html.
2. Copy/paste or drag/drop some text from outside of the editor to editor.

### Expected result

Inserted text matches styles of the context.

### Actual result

Inserted text preserves all its original styles.

![image](https://user-images.githubusercontent.com/1061942/31015832-53eaeeea-a522-11e7-9692-73f6f1a8a91e.png)

I think the similar behaviour was the reason why _[pasteFilter](https://docs.ckeditor.com/#!/api/CKEDITOR.config-cfg-pasteFilter): 'semantic-content'_ were introduced in _Blink/Webkit_ browsers so maybe it can be reused here.

## Other details

* Browser: **Edge 16+ (preview)**
* OS: Windows 10
* CKEditor version: 4.7.3
* Installed CKEditor plugins: `clipboard`

**Comment by f1ames** [comment] 2017-09-29 12:54
It will be a good idea to wait with this fix for #468.

**Comment by mlewand** [comment] 2017-09-29 13:34
Duplicate of #921.

**Comment by f1ames** [comment] 2017-09-29 13:56
@mlewand Are you sure it is a duplicate of #921?

#921 is about incorrect transfer type recognition and this one is about preserving styles (btw. fixing transfer type recognition does not fix this issue).

**Comment by mlewand** [comment] 2017-09-29 15:03
@f1ames actually I might have done it too quickly. Above issue relates only to drag & drop, right?

However I wasn't able to reproduce it on https://sdk.ckeditor.com/samples/fullpreset.html with `Microsoft EdgeHTML 15.15063`, is it Edge 16 only thing?

**Comment by f1ames** [comment] 2017-09-29 15:10
@mlewand, no it is both copy/paste and drag/drop. You are right that it is only Edge 16 (updated **Browser** field to **Edge 16+** so it is more visible).

**Comment by f1ames** [comment] 2017-10-03 11:08
@mlewand considering my latest comment, do you think we should reopen this issue?

**Comment by mlewand** [comment] 2017-10-03 12:06
K let's keep an eye on it as a separate issue.

**Comment by f1ames** [comment] 2017-11-10 09:19
Looks like upstream https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/14591438/

**Comment by Dumluregn** [comment] 2020-07-23 13:38
This issue is no longer reproducible in the latest Edge browser version.

**Closed by Dumluregn** 2020-07-23 13:38 UTC
Labels: browser:edge, plugin:clipboard, status:confirmed, type:bug
