### ISSUE TITLE
Paste text from word / libreoffice, some anchors are created in ckeditor

### ISSUE THREAD

**Issue by ranielli** [ckeditor/ckeditor4#3833] opened 2020-01-31 19:01 UTC
## Type of report

Bug

## Provide detailed reproduction steps (if any)

When I paste text from word / libreoffice, some anchors are created in ckeditor

### Expected result

Shouldn't generate any random anchors

### Actual result

some anchors are created in ckeditor 

![image](https://user-images.githubusercontent.com/1909238/73566523-d62c9e00-4442-11ea-8c6f-70da2acd1ada.png)

## Other details

* Browser: all
* OS: all
* CKEditor version: 4.14
* Installed CKEditor plugins: all

**Comment by Dumluregn** [comment] 2020-02-03 07:41
Hello, could you provide a file from which you paste content to editor? I see you are using unreleased yet version, so it would be very helpful and maybe we could fix this before release.

**Comment by ranielli** [comment] 2020-02-03 14:40
[teste.docx](https://github.com/ckeditor/ckeditor4/files/4148414/teste.docx)

follow the file

**Comment by Dumluregn** [comment] 2020-02-04 08:34
Hello, thank you for the file. I pasted it and the outcome is:

![](https://user-images.githubusercontent.com/10883184/73727237-5d269280-4731-11ea-9508-96ad6bc00dfc.png)

Is this the same for you? Could you send a file which produces multiple anchors (as on the screen in the first post)?

**Comment by 90Nobby** [comment] 2020-02-14 12:01
Hi,

I have a very similar issue where the editor is loading a word template upon screen load for the user to amend and send, however some templates are loading with these anchor flags where as others don't.

When looking at the word templates they look exactly the same.

Is there anyway to just hide the flag? As it doesn't seem to be impacting the styling or the UX.
![2020-02-14_11-58-12](https://user-images.githubusercontent.com/61050697/74530300-9c1eca00-4f21-11ea-8d9f-a26d0f4a2540.png)

Cheers

**Comment by Dumluregn** [comment] 2020-02-14 12:27
Hello, could you provide a docx file from which you paste this content?

**Comment by Dumluregn** [comment] 2020-02-28 09:18
Hi, It's been a while since we last heard from you. We're closing this issue for now. Still, feel free provide us requested feedback, so that we can reopen this issue.

**Closed by Dumluregn** 2020-02-28 09:18 UTC
Labels: plugin:pastefromlibreoffice, plugin:pastefromword, status:pending, type:bug

**Comment by SimonBrazell** [comment] 2020-12-10 23:36
For those who are having the same problem and stumble across this issue while searching for a solution, for me it was caused by setting `allowedContent: true` in the editor config, removing this resolved the issue.
