### ISSUE TITLE
"TypeError: Cannot read property 'unselectable' of null" thrown when working with CKEditor in integrations

### ISSUE THREAD

**Issue by Dumluregn** [ckeditor/ckeditor4#4390] opened 2020-11-20 16:08 UTC
## Type of report

Bug/Task/Feature?

## Provide detailed reproduction steps (if any)

Demo was provided by one of users in Angular: https://github.com/ckeditor/ckeditor4-angular/issues/114#issuecomment-665137826.

### Expected result

Errors are not thrown.

### Actual result

`TypeError: Cannot read property 'unselectable' of null` error is thrown and CKEditor crashes.

## Other details

There is an error that occurs in various frameworks where you try to integrate CKEditor. It was reported in [Drupal](https://www.drupal.org/project/ckeditor/issues/2412233), [Laravel](https://github.com/ckeditor/ckeditor4/issues/3807) and [Angular](https://github.com/ckeditor/ckeditor4-angular/issues/114) and now I encountered it while testing https://github.com/ckeditor/ckeditor4-angular/issues/143.

The issue is most probably caused by [this line](https://github.com/ckeditor/ckeditor4/blob/major/core/creators/themedui.js#L458):

```js
topHtml && editor.ui.space( 'top' ).unselectable();
bottomHtml && editor.ui.space( 'bottom' ).unselectable();
```

Although the issue wasn't reproduced in the CKEditor itself so far, I think it could be worth to at least take a look at it as it makes integrating it a bit more difficult than it should be. It's hard to classify the character of this issue, so it may need to be relabeled.

**Comment by sculpt0r** [comment] 2020-12-16 13:44
Based on browser console - null is at line: https://github.com/ckeditor/ckeditor4/blob/major/core/creators/themedui.js#L458 (so, exactly as @Dumluregn said). 
`editor.ui` is an object, but the results of `space` method are `null`.

My current status:
- bug appears only for `classic` editor (so default one).
- It happened only if the initial ckeditor `element` is hidden. If it's not - then both `classic` and `inline` editor types are fine.

**Comment by Dumluregn** [comment] 2020-12-16 16:04
> It happened only if the initial ckeditor element is hidden

It makes sense and explains why it fails in the frameworks - they usually do some magic during the component initialisation which often happens before the component is actually rendered.

**Comment by sculpt0r** [comment] 2020-12-22 09:07
To be precise, in angular, the element is not hidden on not visible, but physically it's not in the document structure - that's why `space( 'top' )` returns null. In the end it ends up with `CKEDITOR.document.getById();`

**Comment by sculpt0r** [comment] 2020-12-23 08:38
Alright!

**Note**: Below angular sample is targeting `editorUrl` as localhost. Remove it to use default CDN editor.

After analyzing the test case from angular: https://stackblitz.com/edit/angular-issue-4390

I was able to create the same environment in plain CKEditor4: https://stackblitz.com/edit/js-yndfve

DOM structure during editor creation in angular (with hidden editor element inside `p-dialog`) looks like this:
- textarea element is created
- textarea element is placed as children for `<ckeditor>` element
- `<ckeditor>` is child for `p-dialog` which will be invisible
- `textarea` element has parent => `<ckeditor>`
- `<ckeditor>` has no parent => angular magic that hide content under `p-dialog`
- `textarea` element is used as reference element when calling `CKEDITOR.replace`

Potentially I even have some solution idea which targets `ui.space()` implementation.

**Comment by sculpt0r** [comment] 2020-12-23 10:56
Fast fix approach in `ui.space()` method:

```js
var id = '#' + this.spaceId( name );
var spaceElem = this.editor.container.findOne( id );

return spaceElem;
```

So we are looking for space elements inside the editor container - no in the entire document as before.

However...
I've got another problem with content iframe:

Whenever an element in `p-dialog` is shown, body element in iframe is empty and contains only some angular markers:
`<body data-new-gr-c-s-check-loaded="14.990.0" data-gr-ext-installed=""></body>`

The same happens when the editor is initialized properly, then I hide it with `p-dialog` and show it again...

Seems that `p-dialog` is a third party library for angular: https://primefaces.org/primeng/showcase/#/dialog

**Comment by Dumluregn** [comment] 2020-12-23 12:21
> So there is no editor data...

Do you mean that the editor data is erased when `p-dialog` element is shown?

Since this issue was also reproducible without `p-dialog` element (during running editor component tests in Karma), I think it is worth to try to fix it even if the originally reported issue in `ckeditor4-angular` will still occur (since it will be a problem with `p-dialog` now and not `ckeditor`), but before creating new tickets let's try to do as good as we can with this one and we can create follow-ups during the reviews.

**Comment by sculpt0r** [comment] 2020-12-23 12:35
> Do you mean that the editor data is erased when `p-dialog` element is shown?

Yes. Also, data bindings are gone.

I create two editors bound to data with https://ckeditor.com/docs/ckeditor4/latest/guide/dev_angular.html#integration-with-ngmodel

After hide & show the first one - I update data in the second one. The first editor shows no changes.

**Comment by sculpt0r** [comment] 2020-12-28 10:08
> Whenever unhide element with p-dialog, body element inside iframe is empty and contains only some angular markers:
<body data-new-gr-c-s-check-loaded="14.990.0" data-gr-ext-installed=""></body>

Iframe reloading is caused by reattaching element. Angular use it, but it's more like expected behaviour...

I tried set data manually and with onload event - but I'm crashing on 

`Uncaught TypeError: Cannot read property 'getSelection' of undefined ` while `setData` is invoked. So more references are broken inside.

**Comment by sculpt0r** [comment] 2020-12-31 09:06
After a talk with @f1ames we decide:

**Comment by sculpt0r** [comment] 2020-12-31 10:47
Summary:  
1. Original issue is caused by `editor.ui.space` method:

https://github.com/ckeditor/ckeditor4/blob/1aa21195bda3e4cfb4f19fa70d5a285b56965d70/core/ui.js#L123-L125
then
https://github.com/ckeditor/ckeditor4/blob/1aa21195bda3e4cfb4f19fa70d5a285b56965d70/core/dom/document.js#L148-L151

Since everything is detached - there is no proper `element`, so null is returned.

There is no verification whenever space was correctly found, this line gives an error:
https://github.com/ckeditor/ckeditor4/blob/5380706bb4ceb6092dadb2b7067d6c14efec6b26/core/creators/themedui.js#L458

2. Even after fix on `editor.ui.space`: there is another fix on selection to make:
https://github.com/ckeditor/ckeditor4/pull/4454/commits/74eb1dee6c70f9ab2b14a349025724026aecf1f5

3. Finally there is lot's of trouble with `iframe` reconstruction. Each time, editor is attached to DOM, browser tries to reload it. We have an empty `src` attribute, so it's impossible.

Manually recreation involves dealing with different `setTimeouts` while binding to `load` event and maintaining other events binding.

**Comment by sculpt0r** [comment] 2021-01-04 08:41
I found related issue: ckeditor/ckeditor4-react#109

**Comment by sculpt0r** [comment] 2021-05-26 12:17
Since we finished working on https://github.com/ckeditor/ckeditor4/pull/4463 and https://github.com/ckeditor/ckeditor4/pull/4601 - there is a time to verify our work with this root issue :)

**Comment by Dumluregn** [comment] 2021-05-26 14:03
Just a friendly reminder for anyone trying to test the features in integrations - easy way of using the latest CKE4 major version is nightly build: https://nightly.ckeditor.com/latest/standard/ckeditor/ckeditor.js.

**Comment by sculpt0r** [comment] 2021-05-27 10:49
I've pass `editorUrl='https://nightly.ckeditor.com/latest/standard/ckeditor/ckeditor.js'` to components in https://stackblitz.com/edit/angular-issue-4390 and `delayIfDetached=true` in config and there are no errors. Nor when the editor is hidden at the beginning or toggled. So... sounds good :tada: :+1: 

However... Inside https://github.com/ckeditor/ckeditor4/issues/4390#issuecomment-750268149
> Yes. Also, data bindings are gone.

So I'll investigate it now.

**Comment by sculpt0r** [comment] 2021-05-27 10:51
When the editor is created with delay, `ngModel` seems to have no effect...

**Comment by sculpt0r** [comment] 2021-05-27 11:43
Partially solvable with current ckeditor4 `major`, but for full fix: blocked by https://github.com/ckeditor/ckeditor4-angular/issues/190

**Comment by Dumluregn** [comment] 2021-05-27 15:08
We have a root issue reported in Angular: https://github.com/ckeditor/ckeditor4-angular/issues/114 and the CKE4 upstream is fixed. So I'd say this issue is solved, not blocked 🤔  WDYT @sculpt0r?

**Comment by sculpt0r** [comment] 2021-05-28 20:31
@Dumluregn sounds reasonable :)

I'm closing it according to: https://github.com/ckeditor/ckeditor4/pull/4463 & https://github.com/ckeditor/ckeditor4/pull/4601

**Closed by sculpt0r** 2021-05-28 20:31 UTC
Labels: size:External, status:blocked, status:confirmed, type:task

**Comment by ezintz** [comment] 2021-06-25 09:34
Is there a chance to get this released as 4.16.2? We experience this issue quite often using the official Angular module for our application, so it would be nice to get rid of it (:

**Comment by Dumluregn** [comment] 2021-07-14 09:44
Hello, unfortunately this is quite a big new feature and as such is going to be released as 4.17.0. If you want to test this feature earlier, you can use the nightly build temporarily: https://nightly.ckeditor.com/latest/standard/ckeditor/ckeditor.js (you can replace `standard` with e.g. `full`).

**Comment by sculpt0r** [comment] 2021-10-14 04:50
Hi @ezintz 
Changes are already merged to `major` branch, however, we also have a few other things there. You may try to use it, but please notice, that until the release it may be unstable. We will release `4.17.0` as soon as we will be sure, that everything is working fine with all changes. I can just ask you for the patient. We don't want to release fastly one fix and broke something else. Since CKE4 is a huge codebase - we always need to pay attention to all of our features.

Also, you can try to apply changes to your own CKE4 source code(see: https://github.com/ckeditor/ckeditor4/issues/4390#issuecomment-850655837). But it will be more convenient to wait for the official realease.

**Comment by ezintz** [comment] 2021-10-17 00:29
Hi @sculpt0r, thanks for your answer! I am glad and happy that you want to have a stable and working version released - I really appreciate your work! 🙂 We just keep having this error in our logs and sometimes the users are blocked, so we are willing to help and try to contribute 😉, if there is way. I may try the nightly builds with our application already.

Thanks again for all your work!

**Comment by Imaginativeone** [comment] 2022-11-29 16:58
I'm running into this error while using Vue 2. Which details do you need from me to fully describe the problem?
