### ISSUE TITLE
Set max-size limit while uploading image 

### ISSUE THREAD

**Issue by codeforsure** [ckeditor/ckeditor4#4016] opened 2020-05-04 08:06 UTC
## Type of report

Bug

## Provide detailed reproduction steps (if any)
I was trying to restrict max-upload size of the image using this code

```
const onFileUploadRequest = evt => {
  let fileLoader = evt.data.fileLoader;
  if (fileLoader.file.size > max_size) {
     fileLoader.abort ();
    evt.cancel ();
  } else {
    //DO required
    // To prevent the default behavior.
    evt.stop ();
  }
};


```
## Expected result
Should not show any message and restrict files above maximum size

## Actual result
showing a alert message with undefined text after calling fileLoader.abort() function

**Comment by jacekbogdanski** [comment] 2020-05-08 07:00
Could you provide a demo sample with the issue? It's hard to reproduce the issue without more information about implementation and this specific use case. It would be great if you could use some online tool like the one mentioned in the issue template: 

* CodePen: https://codepen.io/Comandeer/pen/ExaMgpz?editors=1010
* JSFiddle: https://jsfiddle.net/Comandeer/d6ey8a2w
* JSBin: https://jsbin.com/keqekef/1/edit?html,js,output
* StackBlitz: https://stackblitz.com/edit/js-vcqfw3

**Comment by Dumluregn** [comment] 2020-05-22 07:21
Hi, it's been a while since we last heard from you. We're closing this issue for now. Still, feel free provide us requested feedback, so that we can reopen this issue.

**Closed by Dumluregn** 2020-05-22 07:21 UTC
Labels: status:pending, type:bug
