### ISSUE TITLE
Paste image file from clipboard as base64 string in Firefox 89 not working

### ISSUE THREAD

**Issue by apothekarius** [ckeditor/ckeditor4#4755] opened 2021-06-11 08:08 UTC
## Type of report

Bug

## Provide detailed reproduction steps (if any)

Pasting an image file from clipboard via Ctrl+V into an editor as a base64 string is not working. There are no extra steps required; just open the fiddle or try it on the sample pages provided in the dev-folder of the clipboard plugin. 
The browser used was Firefox 89, OS is Win10.

* JSFiddle: https://jsfiddle.net/Comandeer/d6ey8a2w

This pertains to both 4.16.1 and the current major branch (and affects different browser as well when changes from #4722 are included).

### Expected result

img element with image file converted to base64 string

### Actual result

paste event is fired, but image not inserted 

## Other details
 I haven't tested the issue with different versions of FF, but it does make sense that the paste doesn't work. CKEDITOR.plugins.clipboard.dataTransfer 's cache doesn't include the types array. The responsible paste event handler checks explicitly for both the amount of files in the dataTransfer instance (first cache, then native clipboard data) AND checks the types for the element 'Files' (only the native clipboard data). At this point in time though, due to asynchronicity, native clipboard data has already expired and the check returns false, resulting in no image pasted.

**Comment by apothekarius** [comment] 2021-06-11 08:17
Including the types in the cache is a very small and straightforward fix. Our QA found it and I already had to fix it for the application I work on. 
I'll create a pull request later or over the weekend.

**Comment by Comandeer** [comment] 2021-06-11 08:50
It's a duplicate of #3757. Additionally the cache for pasted types was implemented in #4604. The fix will be released in 4.17.0.

**Closed by Comandeer** 2021-06-11 08:50 UTC
Labels: type:bug
