### ISSUE TITLE
[Accessibility] - Table Properties Labels: No asterisk marks are provided on required fields (row, columns) in "Table properties" dialog.

### ISSUE THREAD

**Issue by deeptijoshimsft** [ckeditor/ckeditor4#4864] opened 2021-08-31 22:12 UTC
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. Launch CKEditor 4 demo URL https://ckeditor.com/ckeditor-4/demo/
2. Click on Table to open table properties dialog.
3. Notice that there are no asterisk marks on required fields (Rows , Columns).

### Expected result

There should be asterisk mark on the mandatory fields (Rows and Columns).

### Actual result

No asterisk marks are provided on required fields (Row and Columns). 

![image](https://user-images.githubusercontent.com/89545778/131582188-1893f6e7-41b2-48f7-b88d-658c26b6168a.png)

## Other details

* Browser: Chorme, Chromium based EDGE
* OS: Windows 10
* CKEditor version4
* Installed CKEditor plugins: Table

**Comment by jacekbogdanski** [comment] 2021-09-01 09:46
Duplicate of https://github.com/ckeditor/ckeditor4/issues/3433

**Closed by jacekbogdanski** 2021-09-01 09:46 UTC
Labels: type:bug
