### ISSUE TITLE
Enhanced image plugin drag and drop broken in 4.14.0

### ISSUE THREAD

**Issue by mikemunger** [ckeditor/ckeditor4#3953] opened 2020-03-25 21:45 UTC
I'm not sure about other versions, but in ckeditor 4.14.0 drag and drop to reposition an image using enhanced image plugin is broken, including on the demo page here:

https://ckeditor.com/docs/ckeditor4/latest/examples/image2.html

I checked in the latest firefox and chrome on ubuntu 18.04 linux.

Steps to reproduce:

- Go to demo of this plugin https://ckeditor.com/docs/ckeditor4/latest/examples/image2.html
- Drag the top left corner of the image to reposition and try to move the image down a couple positions and release the drag

This will produce error output in the js console, and will not reposition the image as expected.

Error output in chrome after drag and drop of enhance image in editor:
ckeditor.js:716 Uncaught TypeError: Cannot read property 'endContainer' of undefined
    at Object.isDropRangeAffectedByDragRange (ckeditor.js:716)
    at Object.internalDrop (ckeditor.js:717)
    at ckeditor.js:706

**Comment by f1ames** [comment] 2020-03-26 07:13
Thanks for reporting @mikemunger!

You can always check with the previous docs version, e.g. https://ckeditor.com/docs/ckeditor4/4.13.1/examples/image2.html. I already did and it works there correctly which means this is a recent regression in `4.14` version :disappointed:

**Comment by Dumluregn** [comment] 2020-03-26 13:09
May be connected with #3875.

**Comment by Wizard13** [comment] 2020-03-26 22:27
It could be connected to #3926 because if you copy the image and paste it, the new one can be dragged, the first one can't be dragged.

**Comment by NogaMan** [comment] 2020-04-03 10:36
It is connected to https://github.com/ckeditor/ckeditor4/issues/3926.
Check out my comment for fix https://github.com/ckeditor/ckeditor4/issues/3926#issuecomment-608361796

**Comment by jacekbogdanski** [comment] 2020-05-08 11:06
The issue has been introduced in https://github.com/ckeditor/ckeditor4/commit/613f7a8ace83f82852398a0a61bae1b24c147f79

**Comment by jacekbogdanski** [comment] 2020-05-11 07:29
Duplicate of #3926

**Closed by jacekbogdanski** 2020-05-11 07:29 UTC
Labels: plugin:clipboard, regression, status:confirmed, type:bug, workload:medium
