### ISSUE TITLE
[Firefox]Can't move cursor after Ctrl+F of Firefox

### ISSUE THREAD

**Issue by s-nidaira** [ckeditor/ckeditor4#3726] opened 2019-12-11 01:55 UTC
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. https://ckeditor.com/ckeditor-4/demo/
2. I can move up and down with arrow keys in CKEditor and use Tab key, too.
3. Show search area  with Ctrl + F of Firefox.
4. Set Focus to CKEditor and press arrow keys. I can't move cursor.

### Expected result

It is possible to use all keys even if search area of Firefox is opened.

### Actual result

It is not able to move cursor.

## Other details

* Browser: Firefox 71.0 64bit
* OS: Windows7, Windows10
* CKEditor version: CKEditor 4

**Comment by jacekbogdanski** [comment] 2019-12-11 04:00
I can also reproduce the issue after upgrade from FF 70 to 71. The issue is reproducible with any contenteditable element, so I already reported an upstream bug here: https://bugzilla.mozilla.org/show_bug.cgi?id=1603020

As it's an upstream I'm closing the issue, please follow https://bugzilla.mozilla.org/show_bug.cgi?id=1603020 for more updates about the issue state.

**Closed by jacekbogdanski** 2019-12-11 04:00 UTC
Labels: browser:firefox, resolution:upstream, type:bug
