### ISSUE TITLE
Paste image function worked in IE11, but failed in Chrome (77.0.3865.120).

### ISSUE THREAD

**Issue by Lance595** [ckeditor/ckeditor4#3861] opened 2020-02-16 10:36 UTC
## Type of report
Question

## Provide detailed reproduction steps (if any)
I would like to have "paste image" function into ckeditor from windows clipboard so I download "ckeditor4 + easy image" and used it in my program for test. However I find "paste image" works in IE11 but Chrome(77.0.3865.120) not.

In Chrome:
I pasted image and it showed image in ckeditor at this moment then I used ckeditor to view img souce. The content of img src tag was the data that browser currently has in memory, it didn't refer to data the existed on the server. 
I also checked that file uploaded to my server indeed, the file name was image(x).png. After I saved my post into the database and refreshed page, image didn't come up.
![image](https://user-images.githubusercontent.com/61107608/74603041-14d08280-50ea-11ea-9981-3fbe60481f59.png)

In IE11
I did what I did in Chrome and the image could show after saving data to database in IE.  The content of img src tag was different from Chorme, image was saved as data into database, not refer to the file uploaded on the server. (I deleted the uploaded file in server, the image still showed.)
![image](https://user-images.githubusercontent.com/61107608/74603750-c8894080-50f1-11ea-8a7d-dacc5e1fcd31.png)

### Expected result

Chrome could show image as well

### Actual result

Chrome is unable to show image

## Other details

* Browser: IE11, Chrome (77.0.3865.120)
* OS: Win 10
* CKEditor version: 4.13.1
* Installed CKEditor plugins: easy image

**Comment by Comandeer** [comment] 2020-02-17 17:25
Can you provide more details, e.g. sample reproduction? Have you provided correct upload URL for Easy Image plugin via [`cloudServices_uploadUrl` config variable](https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_config.html#cfg-cloudServices_uploadUrl)?

**Comment by jacekbogdanski** [comment] 2020-03-04 08:00
Hi, It's been a while since we last heard from you. We're closing this issue for now. Still, feel free provide us requested feedback, so that we can reopen this issue.

**Closed by jacekbogdanski** 2020-03-04 08:00 UTC
Labels: status:pending, type:bug
