### ISSUE TITLE
Failing test - tests/plugins/imagebase/features/link

### ISSUE THREAD

**Issue by Dumluregn** [ckeditor/ckeditor4#4100] opened 2020-06-09 17:25 UTC
## Type of report

Failing test

## Provide detailed reproduction steps (if any)

`test edit link attribute in existing image widget (classic)`
`Expected: foo (string)`
`Actual:  (string)`

**Comment by f1ames** [comment] 2020-06-10 06:35
@Dumluregn looks like a duplicate of #3147?

**Closed** 2020-06-10 08:19 UTC
Labels: browser:ie11, status:confirmed, type:failingtest
