### ISSUE TITLE
Property data-widget crashes CKEditor

### ISSUE THREAD

**Issue by gaellafond** [ckeditor/ckeditor4#4295] opened 2020-09-22 07:41 UTC
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. Edit a document in source mode
2. Add the following to the document: `<a href="http://aaa.com" data-widget="image">AAA</a>`
3. Save
4. Edit the document again

Some JavaScript errors will be displayed in the browser's JS console and all CKEditor buttons will be greyed out, making the editor pretty mush unusable.

### Expected result

No JS error, CKEditor buttons usable

### Actual result

JS error in browser's JS console, all CKEditor buttons disabled

```
ckeditor.js?v=4.14.1:957 Uncaught TypeError: Cannot read property 'getAttribute' of null
    at h.init (ckeditor.js?v=4.14.1:957)
    at h.widgetDefinition.init (plugin.js?t=qh1qs8:182)
    at new h (ckeditor.js?v=4.14.1:884)
    at b.initOn (ckeditor.js?v=4.14.1:933)
    at b.initOnAll (ckeditor.js?v=4.14.1:933)
    at b.<anonymous> (ckeditor.js?v=4.14.1:907)
    at b.c (ckeditor.js?v=4.14.1:10)
    at b.<anonymous> (ckeditor.js?v=4.14.1:11)
    at b.CKEDITOR.editor.CKEDITOR.editor.fire (ckeditor.js?v=4.14.1:13)
    at ckeditor.js?v=4.14.1:1179
```

## Other details

* Browser: Chrome
* OS: Ubuntu
* CKEditor version: 4
* Installed CKEditor plugins: None (fresh install)

NOTE: The issue can be reproduced without going into Source mode. That's how it happened on my install in the first place. It was something like inserting an image in the middle of the text of a link (HTML tag `A`) then pressing the `Enter` key to break the link into 2 lines. But I haven't figure out how to re-produce it without using the Source mode.

**Comment by Dumluregn** [comment] 2020-09-22 11:19
Hello! I'm unable to reproduce your issue. First of all, the editor doesn't have a `Save` feature on its own. That means that the issue is caused by the integration with CKEditor you are using, not by the editor itself. I've created [a demo](https://codepen.io/dumluregn/pen/NWNePWK?editors=1010) where you can try to check that the problem you described can't be reproduced. The first editor has the default [ACF](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_advanced_content_filter.html) settings and after toggling source mode the `data-widget` attribute is removed. The second one has ACF turned off, but after toggling mode it works fine.

Therefore I'm closing this issue. If you manage to create a demo where the problem can be reproducible with a CKEditor 4 without any integration layer, feel free to come back and provide us more feedback.

**Closed by Dumluregn** 2020-09-22 11:19 UTC
Labels: type:bug

**Comment by gaellafond** [comment] 2020-09-22 23:30
Thank you Dumluregn. I'm using CKEditor integrated in Drupal 9. I had a look at the code (Drupal and CKEditor) and it seems like the only place I could find reference to `data-widget` was in CKEditor so I assume the bug was coming from it.

I didn't know how to test it in CKEditor alone. Apparently because it can't be tested :)

Thanks for your time. I will add a reference to this issue in my Drupal issue.
