### ISSUE TITLE
Can't insert widget if nested editable is in path

### ISSUE THREAD

**Issue by Comandeer** [ckeditor/ckeditor4#3008] opened 2019-04-01 13:11 UTC
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. Open https://jsfiddle.net/Comandeer/zf5eu26g/
2. Start selecting from right text under the widget and end on bottom of the widget.
3. Try to insert new image widget into the current selection.

### Expected result

Image can be inserted.

### Actual result

Image button is disabled. In fact most of editor's features is disabled, as selection's beginning is anchored inside nested editable (caption in this case).

## Other details

* Browser: Safari
* CKEditor version: 4.5.0+
* Installed CKEditor plugins: widget, image2

**Comment by f1ames** [comment] 2020-01-10 14:22
Same happens for Firefox.

**Comment by jacekbogdanski** [comment] 2020-02-06 15:20
Duplicate of https://github.com/ckeditor/ckeditor4/issues/2517

**Closed by jacekbogdanski** 2020-02-06 15:20 UTC
Labels: browser:firefox, browser:safari, plugin:widget, status:confirmed, type:bug
