### ISSUE TITLE
IE11: Unspecified error on clicking on a widget when editor is in read-only mode

### ISSUE THREAD

**Issue by 7c00-oracle** [ckeditor/ckeditor4#3738] opened 2019-12-17 09:37 UTC
## Steps to reproduce:

1. Create a widget as shown in the [widget tutorial](https://ckeditor.com/docs/ckeditor4/latest/guide/widget_sdk_tutorial_1.html)
2. Open in IE11.
3. Click on the widget to add the template to the content.
4. Set the editor to read only mode.
5. Click on the widget wrapper (yellow/blue rectangle).

**Observed:** SCRIPT16389: Unspecified error. ckeditor.js (488,115)

**Expected:** No error should happen

**CKEDITOR version:** 4.9.2 - 4.13.0

**Browser:** IE 11.864

---

## IE11 throws `SCRIPT16389: Unspecified error` on native Selection.addRange() when the start and end containers of the range being added has `display: none`

For example

```
<html>
  <head>
    <script src="https://code.jquery.com/jquery-2.1.4.js"></script>
    <meta charset="utf-8">
    <title>IE11 Unspecified Error</title>
    <style>
      #d2 {
        display:none;
      }
    </style>
  </head>
  <body>
    <div id="d1">div1</div>
    <div id="d2">div2</div>
    <div id="d3">div3</div>
    <a onclick="doSel()" href="javascript:void(0)">click me:)</a>
    <script>
    function doSel(){
    var element = $("#d2").contents()[0];
      var myRange = createRange(element,1,element,2);
      console.log(myRange);
      document.getSelection().removeAllRanges();
      document.getSelection().addRange(myRange);
    }
    function createRange(startContainer, startOffset, endContainer, endOffset){
        var rangeObj = document.createRange();
        rangeObj.setStart(startContainer, startOffset);
        rangeObj.setEnd(endContainer, endOffset);
        return rangeObj;
    }
    </script>
  </body>
</html>
```
Clicking on the link results in error since `div#d2` has `display: none`

---

## Fake selections in CKEDITOR 4.6 [#13829](http://dev.ckeditor.com/ticket/13829)
[This commit](https://github.com/ckeditor/ckeditor4/commit/839427e49ac8fa8563ad42d2fc02064f50fa124b) added the check for IE and then sets the display of fake selection div to none. Changing the display style so that element is rendered but not visible seemed to solve the problem for IE11

![image](https://user-images.githubusercontent.com/55756984/70983459-c5b4a400-20de-11ea-851f-7c8de784b214.png)

**Comment by jacekbogdanski** [comment] 2019-12-17 09:46
Duplicate of #1575

**Closed by jacekbogdanski** 2019-12-17 09:46 UTC
Labels: type:bug
