### ISSUE TITLE
[Accessibility] - All Radio buttons in one group are accessible through tab key which is incorrect.

### ISSUE THREAD

**Issue by sryarama** [ckeditor/ckeditor4#4484] opened 2021-01-13 15:25 UTC
## Type of report

Bug

## Provide detailed reproduction steps (if any)
As w3 standards when a radio group receives focus the first radio button in the group receives focus and other items in the group canonly be accessible using left/right arrows. In CKEDITOR image dialog all radio group items are accessible through TAB which causes confusion to keyboard users.

W3 radio Button Documentation available [here](https://www.w3.org/TR/2017/WD-wai-aria-practices-1.1-20170628/#radiobutton).
Example implementation on W3 is available [here](https://www.w3.org/TR/2017/WD-wai-aria-practices-1.1-20170628/examples/radio/radio-1/radio-1.html).

![image](https://user-images.githubusercontent.com/66038900/104470531-ab155e80-556e-11eb-94d1-8bae74541f69.png)

## Other details

* Browser: Google Chrome Version 87.0.4280.66 (Official Build) (64-bit)
* OS: Windows 10
* CKEditor version: 4
* Installed CKEditor plugins: image

**Comment by Comandeer** [comment] 2021-01-19 15:23
Duplicate of #439.

**Closed by Comandeer** 2021-01-19 15:23 UTC
Labels: type:bug
