### ISSUE TITLE
Failing PfW tests on mobile Safari

### ISSUE THREAD

**Issue by Comandeer** [ckeditor/ckeditor4#5113] opened 2022-03-08 10:39 UTC
## Type of report

Failing test

## Provide detailed reproduction steps (if any)

1. Open http://localhost:1030/#tests/is:unit,name:tickets1,name:tickets2
1. Run tests.

### Expected result

All tests in `tests/plugins/pastefromword/generated/tickets1` and `tests/plugins/pastefromword/generated/tickets2` suites should pass.

### Actual result

Several tests fail due to autolinking of phone numbers in Safari mobile.

## Other details

* Browser: Safari Mobile
* OS: iOS 15
* CKEditor version: 4.17.3
* Installed CKEditor plugins: pastefromword, link

Probably we would want to disable autolinking → https://stackoverflow.com/a/227238

**Comment by sculpt0r** [comment] 2022-03-31 06:38
@Comandeer - looks like those tests are already ignored on `bender.tools.env.mobile` and at least on iOS simulator on macOS - they are - indeed. Could you take a look again and share some screens?

**Comment by Comandeer** [comment] 2022-04-03 19:50
That's weird :thinking: My iPad seems to have a desktop UA: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.4 Safari/605.1.15`. Not sure why, I didn't change anything in its settings.

**Comment by Comandeer** [comment] 2022-04-03 20:00
Ok, it seems that [iPad uses desktop versions of websites by default](User Agent in Safari on iPadOS - https://developer.apple.com/forums/thread/119186?answerId=373517022#373517022)… So it basically means that we can't confidently detect mobile iOS devices :/

**Comment by jacekbogdanski** [comment] 2022-04-28 12:39
@Comandeer if I remember correctly, this issue actually doesn't need our attention as it's working by design on iOS?

**Comment by Comandeer** [comment] 2022-04-28 12:49
Yes and no…

By default iOS browser announce itself as a desktop one. So if we're good with changing browser's settings to accommodate that, we can safely close the issue. Otherwise, we would need to come up with a better browser sniffing method.

**Comment by jacekbogdanski** [comment] 2022-06-07 10:13
Since this issue can be accommodated by correcting iPad settings, let's close it for now and add an appropriate comment to the test files.

**Closed** 2022-06-10 12:30 UTC
Labels: status:confirmed, browser:ios, plugin:pastefromword, plugin:link, type:failingtest, size:XS
