### ISSUE TITLE
script error: Cannot read property 'clientTop' of undefined

### ISSUE THREAD

**Issue by weichuan-dong** [ckeditor/ckeditor4#3512] opened 2019-09-27 17:30 UTC
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. "autogrow" plugin is enabled in our code.
2. when the ckeditor is just rendered and the user types in ckeditor, the following error is seen in the console:
Cannot read property 'clientTop' of undefined
@TypeError: Cannot read property 'clientTop' of undefined
    at CKEDITOR.dom.element.getDocumentPosition (https://day103-191100-sql-201h.dq.lan/AgentWeb/api/agentbrowserui/v.31909250003/libs/ckeditor/ckeditor.js:120:108)
    at contentHeight (https://day103-191100-sql-201h.dq.lan/AgentWeb/api/agentbrowserui/v.31909250003/libs/ckeditor/plugins/autogrow/plugin.js?t=I3I8:143:37)
    at resizeEditor (https://day103-191100-sql-201h.dq.lan/AgentWeb/api/agentbrowserui/v.31909250003/libs/ckeditor/plugins/autogrow/plugin.js?t=I3I8:162:17)
    at https://day103-191100-sql-201h.dq.lan/AgentWeb/api/agentbrowserui/v.31909250003/libs/ckeditor/plugins/autogrow/plugin.js?t=I3I8:74:7 TypeError: Cannot read property 'clientTop' of undefined
    at CKEDITOR.dom.element.getDocumentPosition (ckeditor.js:120)
    at contentHeight (plugin.js?t=I3I8:143)
    at resizeEditor (plugin.js?t=I3I8:162)
    at plugin.js?t=I3I8:74

### Expected result

*What is the expected result of the above steps?*

### Actual result

*What is the actual result of the above steps?*

## Other details
It is not reproducible 100% but intermittent.
* Browser: Firefox, chrome …
* OS: Window 10, Mac…
* CKEditor version: 4.9.2…
* Installed CKEditor plugins: autogrow

**Comment by jacekbogdanski** [comment] 2019-10-01 07:46
Hello,

I'm not able to reproduce the issue with Chrome nor Firefox. Could you provide code sample and strict reproduction steps, so we can verify what's going on?

Are you able to reproduce the issue with the latest CKEditor4 4.13.0?

**Comment by Dumluregn** [comment] 2019-10-17 09:17
Hi, It's been a while since we last heard from you. We're closing this issue for now. Still, feel free provide us requested feedback, so that we can reopen this issue.

**Closed by Dumluregn** 2019-10-17 09:17 UTC
Labels: plugin:autogrow, status:pending, type:bug

**Comment by darmawan01** [comment] 2019-11-08 05:27
same issues here, it's happen when try select all text and set align to center/right. then cursor is move automatically to start of text. and i can't set focus back to end of text

**Comment by darmawan01** [comment] 2019-11-11 06:59
hy @weichuan-dong did find what's happen ?
