### ISSUE TITLE
Errors in samples/toolbar configurator

### ISSUE THREAD

**Issue by npelov** [ckeditor/ckeditor4#4140] opened 2020-07-05 15:42 UTC
This is a fresh install of CKEditor 4.14.1 (version taken from the top of CHANGES.md). I do not remember if I added/removed any plugins.  The toolbar configurator does not work. I see following errors (ignore the first error  - it's from a chrome plugin):

The error `Uncaught TypeError: Cannot read property 'split' of undefined` showed at page load (clicked on toolbar editor). 

The error `Uncaught TypeError: Cannot read property 'refresh' of null` showed when I clicked "advanced"

![image](https://user-images.githubusercontent.com/16647317/86536228-98024180-beee-11ea-82ad-cd809db15375.png)

**Comment by Comandeer** [comment] 2020-07-05 21:06
I can't reproduce the issue. Can you provide some additional info about version of your browser, your operating system and configuration of your CKEditor 4?

**Comment by jacekbogdanski** [comment] 2020-07-20 07:10
Hi, It's been a while since we last heard from you. We're closing this issue for now. Still, feel free provide us requested feedback, so that we can reopen this issue.

**Closed by jacekbogdanski** 2020-07-20 07:10 UTC
Labels: status:pending, type:bug
