### ISSUE TITLE
HTML Comments converted to cke_protected in inline mode

### ISSUE THREAD

**Issue by epchristi** [ckeditor/ckeditor4#3903] opened 2020-03-01 05:20 UTC
## Are you reporting a feature request or a bug?
bug report

When html content entered from "source" mode has html comments (), content between the comments turns into cke_protected and gets encoded.

## Provide detailed reproduction steps (if any)

1. …Insert the following html
```
<div bb="true" style="text-align:center; width:100%"><!-- button_builder_start --><!--[if mso]>
	<v:rect xmlns:v="urn:schemas-microsoft-com:vml" xmlns:w="urn:schemas-microsoft-com:office:word" href="https://" style="height:53px;v-text-anchor:middle;width:160px;"  stroke="f" fillcolor="#49a9ce">
	<w:anchorlock></w:anchorlock>
	<center>
	<![endif]--><a href="https://" style="background-color:#49a9ce;color:#ffffff;display:inline-block;font-family:comic sans ms, sans-serif;font-size:16px;font-weight:bold;line-height:53px;text-align:center;text-decoration:none;width:160px;-webkit-text-size-adjust:none;">Just do it!</a> <!--[if mso]>
	</center>
	</v:rect>
	<![endif]--> <!-- button_builder_end --></div>
```

2. … Then use CKEDITOR.dialog.getCurrent().getParentEditor().getData()
3. … Then verify the content looks like this:
```
<div bb="true" style="text-align:center; width:10
[build-config.js.txt](https://github.com/ckeditor/ckeditor4/files/4271381/build-config.js.txt)

0%">
<!--{cke_protected}{C}%3C!%2D%2D%20button_builder_start%20%2D%2D%3E--><!--{cke_protected}{C}%3C!%2D%2D%5Bif%20mso%5D%3E%0A%09%3Cv%3Arect%20xmlns%3Av%3D%22urn%3Aschemas-microsoft-com%3Avml%22%20xmlns%3Aw%3D%22urn%3Aschemas-microsoft-com%3Aoffice%3Aword%22%20href%3D%22https%3A%2F%2F%22%20style%3D%22height%3A53px%3Bv-text-anchor%3Amiddle%3Bwidth%3A160px%3B%22%20%20stroke%3D%22f%22%20fillcolor%3D%22%2349a9ce%22%3E%0A%09%3Cw%3Aanchorlock%3E%3C%2Fw%3Aanchorlock%3E%0A%09%3Ccenter%3E%0A%09%3C!%5Bendif%5D%2D%2D%3E--><a href="https://" style="background-color:#49a9ce;color:#ffffff;display:inline-block; font-family: 'trebuchet ms',sans-serif;font-size:16px;font-weight:bold;line-height:53px;text-align:center;text-decoration:none;width:160px;-webkit-text-size-adjust:none;">Just do it!</a> <!--{cke_protected}{C}%3C!%2D%2D%5Bif%20mso%5D%3E%0A%09%3C%2Fcenter%3E%0A%09%3C%2Fv%3Arect%3E%0A%09%3C!%5Bendif%5D%2D%2D%3E--> <!--{cke_protected}{C}%3C!%2D%2D%20button_builder_end%20%2D%2D%3E--></div>
```

### Expected result
html content is not cke_protected. (and when done in "non-inline mode" it is not cke_protected.) This only happens in inline mode.

### Actual result
cke_protected content between the comments.

## Other details

* Browser: … chrome
* OS: … windows and linux
* CKEditor version: … 4.13.1
* Installed CKEditor plugins: …

**Comment by epchristi** [comment] 2020-03-01 05:33
One updated piece of information. If I hover over the inline editor instance and let it sit there for about 5 seconds (or click in it), then the same exact content won't always be cke_protected, it will be the correct html. I can not make it deterministic yet, but will keep trying to triage.

**Comment by jacekbogdanski** [comment] 2020-03-04 08:19
Could you provide a minimal demo with the issue using some online tool like https://codepen.io? I'm not able to reproduce the issue, but I'm not sure if I fully understand your problem. Could you correct these reproduction steps if something wrong?

1. Open **inline** editor demo with a standard preset and `sourcedialog` plugin.
2. Open console.
3. Open source dialog and insert provided HTML:
```
<div bb="true" style="text-align:center; width:100%"><!-- button_builder_start --><!--[if mso]>
	<v:rect xmlns:v="urn:schemas-microsoft-com:vml" xmlns:w="urn:schemas-microsoft-com:office:word" href="https://" style="height:53px;v-text-anchor:middle;width:160px;"  stroke="f" fillcolor="#49a9ce">
	<w:anchorlock></w:anchorlock>
	<center>
	<![endif]--><a href="https://" style="background-color:#49a9ce;color:#ffffff;display:inline-block;font-family:comic sans ms, sans-serif;font-size:16px;font-weight:bold;line-height:53px;text-align:center;text-decoration:none;width:160px;-webkit-text-size-adjust:none;">Just do it!</a> <!--[if mso]>
	</center>
	</v:rect>
	<![endif]--> <!-- button_builder_end --></div>
```
4. Retrieve HTML by getting editor data by `editor.getData()` API.
5. Switch back to editing mode and again verify HTML using `editor.getData()` API.

Not sure if the issue occurs in 4 or 5, but for both works fine for me. I assumed that you are not switching to editing mode as you are using source dialog to retrieve editor instance.

**Comment by Dumluregn** [comment] 2020-03-18 18:53
Hi, It's been a while since we last heard from you. We're closing this issue for now. Still, feel free provide us requested feedback, so that we can reopen this issue.

**Closed by Dumluregn** 2020-03-18 18:53 UTC
Labels: status:pending

**Comment by ZuffoX** [comment] 2020-04-20 09:29
Hi, I also have this 'bug' and it is already confirmed as a bug in https://github.com/ckeditor/ckeditor4/issues/729 but never fixed.
I get it when i put this in source `<!--[if mso]><div>hello</div><![endif]--></p>`

So is it possible to get this fixed?
