### ISSUE TITLE
Uncaught TypeError: CKEDITOR.tools.throttle is not a function     at new TextWatcher (plugin.js?t=FB9E:157)

### ISSUE THREAD

**Issue by Tectract** [ckeditor/ckeditor4#3658] opened 2019-11-17 08:54 UTC
## Type of report

Bug

CKEDITOR.tools.throttle is not a function, error kicking up from textwatcher / autocomplete / emoji plugins. I'm trying to get the emoji plugin working, which relies on autocomplete, which relies on textwatcher...

## Provide detailed reproduction steps (if any)

using textwatcher plugin, seems that ckeditor.tools.throttle is throwing a halting error

### Expected result

no error

### Actual result

error

## Other details

* Browser: …
* OS: …
* CKEditor version: 4.11-4.13
* Installed CKEditor plugins: html5video,widget,widgetselection,clipboard,lineutils,dialog,dialogui,notification,toolbar,button,textmatch,textwatcher,xml,panel,autocomplete,ajax,panelbutton,floatpanel,emoji

**Comment by msamsel** [comment] 2019-11-18 08:39
Hi,

I cannot reproduce the error. Please take a look at samples:
http://cdn.ckeditor.com/4.13.0/full-all/samples/old/emoji/emoji.html
You can type in browser's console `CKEDITOR.tools.throttle` and you'll see the function is available.

Please provide extender reproduction steps or some demo website.

**Comment by Tectract** [comment] 2019-11-18 17:00
oops this ticket was supposed to be in the ckeditor-rails repo...

**Comment by msamsel** [comment] 2019-11-19 08:12
@Tectract no problem. I've closed it in such case :)

**Closed** 2019-11-19 08:12 UTC
Labels: resolution:invalid, type:bug

**Comment by kruzalmighty** [comment] 2020-05-18 05:51
Change ckeditor.js version
<script src="http://cdn.ckeditor.com/4.13.0/full-all/ckeditor.js"></script>
