### ISSUE TITLE
Table Resize plugin does not work when editor placed in absolutely positioned container in divarea

### ISSUE THREAD

**Issue by jbalinski** [ckeditor/ckeditor4#909] opened 2017-09-13 18:14 UTC
## Are you reporting a feature request or a bug?
Bug

## Provide detailed reproduction steps (if any)

1. Using divarea and table resize plugin
2. Place editor in a div that is absolutely positioned with a z-index greater than 10 (we are using 900).
3. Insert a table.   Attempt to resize one of the columns.

### Expected result
You should be able to resize columns.

### Actual result
You are not able to resize columns.

## Other details

* Browser: Chrome, Edge, IE 11
* OS: Windows 10
* CKEditor version: 4.7.3
* Installed CKEditor plugins:
basicstyles,button,clipboard,colorbutton,colordialog,contextmenu,dialogadvtab,dialogui,divarea,enterkey,entities,fakeobjects,filetools,floatpanel,font,htmlwriter,image2,indent,indentblock,indentlist,link,list,listblock,liststyle,menu,menubutton,notification,notificationaggregator,panel,panelbutton,pastetext,popup,removeformat,resize,richcombo,scayt,showborders,tab,table,tableresize,tabletools,toolbar,undo,uploadimage,widget

**Comment by msamsel** [comment] 2017-09-18 06:42
I'm not able to reproduce this problem: you can check my test example: https://codepen.io/msamsel/pen/ZXbPbJ?
You can also prepare your example which will show this problem, maybe I do something wrong in my example.

**Comment by jbalinski** [comment] 2017-09-28 15:35
The problem occurs with the divarea plugin.  The example you have is using an iframe for the editor.

**Comment by msamsel** [comment] 2017-09-28 15:56
I was able to repeat it in divarea. Thank you for the clarification.

**Comment by f1ames** [comment] 2020-06-05 16:11
Fixed in e3be5c1.

**Closed by f1ames** 2020-06-05 16:11 UTC
Labels: plugin:tableresize, status:confirmed, type:bug, workload:low
