### ISSUE TITLE
When user copy-paste image CKEditor get blob-url

### ISSUE THREAD

**Issue by Dissarion** [ckeditor/ckeditor4#3579] opened 2019-10-16 09:07 UTC
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. Take iPad (12.3.1)
2. Choose photo (local storage from your iPad) and copy him.
3. Paste photo in CKEditor and save.
4. Watch on saved data. The URL will be in "blob: ..." format.
5. Open saved data from another device (where don't have image).

### Expected result

Image is not displayed on both devices.

### Actual result

Image displaying on device when have image in local storage/deleted images/clipboard.

## Other details

* Browser: Chrome 77.0.3865.120
* OS: MacOS
* CKEditor version: 4
* Installed CKEditor plugins: 
a11yhelp, 
cloudservices,
flash,
magicline,
specialchar,
about,
colordialog,
forms,
mathjax,
table,
ajax,
copyformatting,
icons.png,
media,
tableselectionapi,
dialog,
icons_hidpi,
png	pagebreak,
tabletoolsautoembed,
div,
iframe,
pastefromword,
templatesautogrow,
easyimage,
image,
preview,
textmatchautolink,
embed,
image2,
resize,
widgetballoonpanel,
embedbase,
imagebase,
scayt,
wsc,
balloontoolbar,
embedsemantic,
link,
showblocks,
xml,
clipboard,
find,
liststyle,
smiley

**Comment by Dumluregn** [comment] 2019-10-18 14:21
Hello, I tried to reproduce your issue using our [Easy Image Sample](https://ckeditor.com/docs/ckeditor4/latest/examples/easyimage.html), which has a similar configuration, but your description is a little too superficial and I can't get the result you mentioned. Please give us more details (like: do you copy image from gallery and then paste it using context menu or using paste button or do you upload file using editor's uploader etc., then how do you save data - you have a form for that? Save data on server?) or maybe create a demo on [CodePen](https://codepen.io/).

**Comment by Comandeer** [comment] 2019-11-04 13:10
Hi, It's been a while since we last heard from you. We're closing this issue for now. Still, feel free provide us requested feedback, so that we can reopen this issue.

**Closed by Comandeer** 2019-11-04 13:10 UTC
Labels: status:pending, type:bug

**Comment by davidfrancis597** [comment] 2024-11-21 10:52
<html>
<body>

When a user pastes an image into CKEditor, it generates a Blob URL to temporarily represent the image in the editor.<a href="https://clippingpathphotoediting.com/services/">photoshop clipping path service company</a> This Blob URL points to the image stored in the browser's memory, allowing for immediate preview. To save the image permanently, the Blob data must be uploaded to a server or converted into a storable format.
--


<br class="Apple-interchange-newline">
</body>
</html>
