### ISSUE TITLE
Accessibility: Link button dialog - tabs are not accessibility complaint

### ISSUE THREAD

**Issue by Sukesh-Gundoji** [ckeditor/ckeditor4#3812] opened 2020-01-22 17:13 UTC
Step 1: Navigate to the 'Link' button which is present in the editor field press enter on the 'Link' button. 
Step 2: “Link” Dialog will be displayed and now navigate to the tab items present on the dialog.
Step 3: Verify whether the Screen readers(NVDA/Narrator) are narrating the State i.e. selected for the tab items present on the “Link” dialog.

Actual result:
Screen readers(NVDA/Narrator) are not narrating the State i.e. selected for the tab items present on the “Link” dialog.
Current Observation: Upon traversing to the tab item ex: Link Info which is selected Screen readers are narrating as “Tab Link Info”. 

Expected Result:
Screen readers(NVDA/Narrator) should narrate the State i.e. selected for the tab items present on the “Link” dialog.
EX: Upon traversing to the tab item ex: Link Info which is selected Screen readers should narrate as “Tab Link Info Selected”.

WCAG Reference Link:

https://www.w3.org/WAI/WCAG21/Understanding/name-role-value.html

**Comment by msamsel** [comment] 2020-01-23 11:04
Hi @Sukesh-Gundoji,

It seems to be duplicate of this issue: #3547.
Can you confirm that fixing linked issue solves your case as well?

**Comment by Sukesh-Gundoji** [comment] 2020-01-29 07:05
Hi Samsel,

Thank you for reaching out. Yes looks like this issue is a duplicate.

Thanks,
Sukesh.

**Comment by jacekbogdanski** [comment] 2020-01-29 09:26
Duplicate of #3547

**Closed by jacekbogdanski** 2020-01-29 09:26 UTC
Labels: accessibility, status:pending
