### ISSUE TITLE
Pasting image from clipboard

### ISSUE THREAD

**Issue by whity** [ckeditor/ckeditor4#4512] opened 2021-01-26 14:59 UTC
## Type of report

Bug

When pasting a image from the clipboard the event 'change' is fired but the editor does not have any data yet, and after everything has been processed no event 'change' is fired.
I'm not sure if this the way supposed to work, but seems kind of weird.

Please, check the video 

https://user-images.githubusercontent.com/286635/105861652-db391480-5fe6-11eb-9fc8-bef9195d7049.mov

### Expected result

Would expect the 'change' event to be fired after the content was set in the editor

### Actual result

Event 'change' is fired and no content was still set on it.

## Other details

* Browser:  firefox or chrome
* CKEditor version: 4.15.1
* Installed CKEditor plugins: image2

Thanks.

**Comment by sculpt0r** [comment] 2021-01-27 10:00
Hi @whity ,  
I can confirm this behaviour, but please notice, that this documentation sample also use `uploadimage` plugin.  
  
The `change` event, which you used is described here: [https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_editor.html#event-change](https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_editor.html#event-change) 

In some cases, it may works as you expect, but there is no guarantee that on `change` event provides you updated editor data.  
  
In this particular case, you should look at file loader: [https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_fileTools_fileLoader.html](https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_fileTools_fileLoader.html)

This one handles all uploading events, so it may be a good idea to use it to provide "upload finish" signal in your application.  
  
I'm closing this issue since it is not actually a bug.  
Feel free to report feature request if you think that CKEditor4 should behave in some manner. Please provide all details that you would expect. We will be happy to consider it.

**Closed by sculpt0r** 2021-01-27 10:00 UTC
Labels: type:bug
