### ISSUE TITLE
Ck-editor 4.11.4 is not working on edge browser

### ISSUE THREAD

**Issue by janakia** [ckeditor/ckeditor4#3488] opened 2019-09-25 08:04 UTC
## Type of report

Bug
Ck-editor 4.11.4 is not working on edge browser. Integrated the Ck-editor in my application. After integrating with my application, it works fine in chrome, internet explorer,firefox, Its not working in edge browser for windows 10 OS.

## Provide detailed reproduction steps (if any)

1. Open the ck-editor 4.11.4 in edge browser.

### Expected result

It should work in Edge browser.

### Actual result

CK editor is opening, we are able to type the content in editor area, whatever the available function(plugins or button in the tool bar) in tool is not working. For ex: Not able to make the text bold,italic,underline, etc

## Other details
 Getting error in below line of code in ckeditor.js
Error in console:
Object doesn't support property or method 'createTextRange'

In Ckeditor(9177,9)
if (a.getTarget().is("html") && a.$.y < n.$.clientHeight && a.$.x < n.$.clientWidth) {
									r = t.$.createTextRange();
Error in console: Unable to get property 'specified' of undefined or null reference
In Ckeditor(2468,8)
case "contentEditable": 
							return this.$.attributes.getNamedItem("contentEditable").specified ? this.$.getAttribute("contentEditable") : null

* Browser: Edge- version 42.17134.1.10
* OS: Window 10
* CKEditor version: 4.11.4

**Note:**
It is working fine in edge browser for windows 7.

**Comment by msamsel** [comment] 2019-09-25 14:42
I cannot reproduce this error.
I'm using Edge: `Microsoft Edge 44.18362.329.0`, which seems to be actual version now.
Can you check if the error occurs here, where is clear CKEditor implemented on a webpage?
* http://cdn.ckeditor.com/4.12.1/full-all/samples/
* http://cdn.ckeditor.com/4.11.4/full-all/samples/

**Comment by janakia** [comment] 2019-09-25 16:32
I have integrated the ck- editor 4.12.1 version in my application. Still i m getting the sameeroro as mentioned above. Edge version:42.17134.10 OS:Windows 10.

**Comment by janakia** [comment] 2019-09-25 16:37
We are getting the same error in console as mentioned above.  We are able to type the content in editor. But whatever functionality or plugin is not working . In edge browser  of Windows OS machine alone we are facing this issue.

**Comment by msamsel** [comment] 2019-09-27 07:47
We're supporting the latest stable release of Microsoft Edge browser.
Please update your browser version, there should work everything fine.

**Comment by janakia** [comment] 2019-09-27 09:27
I have updated to ck editor  to 4.12.1 release . Edge version is 44.17763.1.10 . OS: window 10. still i m getting the same error as mentioned above.

**Comment by msamsel** [comment] 2019-09-27 09:48
Please provide more details about your environment. Do you run some external tools which might influence on Edge Browser? Is it possible for you to check the issue on another computer? (You can also check the VM: https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/)
Do you make some extra steps except loading page?

![Sep-27-2019 11-44-46](https://user-images.githubusercontent.com/9017322/65759894-41c0d080-e11c-11e9-8861-e5d2a269c8ab.gif)

**Comment by Tejatr** [comment] 2019-09-27 10:55
![BeautyPlus_20190927155513390_save](https://user-images.githubusercontent.com/55478704/65764468-56648f00-e143-11e9-954d-d8fefd63597b.jpg)

**Comment by janakia** [comment] 2019-09-27 11:32
Please find the above screen shots . This error only er are getting

**Comment by msamsel** [comment] 2019-09-27 12:51
Earlier I provide you two links with CKEditor implemented on our page with a question that you could confirm that error occur in such situation. I assumed you test it there and had the same error.
So we go back to the first question:

> I cannot reproduce this error.
> I'm using Edge: `Microsoft Edge 44.18362.329.0`, which seems to be actual version now.
> Can you check if the error occurs here, where is clear CKEditor implemented on a webpage?
> 
> * http://cdn.ckeditor.com/4.12.1/full-all/samples/
> * http://cdn.ckeditor.com/4.11.4/full-all/samples/

**Comment by janakia** [comment] 2019-10-01 02:36
Ckeditor implemented file(replacing the textarea)  is expecting is html 5 <!DOCTYPE html>  declaration. if  doctype declaration changes to the html4 we are getting this error only in edge browser
[html.zip](https://github.com/ckeditor/ckeditor4/files/3674132/html.zip)

. But in other browser (chrome,firefox), we are not getting this error.It is working as expected.

**Comment by janakia** [comment] 2019-10-03 10:32
I have cleared the console error, still none of the functionality is not working. Any other solutions or work around for this issue.

**Comment by janakia** [comment] 2019-10-11 06:16
Any solutions for this issue.

**Comment by Comandeer** [comment] 2019-10-13 13:13
The `DOCTYPE` you provided puts Edge in [quirks mode](https://developer.mozilla.org/en-US/docs/Web/HTML/Quirks_Mode_and_Standards_Mode), so the browser works in the similar way to how IE6 worked. The only sensible solution is to not use HTML4 `DOCTYPE` and stick to the HTML5 one (`<DOCTYPE html>`) or to provide full HTML 4.01 Strict `DOCTYPE`:

```html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
```

As it's clearly issue on browser's side, I'm going to close this issue, because we can't do anything about it.

**Closed by Comandeer** 2019-10-13 13:13 UTC
Labels: status:pending, type:bug
