### ISSUE TITLE
Last Bullet point/ last numbered item(1.) not getting deleted on Backspace key

### ISSUE THREAD

**Issue by vallikumar** [ckeditor/ckeditor4#4000] opened 2020-04-23 19:12 UTC
Normally, a user can delete the bullet lists/numbered lists by using the backspace and delete keys.

CK Editor is not deleting the last  bullet point or last numbered item (1.), 

Steps to reproduce.

Enter some random text e.g Test1 , Test2, Test3, Test4, 
Select the bullet list / Numbered list.
Now keep the cursor at the end of the 4th bulleted item and start deleting by using backspace keys.
While deleting we can see, the ck editor stops deleting the last bullet point  / or last numbered item (1.),  

Observe only text getting deleted and stopped at the last bullet / numbered item.
Expected result:
The bullet list / Numbered list should also be deleted, when the user deleting it with the backspace key.
Actual Results:
the bullet point is not getting deleted,
behind the scenes, some junk characters, br tags or "p< span >& nbsp< /span ></p>" are getting inserted in to the li tag, if we inspect using chrome and see it..

Browser: …Chrome 78 / 79
OS: …Windows 10
CKEditor version: … 4.7.1
Installed CKEditor plugins: with package.

**Comment by Dumluregn** [comment] 2020-04-25 17:39
Duplicate of #3281.

**Closed by Dumluregn** 2020-04-25 17:39 UTC
Labels: type:bug

**Comment by githubalbumman** [comment] 2020-06-30 20:25
Is duping this to a two year old bug that has nobody assigned to it a good idea?
