### ISSUE TITLE
Removing elements after posting form

### ISSUE THREAD

**Issue by DustSwiffer** [ckeditor/ckeditor4#4018] opened 2020-05-04 13:42 UTC
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. Pasting html code in source mode
2. going to preview mode
3. submit the form where ckeditor is in

### Expected result

It should keep the source mode as leading input.

### Actual result

Preview mode is removing some elements (such as A elements). When saving in source mode it will keep it.

## Other details

* Browser: Chrome (but happens in every browser)
* OS: windows 10 (x64)
* CKEditor version: 4.14
* Installed CKEditor plugins: full pack

**Comment by jacekbogdanski** [comment] 2020-05-08 07:12
The preview button is disabled once opening source mode, so I suppose you are talking about some custom editor integration?

![image](https://user-images.githubusercontent.com/10279586/81380463-40707100-910b-11ea-9a5f-85616988e811.png)

If so, indeed we have an issue where it's possible to fetch editor HTML without ACF processing using [editor.getData](https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_editor.html#method-getData) method.

We already have 2 issues related to this one:
https://github.com/ckeditor/ckeditor4/issues/3470
https://github.com/ckeditor/ckeditor4/issues/2326

Also, the issue did get some traction on angular integration:
https://github.com/ckeditor/ckeditor4-angular/issues/89

@DustSwiffer could you confirm that the preview feature is a custom integration, not `preview` plugin and you are using `editor.getData` method when an editor is in source mode?

**Comment by DustSwiffer** [comment] 2020-05-08 07:31
No about this buttom im talking. Whole ckeditor is fresh. There are now custom intergrations. 
When im out of source mode and upload it through the form it will break the code.

I haven't been using editor.getData but i will try that to fix it.
I through `config.allowedContent = true;` was the way to stop the ACF

**Comment by jacekbogdanski** [comment] 2020-05-08 07:35
Sorry, I misunderstood you. Indeed, disabling ACF will still remove some HTML - it may happen because some plugins just work this way e.g. by replacing non-semantic HTML with semantic counterparts or it's required to improve security. Could you tell which HTML is modified and shouldn't be in your case?

**Comment by DustSwiffer** [comment] 2020-05-08 07:41
`<a href="/{lang}/product/22748" class="tileProduct" data-tile=""
                    data-tile-id="22748" data-sort-price="29,9900" data-sort-name="{Product.Name}"
                    data-sort-relevance="18">`
Its removing this element everytime. i think because the extra atributes

**Comment by jacekbogdanski** [comment] 2020-05-08 08:07
Note that the given HTML is incorrect, as the `a` tag has not been closed. Changing it into something like: `<a href="/{lang}/product/22748" class="tileProduct" data-tile="" data-tile-id="22748" data-sort-price="29,9900" data-sort-name="{Product.Name}" data-sort-relevance="18">product1</a>` and enabling ACF fixes the issue.

Despite that ACF is fully disabled, your content still should be correct with HTML 5 specifications. I can suggest not disabling ACF fully, just adding correct rules, e.g.
```javascript
config.extraAllowedContent = 'a[data-title,data-title-id,data-sort-price,data-sort-name,data-sort-relevance](titleProduct)`
```
for security reasons. You can read how to configure ACF in our guide here - https://ckeditor.com/docs/ckeditor4/latest/guide/dev_acf.html

As it doesn't seem like the editor issue, I'm closing it now. But if you can reproduce the issue and think that it's CKEditor 4 bug, please attach some working demo using a chosen online editor, like: 

* CodePen: https://codepen.io/Comandeer/pen/ExaMgpz?editors=1010
* JSFiddle: https://jsfiddle.net/Comandeer/d6ey8a2w
* JSBin: https://jsbin.com/keqekef/1/edit?html,js,output
* StackBlitz: https://stackblitz.com/edit/js-vcqfw3

**Closed by jacekbogdanski** 2020-05-08 08:07 UTC
Labels: status:pending, type:bug

**Comment by DustSwiffer** [comment] 2020-05-08 08:36
the a element contains content and is closed like it used to... but only the a element will be removed

**Comment by jacekbogdanski** [comment] 2020-05-08 08:49
Please, attach demo sample in that case, I cannot reproduce the issue:

![4018](https://user-images.githubusercontent.com/10279586/81388969-61d85980-9119-11ea-9fd5-6af61e7212f0.gif)

note that you also should use `editor.getData` to restore the editor's data.
