### ISSUE TITLE
Chrome 95 causes mouse cursor placement to shift with certain HTML structures after document vertically scrolled

### ISSUE THREAD

**Issue by tbessie** [ckeditor/ckeditor4#4956] opened 2021-11-08 18:36 UTC
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. Using Chrome release 95
2. The HTML document within the CKEditor scrolling content window is long enough that the user can scroll it
3. The document contains a single block-level HTML element (eg. a single `<div> </div>` )
4. The user scrolls vertically several lines in the content window
5. The user left-clicks the mouse within the document on a blank line

### Expected result

The mouse cursor appears where the click occurred

### Actual result

The mouse cursor appears vertically below where clicked, offset by the number of lines scrolled

## Other details

If the HTML document contains other block elements, depending on the specifics of the document structure, this MAY or MAY NOT be reproducible.  I have tested on more complex documents where this doesn't happen.  However, in the simplest case mentioned above (a single block element within the document, with no other block elements), this does occur.

This only started happening as of Chrome release 95.

I thought, at first, that this might be due to the fact that we're using ENTER_BR mode for line breaks.  I tested using ENTER_P (the default), and that seemed to cause this issue to stop occurring.  However, this appears to have been a red herring; when I used ENTER_P mode, but modified the DOM to remove the <P> tags that CKEditor in ENTER_P mode had inserted into the DOM, this bug returned.  It appears that some combination of block-level elements causes this issue, but other combinations cause it to go away.

* Browser: Chrome 95
* OS: Windows 10 / MacOS Big Sur
* CKEditor version: 4.16.2 / 4.8.0
* Installed CKEditor plugins: a11yhelp basicstyles blockquote clipboard colorbutton elementspath enterkey entities filebrowser font format horizontalrule htmlwriter image indentblock indentlist justify link list magicline nbsp pastecode pastefromword pastetext placeholder removeformat scayt sharedspace showborders sourcearea sourcedialog specialchar stylescombo tab table toolbar undo wsc

**Comment by tbessie** [comment] 2021-11-08 21:54
NOTE: We depend on some specific HTML structures in our use of CKEditor, so it appears that simply changing to using ENTER_P would break other functionality.  For instance, we protect some text from modification by users by adding event listeners to some HTML elements.  Changing to use ENTER_P means that things like delete-key events would fire on the surrounding <P> elements that are added by CKEditor when this option is enabled, but wouldn't propagate to the wrapped elements, so our event listeners wouldn't be fired.

It also introduced added vertical spacing, and inserts vertical spacing where it wasn't seen by users before.

I am hoping there is a way to retain use of ENTER_BR while fixing this issue with Chrome.

**Comment by jswiderski** [comment] 2021-11-09 10:29
We were no able to reproduce this issue despite detailed description. Could you attach simplified and working HTML page which shows this problem in code?

**Comment by tbessie** [comment] 2021-11-09 21:14
[demoProblem.html.txt](https://github.com/ckeditor/ckeditor4/files/7508008/demoProblem.html.txt)

See the attached file (rename to demoProblem.html); run in Chrome.
I've included the Source plugin so you can modify the editor content to include a "<div> </div>" somewhere in the middle of the file.

**Comment by tbessie** [comment] 2021-11-09 21:16
Reopening, included sample to reproduce.  This is for the INLINE editor, I think you may not have been testing with that.

**Comment by tbessie** [comment] 2021-11-09 23:17
[Profile-20211109T151612.json.txt](https://github.com/ckeditor/ckeditor4/files/7508579/Profile-20211109T151612.json.txt)

I've included a Chrome profiling tool JSON file (remove the .txt), recorded while this issue is happening.

**Comment by tbessie** [comment] 2021-11-09 23:23
[Profile-20211109T152213.json.txt](https://github.com/ckeditor/ckeditor4/files/7508598/Profile-20211109T152213.json.txt)

I've included another CHrome profiling tool JSON file, recorded using our own copy of CKEditor 4.8.0 (source JS), since this will be easier to use than the obfuscated code/line numbers in the one using the JS loaded from your website.

**Comment by jswiderski** [comment] 2021-11-10 10:07
This is Chrome and not CKEditor bug. After some testing, it has turned out it can be reproduced in native contenteditable area as well. We have reported the problem to Chrome team - [https://bugs.chromium.org/p/chromium/issues/detail?id=1268782.](https://bugs.chromium.org/p/chromium/issues/detail?id=1268782.)

Unfortunately there nothing we can do here except for waiting for ticket resolution in Chrome. 

I'm marking this ticket as an upstream and closing it since this is not an editor bug.

**Closed by jswiderski** 2021-11-10 10:07 UTC
Labels: type:bug, browser:chrome, resolution:upstream, support:2
