### ISSUE TITLE
Superfluous empty spans after pasting from Word

### ISSUE THREAD

**Issue by wwalc** [ckeditor/ckeditor4#3503] opened 2019-09-26 16:31 UTC
Paste the contents of https://ckeditor.com/docs/ckeditor4/latest/examples/assets/pfw/CKEditor4.PFW.Sample.Recognition_of_Achievement.docx into https://ckeditor.com/docs/ckeditor4/latest/examples/pastefromword.html

Result: an editor with empty spans:
![Screen Shot 2019-09-26 at 6 31 56 PM](https://user-images.githubusercontent.com/545175/65706990-e3e4a800-e08b-11e9-92f3-05f139ed88d9.png)

I could not reproduce it on https://cdn.ckeditor.com/4.13.0/full-all/samples/old/replacebyclass.html so it might be a sample issue or require some specific configuration.

**Comment by msamsel** [comment] 2019-09-27 07:57
I can confirm this case on Chrome.
The case appears on an examples page but not on http://cdn.ckeditor.com/4.13.0/full-all/samples/

It seems like a configuration issue inside an example page itself.

**Comment by f1ames** [comment] 2019-12-03 13:29
It is caused by:

```js
extraAllowedContent: 'img[width,height,align];span{background}',
```

config (`span{background}` to be precise). The HTML we get after processing clipboard Word data is:

```html
<h1 align="center" style="margin-bottom:16px; text-align:center; margin-top:16px">
<span style="font-size:22pt">
<span style="line-height:107%">
<span style="font-family:Arial,sans-serif">
<span style="font-weight:normal">
<span lang="EN-US" style="font-family:&quot;Georgia&quot;,serif">
<span style="color:#006699">Recognition of Achievement
</span></span></span></span></span></span></h1>
```

and I assume it's then filtered by ACF, resulting in unsupported attributes being removed:

```html
<h1 style="text-align:center">
<span style="font-size:22pt">
<span>
<span style="font-family:Arial,sans-serif">
<span>
<span style="font-family:&quot;Georgia&quot;,serif">
<span style="color:#006699">Recognition of Achievement
</span></span></span></span></span></span></h1>
```

so the empty spans are left in the content. So `extraAllowedContent:span{background}` means `<span style="background:..."></span>` elements are accepted by ACF, but also spans without any attributes `<span></span>`.

My assumption was that it was done for a second sample document with fancy colors we have in a sample, but if we only want allow `span`s with `background` we could use `span{!background}`.

Also I have tested it with Chrome, FF, IE11, Edge and Safari and it seems for sample documents we have, getting rid of `extraAllowedContent:span{background}` doesn't change anything - I assume at some point `background` attribute handling may have changed and it produces `background-color` now (which is handled by `colorbutton` plugin). I'm not 100% if there are no cases where `background` is present so I think we should be completely safe with `extraAllowedContent:span{!background}`.

**Comment by jacekbogdanski** [comment] 2019-12-03 15:51
Closed via https://github.com/ckeditor/ckeditor4-docs/pull/278

**Closed by jacekbogdanski** 2019-12-03 15:51 UTC
Labels: status:confirmed, type:bug
