### ISSUE TITLE
Moving text(drag n drop)  inside of table by dragging #3745

### ISSUE THREAD

**Issue by vallikumar** [ckeditor/ckeditor4#3984] opened 2020-04-10 23:05 UTC
This is a follow up ticket for thebelow issue(#32745) 

**You would like to have the possibility to move the content around and drop it in a new place.

Should it be available only in the table or should it be possible to drop content outside the table also and create a new one from such content?
Should the content be cut or copied?

Please share you thoughts how this behavior should work.**

_As mentioned We need to drag and drap inside the table cells, As per you taht is a new enhancement, We wanted to check whether any latest upgrades / solutions available for this one, if any, please let us know._

Normally, a user can highlight text words and then click and drag them elsewhere in the text. However, this is not possible with text inside a table. Words inside a table can be highlighted, but then when trying to drag them elsewhere in the table the highlighted term does not move.

CK Editor is not supporting dragging the content inside the table. We have tried with CK editor version 4 and 5.

Steps to reproduce:

…Insert Table with few rows/columns
…Add some contents in cells
…Select consents and try to move around
Expected result:
Editor should allow user to move contents.

Actual Results:
Contents are not moved, drag/drop doesn't work.

Browser: …Chrome 78
OS: …Windows 10
CKEditor version: …7.1
Installed CKEditor plugins: …standard default plugins downloaded as part of package.

**Comment by Comandeer** [comment] 2020-04-11 21:54
I've changed the type of the issue to a feature request, as drag and drop is not implemented in Table Selection plugin.

For now the only workaround is to disable `tableselection` plugin, which will restore the native selection inside the table and allow drag and drop.

**Comment by Dumluregn** [comment] 2020-04-15 08:27
Duplicate of #547 (with a frozen PR #3244).

**Closed by Dumluregn** 2020-04-15 08:27 UTC
Labels: plugin:tableselection, status:confirmed, type:feature
