### ISSUE TITLE
CKEditor 4 pastefromword plugin throws unhandled exception

### ISSUE THREAD

**Issue by ajurry** [ckeditor/ckeditor4#4056] opened 2020-05-15 12:04 UTC
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. Create a custom version of CKEditor 4, using the attached JavaScript
[build-config.txt](https://github.com/ckeditor/ckeditor4/files/4634212/build-config.txt)

2. Attempt to run an instance of CKEditor

### Expected result

CKEditor should work and behave as expected

### Actual result

Throws an unhandled exception which prevents the plugin from working correctly

![image](https://user-images.githubusercontent.com/57255099/82048325-64ecc000-96ac-11ea-89cf-c976214dffe9.png)

## Other details

Associated StackOverflow question: https://stackoverflow.com/questions/61798884/ckeditor-exception-whilst-using-the-pastefromword-plugin
Browser: IE11 (As an embedded browser)
OS: Windows 10
CKEditor version: 4.14
Installed CKEditor plugins: See attached file

**Comment by Comandeer** [comment] 2020-05-18 12:41
I can't reproduce the error in IE11. Does the error occur every time or randomly?

**Comment by ajurry** [comment] 2020-05-19 10:21
Hmmm... It's probably the way in which I'm embedding the browser. It seems to occur every time.

**Comment by Comandeer** [comment] 2020-05-25 15:49
Currently [we do not support embedded browsers](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_browsers.html#officially-supported-browsers). As it works in non-embedded IE 11, I'm going to close the issue.

**Closed by Comandeer** 2020-05-25 15:49 UTC
Labels: status:pending, type:bug
