### ISSUE TITLE
Unintended Paragraph Text Deletion Occurring

### ISSUE THREAD

**Issue by dfisher-lls** [ckeditor/ckeditor4#4716] opened 2021-05-17 15:55 UTC
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. Go to the ckeditor4 demo page https://ckeditor.com/ckeditor-4/demo/.
2. In the demo, place your cursor after the word 'much' on the second line of text.
3. Press the backspace key once.

### Expected result

The letter 'h' should be deleted from the word 'much'.

### Actual result

The entire paragraph of text that contains the word 'much' is deleted.

## Other details

Browser: Google Chrome - Version 90.0.4430.93 (Official Build) (64-bit)
OS: Win10
CKEditor: v4
Additional: This does not occur when using Firefox.

**Comment by Comandeer** [comment] 2021-05-18 13:30
Duplicate of #4628.

**Closed by Comandeer** 2021-05-18 13:30 UTC
Labels: type:bug
