### ISSUE TITLE
Image pasted twice when copy from browsers

### ISSUE THREAD

**Issue by easygolabs** [ckeditor/ckeditor4#4924] opened 2021-10-06 10:16 UTC
## Type of report

Bug

## Provide detailed reproduction steps (if any)

The investigation of the browsers behavior showed that the different browsers insert images in different ways. The picture was inserted twice or once (randomly) : it is not clear why the one picture was inserted once and the other twice. So, solved the problem for one browser, can be created to another. Any ideas how it should be solved based on the investigation on the screenshot?

![image](https://user-images.githubusercontent.com/26522547/136183033-2ea188f8-611c-41bc-bdfd-e66b1f58710b.png)

**1** - if comment the line `d.insertElement(b)` in `ckeditor/ckeditor.js` -> `function h(a, d)`
**2** - without changes

![Безымянный](https://user-images.githubusercontent.com/26522547/136183498-90443bf4-a667-4baf-b02e-929b27a3b48b.png)

### Expected result

It should be pasted just once.

### Actual result

Pasted twice

## Other details

* Browser: `Chrome` `Firefox` `Edge` `Explorer`
* OS: `Windows 10 Pro` `20H2` `19042.1266`
* CKEditor version: `4.14.1`
* Installed CKEditor plugins: `a11yhelp`, `about`, `autocomplete`, `autolink`, `base64image`, `ckwebspeech`, `clipboard`, `colordialog`, `dialog`, `div`, `fakeobjects`, `find`, `flash`, `forms`, `iframe`, `image`, `insertimage`, `link`, `lifestyle`, `magicline`, `pagebreak`, `pastebase64`, `pastefromword`, `pastetools`, `preview`, `scayt`, `setstyle`, `showblocks`, `smiley`, `specialchar`, `table`, `tabletools`, `templates`, `textmatch`, `wsc`

**Comment by easygolabs** [comment] 2021-10-07 09:03
> 
> 
> It could be caused by #4874. Could you disable all custom plugins for inserting/pasting images (`base64image`, `pastebase64` and `insertimage`) to the editor and check if issue's still present?
> 
> Issue can be also caused by the fact that you use more than one plugin to handle image pasting.

If disable `pastebase64` the issue is not present, but i can't copy from the clipboard.

**Comment by Comandeer** [comment] 2021-10-07 10:58
You can download [the nightly version](https://nightly.ckeditor.com/) to check if the issue is resolved.

From the code you mentioned above you need only `clipboard_handleImagePasting` option and it should be added to your code for initializing the editor. It will disable built-in image pasting and then `pastebase64` plugin should work normally, pasting only one image.

**Comment by Comandeer** [comment] 2021-10-08 08:57
Ok, so I'm closing it as a duplicate of #4874.

Please note that the fix will be officially released in 4.17.0, the nightly version is still experimental.

**Closed by Comandeer** 2021-10-08 08:57 UTC
Labels: type:bug

**Comment by easygolabs** [comment] 2022-01-04 11:53
@Comandeer, hi, i have downloaded the `4.17.1` version and added `config.clipboard_handleImages = false;` to `config.js`. Opened the `/ckeditor/samples/` for test and the image is pasting twice. Do I missing something? It had worked for the nightly version. (what has been mentioned in the previous discussion) 

![Безымянный](https://user-images.githubusercontent.com/26522547/148055015-698cbe97-d6ee-4b36-8644-c0dd7e274d49.jpg)

**Comment by Comandeer** [comment] 2022-01-05 13:50
Could you provide some demo of the issue?

**Comment by Comandeer** [comment] 2022-01-05 13:50
Could you provide some demo of the issue?

**Comment by easygolabs** [comment] 2022-01-05 20:56
> Could you provide some demo of the issue?

Of course, you can view at this link: https://drive.google.com/file/d/1eFJhPFD2TLHIVxQAAt2egeZ3gIGTtb4c/view

**Comment by Comandeer** [comment] 2022-01-13 20:52
@easygolabs, sorry for the delayed response. After quick debugging it seems that the issue is connected with `pastebase64` plugin. After removing it, the image was pasted correctly.

**Comment by easygolabs** [comment] 2022-01-14 13:53
@Comandeer right, is this issue could be confirmed and there will be one more fix? Or the reason of this is incorrect use of plugins and it needs to avoid using `pastebase64` plugin with the similar.

**Comment by Comandeer** [comment] 2022-01-14 14:06
It's an issue with a third-party plugin, `pastebase64`. Without it setting `config.handleImages` to `false` seems to work correctly.
