### ISSUE TITLE
CKEditor remove all paragraph when backspace 1 symbol at the end of line

### ISSUE THREAD

**Issue by Lipau3n** [ckeditor/ckeditor4#4661] opened 2021-04-30 11:10 UTC
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. Open demo https://ckeditor.com/docs/ckeditor4/latest/examples/pastefromgoogledocs.html
1.2. or paste from google doc to yours CKEditor
2. Place the cursor at the end of the line (this paragraph must contain several lines!). It doesn't have to be the last line of a paragraph.
3. Press backspace and CKEditor removes the entire paragraph instead of the character on the left.

Note: in Safari there is a space at the end of the line, so the entire paragraph is not deleted there.

Video: [https://drive.google.com/file/d/1M7pIsCsRK37gFxw8wDDHrklRLsXRWzBO/view?usp=sharing](https://drive.google.com/file/d/1M7pIsCsRK37gFxw8wDDHrklRLsXRWzBO/view?usp=sharing)

### Expected result

Only the character to the left of the cursor will be deleted.

## Other details

* Browser: Google Chrome
* OS: macOS Big Sur 11.2.3 / Parallels Desktop win 10 Google Chrome
* CKEditor version: 4.16.0 i seems, on demo site it is latest

**Comment by Dumluregn** [comment] 2021-04-30 11:30
Hello, it's a duplicate of https://github.com/ckeditor/ckeditor4/issues/4628, which is a Chromium upstream issue. Please watch it for the current state of the problem (it should be fixed at `v91` at latest).

**Closed by Dumluregn** 2021-04-30 11:30 UTC
Labels: type:bug
