### ISSUE TITLE
Unable to enter new line with enter key [mobile]

### ISSUE THREAD

**Issue by sculpt0r** [ckeditor/ckeditor4#5210] opened 2022-05-12 09:36 UTC
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. Open the editor (e.g. in samples)
2. Press enter (on mobile device keyboard)
3. Type some text
4. Press the enter again

### Expected result

*What is the expected result of the above steps?*

New line appears and the carret is placed in the new line.

### Actual result

*What is the actual result of the above steps?*

New line appears, but the carret is still in the same line where the typing was ended.

## Other details

* Browser: Chrome (android) 101.0.4951.61
* OS: Android  11
* CKEditor version: 4.19.0 (pre-release)
* Installed CKEditor plugins: full all

**Comment by Comandeer** [comment] 2022-05-12 09:38
Duplicate of #4409.

**Closed by Comandeer** 2022-05-12 09:38 UTC
Labels: type:bug, status:confirmed, browser:android, plugin:wysiwygarea

**Comment by sculpt0r** [comment] 2022-05-12 09:42
But the reference issue mention the underline 🤔

**Comment by sculpt0r** [comment] 2022-05-12 09:45
Also - It works normally whenever the sentence ends with space 🤔
