### ISSUE TITLE
Clear table source from editor without table leaves empty rows

### ISSUE THREAD

**Issue by dimobrandmaker** [ckeditor/ckeditor4#3941] opened 2020-03-19 13:52 UTC
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. The CK editor has only Source option in the toolbar.
2. The value

`<table border="1" style="width:110pt;height:13pt;">`
`<tbody>`
`<tr>`
`<td>table</td>`
`<td><b>table</b></td>`
`</tr>`
`</tbody>`
`</table>`
`<div>B&nbsp;</div>`   

goes into the CK editor.
3. The value is stripped and one unneeded empty row is left. Because of this: `<td>table</td>` . When the table is stripped the `<td>table</td>` becomes `<td></td>,` where TD has child value "". Then 

> htmldataprocessor.js

 is fired and its method 

> function isEmptyBlockNeedFiller( block )

 The fix is in the return statement where we skip the TD for the need of BR, e.g. 

> return (!last && !(block.name in CKEDITOR.dtd.tr)) || block.name == 'form' && last.name == 'input' ;

### Expected result

The stripped table should not leave empty rows.

### Actual result

There are 0 to n empty rows,

## Other details

* CKEditor version: 4.7.2

**Comment by Dumluregn** [comment] 2020-03-20 10:40
Hello, could you provide the list of plugins in your config? And also did you try to replicate it with the latest editor version, i.e. `4.14.0`?

**Comment by dimobrandmaker** [comment] 2020-03-20 14:31
Hello! 

1. We can't test 4.14.0  currently, because we use the CK editor in a big product, where the change is not easy.
2. We have some customization, so the real case for you is when you reach the simple case:
 `<td></td>` . Then this is replaced with `<div><br/><div>` .
3. Here are the plugins, which we have configured:

plugins : {
		'a11yhelp' : 1,
		'about' : 1,
		'ajax' : 1,
		'autogrow' : 1,
		'basicstyles' : 1,
		'bidi' : 1,
		'blockquote' : 1,
		'button' : 1,
		'ckeditor-gwf-plugin' : 1,
		'clipboard' : 1,
		'codemirror' : 1,
		'colorbutton' : 1,
		'colordialog' : 1,
		'confighelper' : 1,
		'contextmenu' : 1,
		'devtools' : 1,
		'dialog' : 1,
		'dialogadvtab' : 1,
		'dialogui' : 1,
		'div' : 1,
		'divarea' : 1,
		'docprops' : 1,
		'elementspath' : 1,
		'enterkey' : 1,
		'entities' : 1,
		'fakeobjects' : 1,
		'filebrowser' : 1,
		'find' : 1,
		'flash' : 1,
		'floatingspace' : 1,
		'floatpanel' : 1,
		'font' : 1,
		'format' : 1,
		'forms' : 1,
		'horizontalrule' : 1,
		'htmlwriter' : 1,
		'iframe' : 1,
		'iframedialog' : 1,
		'image' : 1,
		'imagebrowser' : 1,
		'indent' : 1,
		'indentlist' : 1,
		'justify' : 1,
		'lineutils' : 1,
		'link' : 1,
		'list' : 1,
		'listblock' : 1,
		'liststyle' : 1,
		'magicline' : 1,
		'maximize' : 1,
		'menu' : 1,
		'menubutton' : 1,
		'newpage' : 1,
		'pagebreak' : 1,
		'panel' : 1,
		'panelbutton' : 1,
		'pastefromexcel' : 1,
		'pastefromword' : 1,
		'pastetext' : 1,
		'placeholder' : 1,
		'popup' : 1,
		'preview' : 1,
		'print' : 1,
		'removeformat' : 1,
		'resize' : 1,
		'richcombo' : 1,
		'save' : 1,
		'scayt' : 1,
		'selectall' : 1,
		'sharedspace' : 1,
		'showblocks' : 1,
		'showborders' : 1,
		'smiley' : 1,
		'sourcearea' : 1,
		'sourcedialog' : 1,
		'specialchar' : 1,
		'stylescombo' : 1,
		'stylesheetparser' : 1,
		'tab' : 1,
		'table' : 1,
		'tableresize' : 1,
		'tabletools' : 1,
		'templates' : 1,
		'textselection' : 1,
		'toolbar' : 1,
		'uicolor' : 1,
		'undo' : 1,
		'widget' : 1,
		'wordcount' : 1,
		'wsc' : 1,
		'wysiwygarea' : 1,
		'xml' : 1
	},

**Comment by Dumluregn** [comment] 2020-03-21 14:50
Unfortunately I have a problem with reproducing your issue.

I set toolbar config as you wrote (so `toolbar: [ [ 'Source' ] ]`), pasted the code you provided (I supposed it should be pasted in source mode), then switched to wysiwyg and I don't see a table, just two paragraphs:
```html
<p>tabletable</p>

<p>B&nbsp;</p>
```
As you can read in [our Toolbar Docs](https://ckeditor.com/docs/ckeditor4/latest/examples/toolbar.html):
> When content filtering is working in automatic mode, toolbar configuration affects what is allowed in the editor. In other words, CKEditor will only allow the type of content that can be created using the available toolbar buttons and will remove disallowed elements.

So when there is only `source` button, there is no possibility the table element will be present unless you are also using custom [Content Filter](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_acf.html), and if you do please post it too.

You also seem to use a lot of 3rd party plugins, which we don't own and there is a possibility that some of them are messing around your project.

Last but not least, if you have CKEditor license, please contact our support team where you can get more help with your custom implementation.

**Comment by dimobrandmaker** [comment] 2020-03-23 15:11
We have overriden some plugins, so it is hard to say how to reproduce it. Anyway the case passes via non-touched CK plugins, so i am going to paste the screenshot from the stacktrace and you decide if this is a bug or not.
![Screenshot from 2020-03-23 16-59-50](https://user-images.githubusercontent.com/62385596/77331331-3ea04900-6d29-11ea-9a61-8d9da6d84797.png)

**Comment by jacekbogdanski** [comment] 2020-03-27 10:47
If I understand correctly, your issue is about removed `table` keyword from table elements due to too aggressive HTML stripping done by `htmldataprocessor`? If so, I'm also not able to reproduce the issue also:

![table](https://user-images.githubusercontent.com/10279586/77748319-6e4c9b00-7020-11ea-80e1-4d36269eb176.gif)

Unfortunately, the only stack trace screenshot is not enough to successfully verify the issue. Please, provide a working demo of the issue using some online tools like https://codepen.io so we can verify if the issue is valid.

**Comment by Dumluregn** [comment] 2020-04-10 08:52
Hi, It's been a while since we last heard from you. We're closing this issue for now. Still, feel free provide us requested feedback, so that we can reopen this issue.

**Closed by Dumluregn** 2020-04-10 08:52 UTC
Labels: status:pending, type:bug

**Comment by dimobrandmaker** [comment] 2020-04-10 11:07
Hi, i can't provide more info. This is all i have. The case in https://github.com/ckeditor/ckeditor4/issues/3941#issuecomment-604934167 not the same. The CK editor must have only Source option (p.1 from my description). Also i described the code flow with steps and screenshot. i can't find fiddle with CK editor with only Source sode option. Anyway it is your choice to consider if it is a bug or not. We fixed it on our side.

**Comment by Dumluregn** [comment] 2020-04-10 11:25
Hi, thank you for the reply. We are sorry but without being able to reproduce an issue on our side we shouldn't just change some code without understanding what we are trying to fix as it may cause a lot of new unexpected behaviours (especially that we are referring to one of the core editor functions). It's great you managed to fix this in your implementation and if the similar but reproducible issue ever occurs, we will probably take a look at your solution.
Have a nice day!

**Comment by dimobrandmaker** [comment] 2020-04-10 11:34
Have a nice day too
