### ISSUE TITLE
Rich text editor getting crashed on iOS.

### ISSUE THREAD

**Issue by electem** [ckeditor/ckeditor4#3640] opened 2019-11-09 12:21 UTC
## Type of report

Bug - Rich text editor getting crashed after typing around 2000 characters on iOS app.

## Provide detailed reproduction steps (if any)

1.Opened the new rich text editor
2.Type more than 1800 characters.
3.Text editor starts freezing.

### Expected result
Should be able to type up to 5000 characters as mentioned.

### Actual result
After typing around 2000 characters text editor is getting crashed.
*What is the actual result of the above steps?*

## Other details

* CKEditor version: 4
* Installed CKEditor plugins: …4.12.1

![IMG_20191109_172747](https://user-images.githubusercontent.com/54798178/68528305-f0108600-0316-11ea-8be9-b88b3a08776c.jpg)

**Comment by Dumluregn** [comment] 2019-11-12 10:14
Hello!
I didn't manage to reproduce the issue. Without any problem I managed to type over 5000 characters in the editor as seen on the screen below (it's [full editor preset](http://cdn.ckeditor.com/4.13.0/full-all/samples/) with [Word Count plugin](https://ckeditor.com/cke4/addon/wordcount) added):
![Image-1](https://user-images.githubusercontent.com/10883184/68662523-43641d80-053d-11ea-8f52-c0f5968612d1.jpg)

By the way it seems to me you are not using pure CKEditor, but some custom implementation, so please check if you are experiencing the same issue using our [CDN](http://cdn.ckeditor.com/4.13.0/full-all/samples/).

**Comment by electem** [comment] 2019-11-14 14:15
Hi Dumluregn,

  As you can see in the above screen shot that we uploaded, we need only limited features so we are using basic package of CKEditor. Could you please help us in this environment?

Thank You

**Comment by f1ames** [comment] 2019-11-14 14:18
@electem can you share you env details - like iOS version and browser type and version?

**Comment by electem** [comment] 2019-11-15 10:24
Hi @f1ames  

 we found this issue for the below mentioned devices while testing on MTR mobile application From App Store.
 
 1.iPad  Model MD13LL/A
   iOS version 10.3.3
 
 2.iPhone10,5
 OS Version:          iPhone OS 13.1.3 (17A878)

Thank You

**Comment by f1ames** [comment] 2019-11-15 11:21
Thanks @electem, is MyTechReports app you are developing? Can't find it in the App Store. Does it use some kind of WebView internally?

**Comment by f1ames** [comment] 2019-11-19 08:35
@electem Is MTR some custom application? Does it use something like WebView underneath or you just open it in regular browser (can you tell use which one and what version)?

**Comment by electem** [comment] 2019-11-21 14:14
Hi @f1ames,

  We are the developers of MyTechReports application, this application is working fine for android the issue is only with the iphone, and both adnroid and iOS are having the same js files.
  
  you will get the mytechreports app on Apple store. try searching with "my tech reports", these are the credentials for logging in to the application for your testing.
  KEY:      limswt
  username: admin
  password: 12345



[video for testing.zip](https://github.com/ckeditor/ckeditor4/files/3875027/video.for.testing.zip)

  please follow the below steps shown in the video, in order to login and recreate the isssue.
 
Thank You.

**Comment by f1ames** [comment] 2019-11-26 09:58
Hello @electem,
thanks for sharing details and the video. I have rechecked the issue with your app on iPad Air with 12.4.1 iOS version and iPhone 11 with iOS 13. Tested with more than 15k characters in the editor and it works smooth, applying bold,italics, lists works instantaneously and I didn't notice any delay.

The only thing visible, was one scrolling issue (already reported #498). Not sure where is the difference and what could be the issue that makes it slow on your devices 🤔

**Comment by electem** [comment] 2019-12-02 14:57
Hi @f1ames,

   As you mentioned above we checked the issue #498, and as suggested in the discussions we tried installing  divarea plugin on our system, but nothing worked, we are still facing the same issue.

Apart from the scrolling issue, we are also facing another issue, when we are typing more than 2500 character the ck-editor is getting crashed. 

please check the below attached video , here we are able to recreate the issue and 
this might help you to understand the issue that we are trying to tell.

could you please check the below attached video and help us with this issue.
[mtr_App_Testing1.zip](https://github.com/ckeditor/ckeditor4/files/3911702/mtr_App_Testing1.zip)


Thank You.

**Comment by f1ames** [comment] 2019-12-11 11:32
Hi @electem,
the scrolling issues is a separate thing, if you have any observations which could help use solve it, feel free to drop a comment in #498.

As for performance issue, we are not able to reproduce it as mentioned in previous https://github.com/ckeditor/ckeditor4/issues/3640#issuecomment-558554044. On the attached video I can see the scrolling issue, but the performance seems normal - no delay for typing.

**Comment by jacekbogdanski** [comment] 2019-12-29 13:04
Hi, It's been a while since we last heard from you. We're closing this issue for now. Still, feel free provide us requested feedback, so that we can reopen this issue.

**Closed by jacekbogdanski** 2019-12-29 13:04 UTC
Labels: status:pending, type:bug

**Comment by electem** [comment] 2020-01-07 05:53
Hi @jacekbogdanski, We have gone through the issue #498 and as they have suggested to install divarea plugin on our system, we tried and still it is not working. Could you please help us to find the solution.

Thank You.

**Comment by jacekbogdanski** [comment] 2020-01-07 08:20
Using `divarea` plugin should fix the issue with #498 because the upstream issue only touches `contenteditable` elements. If despite using `divarea` plugin you can still reproduce scroll issue, please provide minimal CKEditor 4 demo with reproduction steps where you can observe it. Please, provide this information as feedback to #498 ticket so we can keep issue status in one place. Note that it's very hard for us to debug application we don't own, so we would appreciate it if you could provide a demo without 3rd party software.
