### ISSUE TITLE
PasteFromWord plugin not able to load image in case word doc has image in Header

### ISSUE THREAD

**Issue by niagrawa** [ckeditor/ckeditor4#4387] opened 2020-11-19 13:44 UTC
## Type of report

Bug

## Provide detailed reproduction steps (if any)

[1-8_9_LS Lost Procedure_101320 (1).docx](https://github.com/ckeditor/ckeditor4/files/5567048/1-8_9_LS.Lost.Procedure_101320.1.docx)

1. Open above word doc
2. Press "Ctrl" + "A" 
3. Press "Ctrl" + "V" in editor

### Expected result

Content should be pasted completely.

### Actual result

Images are lost.

## Other details

* Browser: All
* OS: All
* CKEditor version: 4
* Installed CKEditor plugins: pastefromword

**Comment by f1ames** [comment] 2020-11-19 14:03
Hello @niagrawa,

Thanks for reporting. We have recently fixed similar issue (#2800) and it's targeted for the next `major` release (`4.16` version). Could you check on the nightly build (which includes this fix already) if your issue is solved? Nightly build is available here - https://nightly.ckeditor.com/20-11-19-07-04/full/samples/.

**Comment by niagrawa** [comment] 2020-11-19 14:51
Hi Krzysztof,

Thanks for the quick reply. I have verified that the issue is fixed in the
nightly build using the link you provided. Just one question - When will
the 4.16 release version be available for consumption?

-Nisha

**Comment by f1ames** [comment] 2020-11-20 07:03
Thanks for checking and confirming the issue is already solved :tada: 

We don't have exact date for `4.16` version yet, but it will be release somewhere on the beginning of the next year (Q1 2021).

I'm closing this issue as duplicate of #2800.

**Closed by f1ames** 2020-11-20 07:03 UTC
Labels: plugin:pastefromword, type:bug
