### ISSUE TITLE
Selecting codesnippet inserts additional empty line after it

### ISSUE THREAD

**Issue by f1ames** [ckeditor/ckeditor4#997] opened 2017-10-03 12:56 UTC
## Are you reporting a feature request or a bug?

Bug

## Provide detailed reproduction steps (if any)

1. Go to https://sdk.ckeditor.com/samples/codesnippet.html.
2. Select `codesnippet` widget in the first editor.

### Expected result

Widget is selected, no content changes in the editor.

### Actual result

Widget is selected, additional empty line added after widget.

![oct-03-2017 14-07-05](https://user-images.githubusercontent.com/1061942/31124306-3739eeac-a844-11e7-9948-ef3173b2525e.gif)

## Other details

* Browser: Edge
* OS: Windows 10
* CKEditor version: 4.7.3
* Installed CKEditor plugins: `codesnippet`

**Comment by thommyhh** [comment] 2020-02-16 16:13
This issue exists since 2017. Is there any chances, that this will be fixed? That's quote an annoying bug.

**Comment by f1ames** [comment] 2020-02-17 06:57
Since it is Edge only (`EdgeHTML` based) issue and new version of Edge is already using Chromium engine (were it should work just fine) we are not planning to work on this issue in the foreseeable future.

@thommyhh are you for some reason planning to use older Edge (`EdgeHTML` based) version or will be migrating to the latest one?

**Comment by thommyhh** [comment] 2020-02-17 13:07
@f1ames I must have missed the `browser:edge` label. But I experience the same bug with Chrome 80. It happens, when the code block is inserted as the last element. If I cut the code snippet and paste it again, the empty paragraph after it disappears. It does not either re-appear, when editing the snippet. So it looks to be only at the first creation of the code snippet block.

**Comment by Dumluregn** [comment] 2020-07-23 13:38
This issue is no longer reproducible in the latest Edge browser version.

**Closed by Dumluregn** 2020-07-23 13:38 UTC
Labels: browser:edge, good first issue, plugin:codesnippet, status:confirmed, type:bug
