### ISSUE TITLE
Uncaught TypeError: Cannot read property 'clientTop' of undefined

### ISSUE THREAD

**Issue by weichuan-dong** [ckeditor/ckeditor4#4093] opened 2020-06-02 22:41 UTC
## Type of report

Bug

## Provide detailed reproduction steps (if any)
1. our product uses creditor 4.14. Intermittantly exceptions were thrown:
=========
Unhandled application error: Uncaught TypeError: Cannot read property 'clientTop' of undefined @https://day119-20500-sql-110h.qa.lan/AgentWeb/api/agentbrowserui/v.32001290010/libs/ckeditor/ckeditor.js:127:108

Cannot read property 'clientTop' of undefined

@TypeError: Cannot read property 'clientTop' of undefined

    at CKEDITOR.dom.element.getDocumentPosition (https://day119-20500-sql-110h.qa.lan/AgentWeb/api/agentbrowserui/v.32001290010/libs/ckeditor/ckeditor.js:127:108)

    at g (https://day119-20500-sql-110h.qa.lan/AgentWeb/api/agentbrowserui/v.32001290010/libs/ckeditor/ckeditor.js:681:93)

    at https://day119-20500-sql-110h.qa.lan/AgentWeb/api/agentbrowserui/v.32001290010/libs/ckeditor/ckeditor.js:682:396 TypeError: Cannot read property 'clientTop' of undefined

    at CKEDITOR.dom.element.getDocumentPosition (/AgentWeb/api/agentbrowserui/v.32001290010/libs/ckeditor/ckeditor.js:127)

    at g (/AgentWeb/api/agentbrowserui/v.32001290010/libs/ckeditor/ckeditor.js:681)

    at /AgentWeb/api/agentbrowserui/v.32001290010/libs/ckeditor/ckeditor.js:682
======
the code in the minified ckeditor.js is as followed:
                      , h = e.$.documentElement
                      , u = h.clientTop || d.$.clientTop || 0
                      , n = h.clientLeft || d.$.clientLeft || 0

d.$ was undefined when the exception was thrown.

2. I downloaded the source code of ckeditor and found that the call stack of the exception is at 
line 1531 in function getDocumentPosition at element.js
line 126 in function contentHeight at outgrow plugin.js when it calls element.getDocumentPosition 

I used dev tool to override the function getDocumentPosition in ckeditor.js:127:108 and added a null check throughout "getDocumentPosition" function:
                      , h = e.$.documentElement
                      , u = h.clientTop || d.$? d.$.clientTop : 0
                      , n = h.clientLeft || d.$? d.$.clientLeft : 0

The issue was gone.

3. There was a related issue reported before: https://github.com/ckeditor/ckeditor4/issues/3635. So I wonder if some null check can be added to prevent the exception?

## Other details
* CKEditor version: 4.14
* Installed CKEditor plugins: autogrow

Best Regard!

**Comment by f1ames** [comment] 2020-06-03 06:01
Hi @weichuan-dong, can you provide reproduction steps (or simple demo) for this issue? Also could you share your editor config and preset you are using so we can investigate further?

**Comment by weichuan-dong** [comment] 2020-06-03 19:11
Hi@f1ames, it's really really hard to reproduce it. It's intermittent to reproduce it. Per the persons who found the issue, they saw the issue once the ckeditor is loaded.


The editor config is:
allowedContent: true
coreStyles_bold: {
          element: 'span',
          styles: {
            'font-weight': 'bold'
          }
        },
coreStyles_italic: {
          element: 'span',
          styles: {
            'font-style': 'italic'
          }
        },
coreStyles_strike: {
          element: 'span',
          styles: {
            'text-decoration': 'line-through'
          }
        },
coreStyles_underline: {
          element: 'span',
          styles: {
            'text-decoration': 'underline'
          }
        },
enterMode: 2
extraPlugins: "autogrow,sharedspace,emoji"
autoGrow_minHeight: 65
autoGrow_maxHeight: undefined
autoGrow_onStartup: true
removePlugins: "resize,elementspath,magicline,liststyle,tableselection,tabletools,contextmenu,divarea"
startupFocus: true
readOnly: true
toolbar: [
          {
            items: [
              'Bold',
              'Italic',
              'Underline',
              '-',
              'TextColor'
            ],
            name: 'basicstyles'
          }]
height: 65
sharedSpaces: {top: "chatPanelContents_207publictoolbar"}
disableNativeSpellChecker: false

**Comment by f1ames** [comment] 2020-06-08 08:47
@weichuan-dong I created a [demo with config](https://codepen.io/f1ames/pen/NWxGPed?editors=1010) you provided but it seems everything works fine - no errors in the console. Without any more details it might be hard to reproduce and investigate on our side.

**Comment by weichuan-dong** [comment] 2020-06-08 16:25
@f1ames yeah. to be honest, I myself wasn't able to reproduce it either. But a few users of our product including qa testers, real users and developers reported the issue intermittently. I did the static analysis based on the call stack they provided and found that the exceptions were thrown in element.js. I totally agree that it's really hard to investigate the issue on your side without reproducing it. However I wonder if some null check could be added in element.js which seems to prevent "property of undefined" to happen theoretically and doesn't hurt anything (to me)?

**Comment by jswiderski** [comment] 2020-06-15 15:48
@weichuan-dong the main problem here is that we first have to find out why the problem occurs before we add any `null` checks. If there are no `null` checks at the moment it is most likely because `nulls` should not occur in the first place and not because we have forgotten to add them. 

If we were to add them to the code without making any checks this could lead to some hidden errors in the future thus it is crucial to find out the root cause first.

**Comment by weichuan-dong** [comment] 2020-06-15 15:53
@f1ames I see. I will try to record the issue and post it to you. Thanks for the response.

**Comment by weichuan-dong** [comment] 2020-06-24 19:23
@f1ames our tester reported to reproduce the issue again. I am attaching the screenshot that our tester took. Hope it helps. 

<img width="1044" alt="Screen Shot 2020-06-24 at 9 46 19 PM" src="https://user-images.githubusercontent.com/55892307/85618332-dc9ffa00-b61d-11ea-9e78-6928d66d7149.png">

**Comment by f1ames** [comment] 2020-06-25 06:27
Thanks @weichuan-dong, you may also try to ask your tester what steps/operations were performed before the error occurred - any more details will be helpful for us when trying to find the cause of this issue.

**Comment by weichuan-dong** [comment] 2020-06-25 19:15
@f1ames Our tester reproduced it and then she started recording. During the next about 10 min, she was able to reproduce one more time. I tried to add the video in the attachment however mp4 is not supported.  Is there a way that I send the recorded video to you so that you can see how it was reproduced? Per our tester's statement, it is hard to reproduce. She said in that 10 min try she could reproduce it twice , so it is reproducible but looks like some timing/race condition is hit, not every time seen though.

**Comment by weichuan-dong** [comment] 2020-06-25 19:19
@f1ames  I compressed it to .zip file and am attaching it. Hope you can see it.
[clienTopApplicationError.mp4.zip](https://github.com/ckeditor/ckeditor4/files/4833384/clienTopApplicationError.mp4.zip)

**Comment by weichuan-dong** [comment] 2020-06-26 22:02
Hi @f1ames , one more person reported the issue again when he was testing a production site. Is it possible that we set up a meeting? So that you could review the setting of our ckeditor, view the recorded video, or even possibly our tester may try to reproduce it with you. Any help will be highly appreciated. 
Thanks very much,
Weichuan

**Comment by f1ames** [comment] 2020-06-29 16:37
Thanks @weichuan-dong, we will try to check this issue when possible, however due to other priorities we don't have any ETA yet. We prefer to debug and analyze issue based on received reproduction steps and editor configuration as it proved more effective that debugging during video calls.

Also keep in mind that if you have CKEditor license, you may contact our support team, to see if we can do anything more to help.

**Comment by f1ames** [comment] 2020-07-22 07:28
Hi @weichuan-dong, from what we can see in the video, the error occurs around 10th minute of the recording. However, it's really hard to grasp what interaction lead to that and it's not visible on the recording where and how CKEditor 4 is used there (I don't see it on the video TBH :thinking:).

Since the error occurs randomly, it might be really hard to reproduce it without a clear scenario or simplified demo where it can be seen. Providing the above will help us analyze the issue and without it, unfortunately, we won't be able to proceed with this report.

**Comment by Dumluregn** [comment] 2020-08-05 09:25
Hi, It's been a while since we last heard from you. We're closing this issue for now. Still, feel free provide us requested feedback, so that we can reopen this issue.

**Closed by Dumluregn** 2020-08-05 09:25 UTC
Labels: status:pending, type:bug, workload:?
