### ISSUE TITLE
CKEditor 4.16.2.7 Uncaught TypeError: Cannot read properties of undefined (reading 'addCodeSample')

### ISSUE THREAD

**Issue by thedja** [ckeditor/ckeditor4#5247] opened 2022-06-21 10:27 UTC
Encountering a problem with CKeditor when loaded in a Salesforce page with the following js error : 

> plugin.js?t=4.16.2.7:1 Uncaught TypeError: Cannot read properties of undefined (reading 'addCodeSample')
    at Object.init (plugin.js?t=4.16.2.7:1:251)
    at Object.<anonymous> (ckeditor.js?t=4.16.2.7:268:282)
    at n (ckeditor.js?t=4.16.2.7:248:455)
    at Array.r (ckeditor.js?t=4.16.2.7:249:93)
    at v (ckeditor.js?t=4.16.2.7:249:177)
    at ckeditor.js?t=4.16.2.7:250:131

N.B: It was working fine until June 15th

**Comment by sculpt0r** [comment] 2022-06-23 11:56
Hi @thedja 

If you have CKEditor license, please contact our support team - then we will be able to investigate the issue with more details via email communication.

Based on your current details I'm not able to reproduce the issue - what is more - we do not do that in third-party integrations. I strongly encourage you to contact our support team in case you have a license.

**Comment by sculpt0r** [comment] 2022-06-24 07:14
I'm closing the issue.

**Closed by sculpt0r** 2022-06-24 07:14 UTC

**Comment by DanBeerNebula** [comment] 2022-06-29 12:33
For what it's worth we had the same issue and just removed the offending plugin (in our case 'sfdcCodeBlock') via the removePlugins config:

`CKEDITOR.replace('bodyInput', {
                customConfig:'/ckeditor/ckeditor-4.x/rel/sfdc-config.js',
                removePlugins:'sfdcCodeBlock,elementspath,maximize,image,tabletools,liststyle,contextmenu,resize',`
