### ISSUE TITLE
unable to resize Large Excel table pasted via table properties

### ISSUE THREAD

**Issue by JohnCSMoodys** [ckeditor/ckeditor4#4557] opened 2021-03-05 17:14 UTC
## Type of report

Bug

## Provide detailed reproduction steps (if any)

Paste a large excel into CKEditor and try to resize using table properties.
![image](https://user-images.githubusercontent.com/36516764/110149738-02cc8b00-7da4-11eb-9adc-8541f2578d24.png)

### Expected result

*What is the expected result of the above steps?*

### The paste table must fit in the window

*What is the actual result of the above steps?*

## Other details

* Browser: Chrome
* OS: Win 10
* CKEditor version:4.14.0
* Installed CKEditor plugins: …

**Comment by sculpt0r** [comment] 2021-03-08 10:01
Hi @JohnCSMoodys 
I try to reproduce this issue. Could you confirm that you have a problem only with the `height` property - which is kind of showed on your screen? I'm able to change the `width` property, but indeed the `height` seems to have no effects.

**Comment by sculpt0r** [comment] 2021-03-10 09:07
I can't reproduce this issue at [Paste from excel demo](https://ckeditor.com/docs/ckeditor4/4.14.0/examples/pastefromexcel.html) and MS Office Proffessional Plus 2016.

Changing the  `width` property seems to be working fine. The `height` property limits the horizontal size due to content amount. Also, this option works fine for a small amount of data. Please notice, our [docs](https://ckeditor.com/docs/ckeditor4/4.14.0/examples/pastefromexcel.html) mention other style settings:

> The content appearance in CKEditor also depends on styling used in contents.css files.


At this point, I'm closing this issue with resolution: `by design`. If you can prove this behavior as invalid in any other circumstances - feel free to open another issue.

**Closed by sculpt0r** 2021-03-10 09:07 UTC
Labels: type:bug
