### ISSUE TITLE
Tooltip is not available on toolbar buttons for the keyboard users

### ISSUE THREAD

**Issue by sryarama** [ckeditor/ckeditor4#4324] opened 2020-10-09 16:32 UTC
Any content that can be surfaced by a mouse user should be surfaced when in a keyboard-only scenario (not just screen reader users). Screen reader users aren't the only scenario for keyboard-only scenarios.

Using "title" property on an element uses the browser's default tooltip. However, because this will never surface to keyboard users, this is not considered an accessible approach. 

As per our accessibility testing team, element's title property is not accessible to keyboard users which is an issue.  FYI...One our A11y SME has a whole article discussing the history and recommended approaches: https://sarahmhigley.com/writing/tooltips-in-wcag-21/

**Comment by Dumluregn** [comment] 2020-10-13 10:19
It's a duplicate of #2613.

**Closed by Dumluregn** 2020-10-13 10:19 UTC
Labels: resolution:duplicate

**Comment by VienTranSB** [comment] 2020-11-01 07:12
ADADSADSAD
