### ISSUE TITLE
Upload Image while offline

### ISSUE THREAD

**Issue by tandvu** [ckeditor/ckeditor4#4678] opened 2021-05-06 18:34 UTC
Provide detailed reproduction steps (if any)
Open Chrome Developer Tool. Application Tab. Click on Service Workers. Check Offline.
Click Image icon in CKEditor.
A Dialog popup 
Pick a local file.
Click Upload.

Expected result
The image should be displayed

Actual result
Nothing happens.

**Comment by Comandeer** [comment] 2021-05-07 13:49
Duplicate of #4643.

**Closed by Comandeer** 2021-05-07 13:49 UTC
Labels: resolution:duplicate, type:bug
