### ISSUE TITLE
[Chrome] &nbsp; is inserted instead of space

### ISSUE THREAD

**Issue by mblagojevic10** [ckeditor/ckeditor4#5488] opened 2023-06-06 10:04 UTC
Bug

Provide detailed reproduction steps (if any)
Type a space between two words somewhere in the middle of a sentence:
`<h1>Hello| world!</h1> -> <h1>Hello | world!</h1>` - the caret becomes between two spaces.
Press backspace to delete one space on the left.
Type a space and new word "foobar".
Expected result:
```html
<h1>Hello foobar world!</h1>
``` 

Actual result
```html
<h1>Hello foobar&nbsp;world!</h1>
``` 

Other details
Browser: Google Chrome 114.0.5735.106
OS: linux, win, macos
[Screen Recording 2023-06-06 at 11.59.05.zip](https://github.com/ckeditor/ckeditor4/files/11663130/Screen.Recording.2023-06-06.at.11.59.05.zip)
The video is attached with an example.

**Comment by KarolDawidziuk** [comment] 2023-06-07 21:10
Hi @mblagojevic10 

I cannot confirm this issue. Tested on the provided version of Chrome.

The behavior of the editor shown in the provided video is the expected behavior. In case when there is more than one space between words, the editor will apply a `non-breaking-space`character to prevent text collapsing.

You can test it by applying multiple spaces between word, switch to source mode, remove `&nbsp;` then back to the WYSIWYG mode and you'll see that spaces will be collapsed to a single one which is not a expected behaviour.

Since this report is not valid, I'm closing it.

**Closed by KarolDawidziuk** 2023-06-07 21:10 UTC
Labels: type:bug

**Comment by rmueller83** [comment] 2023-10-13 08:06
To reproduce, use a Chromium-based Browser (Chrome, Edge) and go to https://ckeditor.com/ckeditor-4/demo/
Select a part of the existing text (e.g. "tempted by the idea") and copy it to your clipboard.
Go to the end of a different line (I did it on the last one), hit space, and paste the content from your clipboard.
Now copy the whole modified line to you clipboard and paste it into an editor which shows hidden characters (e.g. IntelliJ IDEA):
![ckeditor-nbsp](https://github.com/ckeditor/ckeditor4/assets/2698076/3d243a80-5c06-4434-a31d-6b74bbcd7a66)

**Comment by rmueller83** [comment] 2023-10-13 08:13
@KarolDawidziuk could you please re-open this?
