### ISSUE TITLE
Failing tests/plugins/autocomplete/view

### ISSUE THREAD

**Issue by Comandeer** [ckeditor/ckeditor4#2141] opened 2018-06-22 11:28 UTC
## Type of report

Failing test

## Provide detailed reproduction steps (if any)

1. Open http://tests.ckeditor.test:1030/tests/plugins/autocomplete/view

### Expected result

All tests pass

### Actual result

Some tests fail due to fact that Firefox responds with _too precise_ result (6.5 instead of 7):

<img width="598" alt="" src="https://user-images.githubusercontent.com/1078728/41774456-1b48d1f4-7620-11e8-8b79-440e46c48f79.png">

## Other details

* Browser: Firefox
* Resolution: 1280x800
* Device pixel ratio: 2

**Comment by FilipTokarski** [comment] 2020-02-19 12:10
Failing on 4.14.0 with the same errors. Firefox 73.0

**Comment by hub33k** [comment] 2020-09-02 08:05
Reproducible with Chrome 85 on Android.

```
Error details for tests/plugins/autocomplete/view
test get caret rect (classic)
Values should be equal.
Expected: 7 (number)
Actual:   7.000030517578125 (number)
```

**Comment by KarolDawidziuk** [comment] 2021-09-13 08:48
I cannot reproduce this problem on any device and the browsers mentioned above (Chrome, FF) in BrowserStack and my physical device, so I close this issue.

**Closed by KarolDawidziuk** 2021-09-13 08:48 UTC
Labels: status:confirmed, browser:firefox, browser:android, type:failingtest
