### ISSUE TITLE
js error in git ckeditor/samples/toolbarconfigurator core/tools.js

### ISSUE THREAD

**Issue by themanyone** [ckeditor/ckeditor4#4002] opened 2020-04-24 02:41 UTC
## Type of report

**Bugfix patch**

## Provide detailed reproduction steps (if any)

1. pbt: obtain the latest git versio nof ckeditor
2. Using Chrome browser, navigate to ckeditor/samples/toolbarconfigurator
3. Note errors in ckeditor/core/tools.js

### Expected result

no eeeeror

### Actual result
﻿
tools.js:1236 Uncaught TypeError: Cannot read property 'event' of undefined
    at new eventsBuffer (tools.js:1236)
    at index.html:415
    at index.html:444
eventsBuffer	@	tools.js:1236
(anonymous)	@	index.html:415
(anonymous)	@	index.html:444
﻿
## Other details

**Fix/patch: I removed "new" from line 415 in ckeditor/samples/toolbarconfigurator/index.html
Seems to have fixed all errors and it works.**

* Browser: Chrome
* OS: Saucy Linux
* CKEditor version: Git?
* Installed CKEditor plugins: stock

**Comment by themanyone** [comment] 2020-04-24 05:24
Fix/patch: I removed "new" from line 415 in ckeditor/samples/toolbarconfigurator/index.html
Seems to have fixed all errors and it works.

**Comment by Dumluregn** [comment] 2020-04-27 09:36
I confirm the error is present, also when using our [CDN](http://cdn.ckeditor.com/4.14.0/full-all/samples/toolbarconfigurator/index.html#basic). It's a regression introduced in `4.11.0`.

**Comment by jacekbogdanski** [comment] 2020-06-01 07:14
So, it looks like the API has been incorrectly used and [`CKEDITOR.tools.eventsBuffer` in > 4.11.0](https://ckeditor.com/docs/ckeditor4/4.10.0/api/CKEDITOR_tools.html#method-eventsBuffer) shouldn't be initialized, as it's not a class, but a method. It worked due to JS mechanism but was not intended to be initialized with `new` keyword. That means it's not a regression requiring some core changes, but simple samples issue.

Refactoring into this method in 4.11.0 revealed samples bug.

**Comment by jacekbogdanski** [comment] 2020-06-01 07:16
Closed in https://github.com/ckeditor/ckeditor4/pull/4083

**Closed by jacekbogdanski** 2020-06-01 07:16 UTC
Labels: status:confirmed, type:task, workload:low
