### ISSUE TITLE
Issue resolved

### ISSUE THREAD

**Issue by paulovich10** [ckeditor/ckeditor4#4990] opened 2021-11-29 08:55 UTC
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. …
2. …
3. …

### Expected result

*What is the expected result of the above steps?*

### Actual result

*What is the actual result of the above steps?*

## Other details

* Browser: …
* OS: …
* CKEditor version: …
* Installed CKEditor plugins: …

**Comment by sculpt0r** [comment] 2021-12-02 10:37
Since the problem is solved - I'm closing this issue.

**Closed by sculpt0r** 2021-12-02 10:37 UTC
Labels: type:bug, resolution:invalid
