### ISSUE TITLE
Text color/background color gets reset when changing color after clicking in the middle of the string

### ISSUE THREAD

**Issue by jtisekar** [ckeditor/ckeditor4#3429] opened 2019-09-17 18:18 UTC
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. Change the background color of a long string to blue
2. click any where in the middle of the string
3. Change background color to yellow

### Expected result

The string background stays blue

### Actual result
The string background color is reset to default.

## Other details
The issue happens for text color as well.
Able to repro it with the color button plugin  demo page below.

https://ckeditor.com/docs/ckeditor4/latest/examples/colorbutton.html

**Comment by jacekbogdanski** [comment] 2019-09-18 07:36
Duplicate of https://github.com/ckeditor/ckeditor4/issues/2932

**Closed by jacekbogdanski** 2019-09-18 07:36 UTC
Labels: type:bug
