### ISSUE TITLE
[Feature request] Add an option to prefer the native browser context menu

### ISSUE THREAD

**Issue by SuperPat45** [ckeditor/ckeditor4#3550] opened 2019-10-08 11:29 UTC
## Type of report

Feature request

## Provide description of the new feature

I can not use the SCAYT plugin (I am on a private LAN, without external internet access), So I use CKeditor with the native browser spell checking, thanks to the option:
`disableNativeSpellChecker : false`

Now, I can see miss-spelled words.
But, when I right click on one of them, I have the CKEditor context menu with only the "Paste" item (in firefox).
So, I need to press Ctrl or Shift + Right click to access to the native browser context menu to view and select corrections. I'd rather not have to do that.
Furthermore, the "Paste" menu item does not work under firefox and chrome and show message to use Ctrl+V.

Because of all this, can you add an option who show the native browser context menu when the CKEditor context menu would have contained only the Cut, Copy or Paste items?
Its name may be "preferNativeBrowserContextMenu".
This parameter would have no effect when the CKEditor context menu contains additional items.

**Comment by Comandeer** [comment] 2019-10-08 15:32
Seems like duplicate of #3336 to me.

Introducing `preferNativeBrowserContextMenu` for certain options would require integrating `contextmenu` plugin with several other plugins. Also criteria for deciding when native context menu can vary between use cases. On the other hand, switching showing native context menu to right click and custom context menu to <kbd>Ctrl/Cmd</kbd> + right click should fix this issue without disabling access to the custom context menu in any context.

**Closed by Comandeer** 2019-10-08 15:32 UTC
Labels: type:feature

**Comment by SuperPat45** [comment] 2021-09-10 12:07
I implemented the feature myself like this:

```
element.on( 'contextmenu', function( event ) {
  var domEvent = event.data,
     isCtrlKeyDown =
       // Safari on Windows always show 'ctrlKey' as true in 'contextmenu' event,
       // which make this property unreliable. (https://dev.ckeditor.com/ticket/4826)
       ( CKEDITOR.env.webkit ? holdCtrlKey : ( CKEDITOR.env.mac ? domEvent.$.metaKey : domEvent.$.ctrlKey ) );

  var showNative = !!this.editor.config.preferNativeContextMenu;
    if ( showNative ) {
      var selection = this.editor.getSelection(),
       start = selection && selection.getStartElement(),
       path = this.editor.elementPath();
      for ( var i = 0; i < this._.listeners.length && showNative; i++ ) {
       var listenerItems = this._.listeners[ i ]( start, selection, path );
       if ( listenerItems ) {
        for ( var itemName in listenerItems ) {
         var item = this.editor.getMenuItem( itemName );
         if ( item && item.command && this.editor.getCommand( item.command ).state 
          && item.command !== "paste" && item.command !== "copy" && item.command !== "cut" ) {
          showNative = false;
         }
        }
       }
      }
    }

    if ( showNative || nativeContextMenuOnCtrl && isCtrlKeyDown ) {
      return;
    }

    // Cancel the browser context menu.
    domEvent.preventDefault();
     
    // ...
```

The native menu as some additional items like "Cancel" / "Redo" / "Select all" and a working "Paste" item.

However, it is not perfect, because if the text is in a table the native context menu is not displayed because of the presence of the items "Cell", "Row", "Column", "Delete table" and "Table properties" appear in the context menu.

  
It should be possible to detect that you have clicked on a simple word (and not an HTML link or other) and ignore this menu and display it only if the focus is next to a word.

#4416 @seanmcne, @ckeditor Maybe this example may inspire you for a further better implementation.
