### ISSUE TITLE
window.opener.CKEDITOR.tools.callFunction( funcNum, fileUrl ); not working

### ISSUE THREAD

**Issue by jmahatpure01** [ckeditor/ckeditor4#3805] opened 2020-01-20 19:02 UTC
## Are you reporting a feature request or a bug?

Bug

## Provide detailed reproduction steps (if any)

1. I am using "ckeditor4-react": "^1.0.1" with below snippet. And I am building the custom image browser in react.
2. <CKEditor
            type="classic"
            data={props.defaultValue}
            config={{
                extraPlugins: "uploadimage",
                uploadUrl: config.SERVER_URL+"/uploadImage",
                filebrowserUploadUrl: config.SERVER_URL+"/uploadImage",
                filebrowserBrowseUrl: "http://localhost:3000/#/browseImages"
            }}
            name={name}
            onChange={(evt)=>onChange(evt.editor.getData())}
            error={!!(touched && error)}
            helperText={touched && error}
            required={isRequired}
        />
3. const getUrlParam = ( paramName ) => {
    var reParam = new RegExp( '(?:[\?&]|&)' + paramName + '=([^&]+)', 'i' );
    var match = window.location.search.match( reParam );

    return ( match && match.length > 1 ) ? match[1] : null;
}

const getImageUrl = (id) => {
    fetch(config.SERVER_URL+'/getImageUrl/'+id).then((response)=>{
        return response.json()
    }).then(({url})=>{
        let funcNum = getUrlParam( 'CKEditorFuncNum' );
        window.opener.CKEDITOR.tools.callFunction( funcNum, url, function() {
            // Get the reference to a dialog window.
            var dialog = this.getDialog();
            // Check if this is the Image Properties dialog window.
            if ( dialog.getName() == 'image' ) {
                // Get the reference to a text field that stores the "alt" attribute.
                var element = dialog.getContentElement( 'info', 'txtAlt' );
                // Assign the new value.
                if ( element )
                    element.setValue( 'alt text' );
            }
            // Return "false" to stop further execution. In such case CKEditor will ignore the second argument ("fileUrl")
            // and the "onSelect" function assigned to the button that called the file manager (if defined).
            // return false;
        } );
        window.close();
    })
}
I am calling the getImageUrl function. I console.logged url which is properly coming. Then I console.logged window.opener.CKEDITOR which is also a proper reference of Ckeditor.

### Expected result

The image dialog of CKEditor should receive and display the url of the image

### Actual result
No change in the url field at all

## Other details

* Browser: Chrome Version 79.0.3945.88 (Official Build) (64-bit)
* OS: Ubuntu 19.10
* CKEditor version: "ckeditor4-react": "^1.0.1" & 4.13.1
* Installed CKEditor plugins: CKEditor.editorUrl="https://cdn.ckeditor.com/4.13.1/full-all/ckeditor.js"

**Comment by Comandeer** [comment] 2020-01-22 10:39
I can't reproduce the error. Can you provide more info? Please also note that the file browser has to be from the same origin as the page with CKEditor instance.

**Comment by jmahatpure01** [comment] 2020-01-23 04:54
Yes, it is on the same origin. In my react application in one page I have used the ckeditor react component. And in another page I am showing list of all images. On click of an image I am calling the function getImageUrl(). The function gets url of image from server and passes it to the ckeditor callfunction.

**Comment by Comandeer** [comment] 2020-01-23 14:23
Can you show some demo? Are there any errors in console?

**Comment by jmahatpure01** [comment] 2020-01-24 04:13
There are no errors in the console... that's the biggest issue.

**Comment by Comandeer** [comment] 2020-01-27 13:02
I'm not able to reproduce it. I created sample codesandbox with your code: https://codesandbox.io/s/sharp-bose-2uyjs?fontsize=14&hidenavigation=1&theme=dark – it seems to be working fine.

**Comment by Dumluregn** [comment] 2020-02-11 08:19
Hi, It's been a while since we last heard from you. We're closing this issue for now. Still, feel free provide us requested feedback, so that we can reopen this issue.

**Closed by Dumluregn** 2020-02-11 08:19 UTC
Labels: status:pending, type:bug
