### ISSUE TITLE
4.13.0 - Paste overwrites existing text

### ISSUE THREAD

**Issue by laurin1** [ckeditor/ckeditor4#3589] opened 2019-10-21 17:41 UTC
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. Update from 4.12.1 to 4.13.0
2. Enter text into a CKEditor text box
3. Copy and then paste the additional text below the initial text

### Expected result

Text is pasted below original text.

### Actual result

Pasted text overwrites the original text entered.

## Other details

* Browser: Edge (Chromium, Dev & Canary)
* OS: Windows 10 Pro 1903 x64
* CKEditor version: 4.13.0
* Installed CKEditor plugins: Default set, minus "scayt"

**Comment by msamsel** [comment] 2019-10-22 08:02
I wasn't able to reproduce the issue.
Can you provide more details to your issue description?
Please check our sample: http://cdn.ckeditor.com/4.13.0/full-all/samples/ is it possible to reproduce the issue on this page?
I used VM with Win10 and Edge Beta (with chromium) and previously mentioned the link with the editor for testing purpose.

**Comment by laurin1** [comment] 2019-10-26 11:27
I am not able to reproduce on the samples page. I'm not sure what other details I can give. I've looked at a any JavaScript attached to various events on these instances, but nothing even appears to be a remote possibility. I did confirm if we roll back to 4.12.1, we do not have this issue. I'll see if I can't isolate or more or provide better feedback.

**Comment by laurin1** [comment] 2019-10-27 11:58
This is going to be a hard one. I can reproduce it on our site (which is internal only) consistently for 5-10 attempts, then it won't happen again for a while, no matter what I do. Then it starts happening again. Right now, we are stuck on 4.12.1 until we can figure out what is causing the issue. I looked through the release notes for 4.13.0 but found nothing that even might cause an issue.

**Comment by msamsel** [comment] 2019-10-28 13:17
The case which somehow might be related is supporting paste from google docs: #835, which also includes some of `paste` refactoring. So you could check if removing `pastetools`, `pastefromgoogledocs` and `pastefromword` help here.
There was also some selection optimization which might also be related.
I encourage you to create some basic setup of the editor and gradually add more and more features.
This might give us information if the problem is inside one of the plugins or rather somewhere in the core of the editor.

**Comment by laurin1** [comment] 2019-10-28 13:28
Considering that I have found it impossible to consistently reproduce the issue, the method you're talking about will be almost impossible. I could think I have it narrowed down, then find out it had failed 3 or 4 options ago and just did not show up at that point. I will try removing those plugins you indicated.

**Comment by laurin1** [comment] 2019-11-03 18:26
Try as I might, I cannot reproduce this issue consistently. I will get a pattern (copy source, copy format, paste format) where it happens all the time, then the same pattern fails and never occurs again.

**Comment by msamsel** [comment] 2019-11-04 08:35
So right now I'm closing this issue. If you discover repetitive pattern to reproduce the bug, please report it as a separate issue with all details allowing for bug reproduction.

**Closed by msamsel** 2019-11-04 08:35 UTC
Labels: status:pending, type:bug

**Comment by laurin1** [comment] 2019-11-04 13:59
The problem is, I just deployed it to production again and it's failing right off the bat. Meaning, since we can't debug and we can't deploy, we are stuck on 4.12.1 indefinitely.

**Comment by laurin1** [comment] 2019-11-04 14:01
> If you discover repetitive pattern to reproduce the bug, please report it as a separate issue with all details allowing for bug reproduction.

I don't even understand this statement. How the bug is produced should not create an issue, it's that a bug is produced that should create an issue.

**Comment by laurin1** [comment] 2019-11-04 14:01
Really frustrating that the issue is not resolved, but you just closed it without asking me first.

**Comment by laurin1** [comment] 2020-09-26 18:06
Just updated to 4.15.0 and the issue still exists.
