### ISSUE TITLE
For the image plugin add option to set the loading attribute

### ISSUE THREAD

**Issue by johanadivare** [ckeditor/ckeditor4#5392] opened 2022-12-14 08:24 UTC
## Feature request for image plugin

Right now we dont have a option to set the loading attribute for the image plugin, and i think this attribute is quite important with making sure image are loaded the most efficient way like loading images at the bottom of the page with `loading=lazy` more information about the loading attribute https://developer.mozilla.org/en-US/docs/Web/HTML/Element/img#attr-loading

I would like to have another select box for loading with the following values:
not set (default selected in this case the attribute isn't added)
eager
lazy

maybe `auto`? https://web.dev/browser-level-image-lazy-loading/#are-there-plans-to-automatically-lazy-load-images-in-chrome

some short information for each value:
lazy - Deferring the loading of assets till it reaches a certain distance from the viewport.
eager - loading the assets as soon as the page loads, irrespective of where they are placed on the page, whether above or below the page fold.
auto - This value triggers default lazy loading. Basically, it's the same as not including the loading attribute.

**Comment by KarolDawidziuk** [comment] 2022-12-15 09:32
Duplicate of https://github.com/ckeditor/ckeditor4/issues/3935.

**Closed by KarolDawidziuk** 2022-12-15 09:32 UTC
Labels: type:feature
