### ISSUE TITLE
f.getNextRange is not a function

### ISSUE THREAD

**Issue by skerit** [ckeditor/ckeditor4#3829] opened 2020-01-31 11:13 UTC
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. Select any piece of text
2. Try to apply a style (bold/italic)
3. Error is thrown...

This happens with or without extra options. In either inline or replace mode.

### Expected result

It should just apply the style

### Actual result

An error is thrown:

```
Uncaught TypeError: f.getNextRange is not a function
    at CKEDITOR.style.G (ckeditor.js?v=1580468207602:512)
    at CKEDITOR.style.apply (ckeditor.js?v=1580468207602:514)
    at applyStyle (ckeditor.js?v=1580468207602:523)
    at CKEDITOR.command.CKEDITOR.styleCommand.exec (ckeditor.js?v=1580468207602:522)
    at CKEDITOR.command.exec (ckeditor.js?v=1580468207602:219)
    at a.execCommand (ckeditor.js?v=1580468207602:292)
    at CKEDITOR.ui.button.CKEDITOR.tools.extend.click (ckeditor.js?v=1580468207602:698)
    at Object.execute (ckeditor.js?v=1580468207602:699)
    at ckeditor.js?v=1580468207602:700
    at ckeditor.js?v=1580468207602:33
```

## Other details

* Browser: Chrome 75.0.3770.100
* OS: Linux
* CKEditor version: 4.13

**Comment by Dumluregn** [comment] 2020-02-03 07:39
Hello, it seems to be working fine on our [CDN](http://cdn.ckeditor.com/4.13.1/full-all/samples/). Could you try to reproduce it there? It would be helpful, if you create a sample where the issue occurs (e.g. using [CopePen](https://codepen.io/) or other).

**Comment by jacekbogdanski** [comment] 2020-02-17 08:51
Hi, It's been a while since we last heard from you. We're closing this issue for now. Still, feel free provide us requested feedback, so that we can reopen this issue.

**Closed by jacekbogdanski** 2020-02-17 08:51 UTC
Labels: resolution:expired, type:bug
