### ISSUE TITLE
Can't delete empty paragraph between widgets unless I use Source mode

### ISSUE THREAD

**Issue by Wizard13** [ckeditor/ckeditor4#3534] opened 2019-10-03 20:32 UTC
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. Go to Simplebox widget demo: https://ckeditor.com/docs/ckeditor4/latest/examples/simplebox.html
2. Delete contents of CKEditor
3. Click on Simplebox button, then click below it, hit Enter and then click on Simplebox button again.
4. Place cursor in the empty paragraph between the widgets and hit Delete or Backspace to remove the empty paragraph

### Expected result

Paragraph is removed and widgets are close to each other.

### Actual result

Paragraph is not removed and focus is being applied to one of the two widgets. I have to go to Source mode to delete this paragraph.

## Other details

* Browser: Firefox 69 x64
* OS: Windows 7 SP1 x64
* CKEditor version: 4.13.0
* Installed CKEditor plugins: widget

**Comment by jacekbogdanski** [comment] 2019-10-07 08:16
Duplicate of #1572

**Closed by jacekbogdanski** 2019-10-07 08:16 UTC
Labels: type:bug
