### ISSUE TITLE
onChange event is getting called, but with no data, when content is added via plugin like mathtype or wiris

### ISSUE THREAD

**Issue by jvanwyk1** [ckeditor/ckeditor4#4280] opened 2020-09-16 07:50 UTC
## Type of report

Bug

## Provide detailed reproduction steps (if any)

Creating new issue from previous issue.
Reference:
#3817 

1. Open https://ckeditor.com/docs/ckeditor4/latest/examples/mathtype.html
2. Handle 'change' event of editor, paste in dev console:

`CKEDITOR.instances.editor1.on( 'change', function() {
  console.log( 'change event data', this.getData() );
} );`

3. Delete all content in ckeditor
4. Launch mathtype from the editor
5. Add math formula and click insert
6. Editor 'change event is fired, when you click insert button on mathtype.
7. call editor.getData(), returns empty result
8. Formula is is inserted into ckeditor.

### Expected result

when call step 7 above, expected to get the mathml code as data

### Actual result

returns nothing, believe event get fired before data is inserted into ckeditor and not after. 

## Other details

* Browser: Chrome(latest)
* OS: Windows 10
* CKEditor version: latest
* Installed CKEditor plugins: MathType

**Comment by Comandeer** [comment] 2020-09-16 08:00
I can confirm the issue. @carlawiris, could you take a look?

**Comment by dcanetma** [comment] 2020-09-18 09:35
You can track the issue here: https://github.com/wiris/html-integrations/issues/115

**Comment by henok-tesfaye** [comment] 2020-10-05 09:47
This issue has been fixed, you can close it. FYI the [demo page](https://ckeditor.com/docs/ckeditor4/latest/examples/mathtype.html) is not upgraded to use the latest version.

**Comment by f1ames** [comment] 2020-10-05 11:40
Thanks @henok-tesfaye for the follow-up :+1: 

As mentioned, the issue has been fixed in `7.24.1` version (more details in wiris/html-integrations#115).

**Closed by f1ames** 2020-10-05 11:40 UTC
Labels: resolution:upstream, status:confirmed, type:bug, workload:external

**Comment by AkashSanariya** [comment] 2020-11-11 17:28
> This issue has been fixed, you can close it. FYI the [demo page](https://ckeditor.com/docs/ckeditor4/latest/examples/mathtype.html) is not upgraded to use the latest version.

How to fix this issue because in angular when i implements at that time I got the same issue
