### ISSUE TITLE
Undo/redo using keyboard shortcuts escaping divarea editor

### ISSUE THREAD

**Issue by ChadMcCaulley** [ckeditor/ckeditor4#5386] opened 2022-12-03 01:00 UTC
## Type of report

Bug

## Summary
When using one or more divarea editors, undoing and redoing changes when no more changes exist (history is empty); focus jumps to the previous focused element.

#### Steps for editor
1. Type some value into the editor
2. Press ctrl+z or ctrl+shift+z two or more times
3. Focus will move from the editor to the parent document

#### Steps for 2 or more editors
1. Type some value into one of the editors
2. Move focus to another editor by tabbing or clicking
3. Type some value into the second editor
4. Press ctrl+z or ctrl+shift+z two or more times
5. Focus will move to the first editor and undo/redo the changes

### Expected result

Should disable the undo button when there is nothing left to undo and ctrl+z should have no effect.

### Actual result

Focus jumps to most recent focused element or the parent DOM

## Other details

* Framework: Vue 2
* Wrapper: Ckeditor4Vue
* Browser: chrome, edge, firefox
* OS: windows 11
* CKEditor version: 4.20.1
* Installed CKEditor plugins: divarea

**Comment by KarolDawidziuk** [comment] 2022-12-06 09:59
Duplicate of https://github.com/ckeditor/ckeditor4-vue/issues/149

**Closed by KarolDawidziuk** 2022-12-06 09:59 UTC
Labels: type:bug
