### ISSUE TITLE
Performance drop in Ckeditor while Copy Formating 

### ISSUE THREAD

**Issue by atomtechsln** [ckeditor/ckeditor4#4174] opened 2020-07-24 11:57 UTC
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. Open IE ,Create large content in  ckeditor content.
2. Copy Formatting and apply apply to entire content.
3. IE window hang while Copy Formatting entire content.

### Expected result

Apply smoothly.

### Actual result

Hang Internet explore(IE)11 and wait or kill confirmation windows will appear. and Take too much time to apply.

## Other details

* Browser:IE11
* OS:Windows 10
* CKEditor version:4.12.1
* Installed CKEditor plugins: pastefromword,pastebase64,copyformatting

**Comment by Dumluregn** [comment] 2020-07-27 13:38
Hello, please provide us more information, like what size of content concerns this issue and which formats do you try to copy. Here are the templates - please use one of them to create a demo, where we could reproduce the behaviour you described:

* CodePen: https://codepen.io/Comandeer/pen/ExaMgpz?editors=1010
* JSFiddle: https://jsfiddle.net/Comandeer/d6ey8a2w
* JSBin: https://jsbin.com/keqekef/1/edit?html,js,output
* StackBlitz: https://stackblitz.com/edit/js-vcqfw3

**Comment by jacekbogdanski** [comment] 2020-08-11 06:40
Hi, It's been a while since we last heard from you. We're closing this issue for now. Still, feel free provide us requested feedback, so that we can reopen this issue.

**Closed by jacekbogdanski** 2020-08-11 06:40 UTC
Labels: status:pending, type:bug
