### ISSUE TITLE
Impossible to delete inline widget / caret displacement on mobile

### ISSUE THREAD

**Issue by sculpt0r** [ckeditor/ckeditor4#4711] opened 2021-05-14 08:45 UTC
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. Open test `tests/plugins/widget/manual/inline`
2. Put caret after the widget
3. Start deleting characters
4. When caret comes to the widget it's becoming selected and the keyboard hides.
5. Select widget (tap on it)
6. Start deleting characters. Caret is moved to the end of the document and the widget won't delete.

### Expected result

The inline widget should be deleted.
Caret should remain between previous characters.

### Actual result

*What is the actual result of the above steps?*
Widget stays in the document, caret is moved to the end of the content

## Other details

https://user-images.githubusercontent.com/6498567/118245800-84761e80-b4a1-11eb-9a84-fa71fcf0a712.mp4

* Browser: Chrome (mobile) 90
* OS: Android 10
* CKEditor version: 4.16.1
* Installed CKEditor plugins: -

**Comment by f1ames** [comment] 2021-05-14 13:55
Duplicate of #3920.

**Closed by f1ames** 2021-05-14 13:55 UTC
Labels: browser:android, browser:chrome, plugin:widget, status:confirmed, type:bug
