### ISSUE TITLE
[PasteFromWord]: When doc is pasted from word, extra spacings are introduced at multiple places

### ISSUE THREAD

**Issue by niagrawa** [ckeditor/ckeditor4#4754] opened 2021-06-10 18:15 UTC
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. Copy paste from this doc 
[1-8_9_LS Lost Procedure_101320.docx](https://github.com/ckeditor/ckeditor4/files/6633546/1-8_9_LS.Lost.Procedure_101320.docx)

2. Extra spacings introduced at multiple places

### Expected result

No extra spacings should be introduced.

### Actual result

Extra spacings introduced at multiple places

## Other details

* Browser: Chrome
* OS: Windows 10
* CKEditor version: 4
* Installed CKEditor plugins: pastefromword

**Comment by Comandeer** [comment] 2021-06-11 15:29
Can you precise what do you mean by "spacing"? Are you referring to the additional padding inside table cells?

**Comment by niagrawa** [comment] 2021-06-14 10:13
Adding snaphots of few places where I can see extra spacing. @Comandeer FYI

![image](https://user-images.githubusercontent.com/41113728/121875936-a1af3e80-cd26-11eb-8f93-382b80b729b0.png)

![image](https://user-images.githubusercontent.com/41113728/121876207-e76c0700-cd26-11eb-982d-c9600a31f64f.png)

![image](https://user-images.githubusercontent.com/41113728/121876452-21d5a400-cd27-11eb-8f32-96d436920fbc.png)

**Comment by Comandeer** [comment] 2021-06-14 13:26
The issue is not connected to the pasting mechanism itself, but with the way in which the content of the editor is displayed. [Adjusting styles](https://jsfiddle.net/Comandeer/ahry7d5c/) seems to eliminate unnecessary spacing.

You can change default styles by [providing alternative stylesheet for the editor](https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_config.html#cfg-contentsCss).

I'll close the issue as the issue with rendering is better fixed on user end, not by modifying paste logic.

**Closed by Comandeer** 2021-06-14 13:26 UTC
Labels: type:bug
