### ISSUE TITLE
CKEditor does not delete a paragraph between two widgets

### ISSUE THREAD

**Issue by bunglegrind** [ckeditor/ckeditor4#4375] opened 2020-11-17 11:44 UTC
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. take ckeditor latest version, with a widget installed, e.g. the simplebox plugin.
2. Insert two consecutive widgets
3. add a paragraph between the widget (with the magic line or manually via source)
4. put the cursor in the paragraph and hit del or backspace

### Expected result

paragraph is deleted

### Actual result

the next (or previous depending if you hit del or backspace) widget is selected

## Other details

* Browser: Firefox or Chrome latest
* OS:win10
* CKEditor version:CKEditor 4.15.1
* Installed CKEditor plugins: simplebox

You can actually delete the paragraph by pressing shift + del or ctrl + del, but it doesn' always work and it's not good from a user experience perspective.

**Comment by bunglegrind** [comment] 2020-12-01 07:56
btw, I found the same issue on stackoverflow:

https://stackoverflow.com/questions/30262191/ckeditor-how-to-delete-empty-paragraphs-before-and-between-widgets

**Comment by bunglegrind** [comment] 2020-12-03 14:21
the workaround suggested in the aforementioned link is not working (anymore?) (Select p in elements path - press backspace). It just the closing p tag at the end of the text.

Anyway, this is the very same bug? #12778

**Comment by f1ames** [comment] 2020-12-03 16:08
Hi @bunglegrind, yes your issue is a duplicate of #1572, thanks for bringing this up :+1: 

I'm marking and as a duplicate, please add any further comments in #1572.

**Closed by f1ames** 2020-12-03 16:08 UTC
Labels: plugin:widget, status:confirmed, type:bug
