### ISSUE TITLE
Delete last character in row, ckeditor 4 (v4.16.0) will delete whole paragraph

### ISSUE THREAD

**Issue by ducpt1** [ckeditor/ckeditor4#4628] opened 2021-04-20 09:07 UTC
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. Go to https://ckeditor.com/ckeditor-4/demo/
2. Delete image in content demo.
3. Place cursor to last of "I didn’t know".
4. Press backspace.
5. The whole paragraph will be deleted.

### Expected result

Just only character "w" in "I didn’t know"  is deleted

### Actual result

The whole paragraph will be deleted.

## Other details

* Browser: Chrome 90
* OS: Window 10
* CKEditor version: 4.16.0
* Installed CKEditor plugins: …

Sorry for my bad English!!!

**Comment by sergeyvdovareize** [comment] 2021-04-20 09:12
https://user-images.githubusercontent.com/3746371/115370351-a695bd00-a1d1-11eb-8734-ad81d796aef4.mp4

**Comment by Christoph-Wagner** [comment] 2021-04-20 13:27
We just got hit by the bug as well. It happens on Chrome 90, but not 89. Firefox is also not affected.

**Comment by f1ames** [comment] 2021-04-20 13:37
I can confirm it happens in Chrome `90` and is not happening in Chrome `89`. This means some changes in latest Chrome version are causing this issue. We will have to investigate what's going on there :crossed\_fingers:

**Comment by f1ames** [comment] 2021-04-20 15:03
Findings so far:

*   Happens with both `iframe` and `div` based editors.
*   Couldn't reproduce with native `contenteditable` element so far.
*   We don't have that much custom `backspace` handling and I was not able to determine exactly what's going on.
*   All unit tests are green.

**Comment by Comandeer** [comment] 2021-04-20 15:45
It seems that our [anti-going-rogue Blink <kbd>Backspace</kbd> handler](https://github.com/ckeditor/ckeditor4/blob/major/core/editable.js#L1195-L1235) made Chrome 90+, ironically, go rogue. The issue is connected with the logic inside `mergeBlocksCollapsedSelection` private function, yet I need more time to really pin down the cause.

**Comment by Comandeer** [comment] 2021-04-21 11:03
I was able to pin down the cause – it seems that it's a [Chrome's bug connected with splitting the text node](https://bugs.chromium.org/p/chromium/issues/detail?id=1201161).

**Comment by f1ames** [comment] 2021-04-22 10:29
> I was able to pin down the cause – it seems that it's a [Chrome's bug connected with splitting the text node](https://bugs.chromium.org/p/chromium/issues/detail?id=1201161).

Since there is no straightforward reasonable workaround for now and the issue has been already confirmed, let's see if it will be fixed quickly. We will revisit this issue regularly to see what's the status of things.

**Comment by f1ames** [comment] 2021-04-23 08:46
We decided to take another look into this issue to see if there could be any workaround implemented on our side so we can tackle this issue quickly :crossed\_fingers:

**Comment by sergeyvdovareize** [comment] 2021-04-23 08:48
Updated Chrome version (90.0.4430.85) still has the issue

**Comment by Comandeer** [comment] 2021-04-26 12:59
I was trying to find a workaround, but I've [encountered another bug](https://bugs.chromium.org/p/chromium/issues/detail?id=1202439). I'm not sure if there is a sensible way to fix it on our side.

**Comment by f1ames** [comment] 2021-04-27 08:14
Well, nothing so far, we also tried to get rid of our [anti-going-rogue Blink <kbd>Backspace</kbd> handler](https://github.com/ckeditor/ckeditor4/blob/major/core/editable.js#L1195-L1235) all together but it seems it's still needed (also on Safari).

**Comment by temi** [comment] 2021-04-28 06:57
The issue happens on microsoft edge

**Comment by f1ames** [comment] 2021-04-28 10:51
For now it seems there are no reasonable workarounds (anything at all in fact), as mentioned in [https://github.com/ckeditor/ckeditor4/pull/4645#issuecomment-827682937](https://github.com/ckeditor/ckeditor4/pull/4645#issuecomment-827682937):

> If the result is the same (meaning existing tests pass and it works the same as before on Chrome 89) it's still broken on Chrome 90... Seems like some mechanism related to manipulating text nodes (not only `splitText()`) is broken :thinking::sob:

It seems it's fixed on Canary already (see https://bugs.chromium.org/p/chromium/issues/detail?id=1202439#c17) so there is some hope it will be fixed soon in a stable version.

I have also checked other channels:

* Stable (`90.0.4430.93`) - Broken
* Beta (`91.0.4472.19`) - Broken
* Dev (` 92.0.4484.7`) - Broken
* Canary (`92.0.4491.0`) - Works fine :tada:

So worst case scenario the fix is two versions from the current stable (which is around 11 weeks from now). We will see if it can be pushed quicker on the Chrome side.

**Comment by f1ames** [comment] 2021-04-29 07:49
Hi all, quick update on this issue - the fix on the Chromium side was [already merged to `v91`](https://bugs.chromium.org/p/chromium/issues/detail?id=1202439#c25) from what I can see. Also there are [some efforts to merge it to `v90`](https://bugs.chromium.org/p/chromium/issues/detail?id=1202439#c26). So there is a high chance it will be much quicker than `v92` (worst case scenario now is `v91` stable).

You can see the progress on both issue in:

* https://bugs.chromium.org/p/chromium/issues/detail?id=1202439
* https://bugs.chromium.org/p/chromium/issues/detail?id=1201161

**Comment by Dumluregn** [comment] 2021-05-12 09:08
Another update - I wasn't able to reproduce the problem after updating to stable Chrome `90.0.4430.212` on macOS 🎉  So anyone who experiences this issue - please make sure you are using the latest version and it should work fine.

**Comment by Christoph-Wagner** [comment] 2021-05-12 09:15
Can confirm with the same Chrome version `90.0.4430.212` on Windows.

**Comment by Comandeer** [comment] 2021-05-13 10:09
I can also confirmed that the bug is fixed. Therefore I'm closing this issue.

**Closed by Comandeer** 2021-05-13 10:09 UTC
Labels: browser:chrome, core, resolution:upstream, size:External, status:blocked, status:confirmed, type:bug
