### ISSUE TITLE
[Bug] After executing Undo, the placeholder becomes editable.

### ISSUE THREAD

**Issue by HuangBuxin-Glority** [ckeditor/ckeditor4#4171] opened 2020-07-24 09:08 UTC
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. Config placeholder for CKEditor. for example: CKEDITOR.replace('cke_message_area', {placeholder: 'Enter message'});
2. Open CKEditor.
3. Enter a word like 'a' to the CKEditor
4. Click twice 'Undo' button on the toolbar

Reproduction Video:
https://drive.google.com/file/d/1QRc3g6-Ms5uN3Ndcqz2ZCCVL-btswNQC/view?usp=sharing

### Expected result

*The word 'a' was removed,  placeholder cannot be edited in CKEditor.*

### Actual result

*The word 'a' was removed,  placeholder can be edited in CKEditor.*

## Other details

* Browser: Chrome
* OS: Windows
* CKEditor version: CKEditor 4
* Installed CKEditor plugins: Undo

**Comment by Dumluregn** [comment] 2020-07-24 09:32
Hello, 
1. `config.placeholder` is not a valid config option for CKEditor 4, so it isn't expected to work correctly. Are you using an unreleased `editorplaceholder` plugin already? If so, the correct config option is `config.editorplaceholder`.
2. I wasn't able to reproduce the issue, and I see that at the beginning of your video you already have some undo steps stacked so you didn't give the full reproduction path. Does the issue occur also with the freshly loaded editor?

**Comment by jacekbogdanski** [comment] 2020-08-11 06:40
Hi, It's been a while since we last heard from you. We're closing this issue for now. Still, feel free provide us requested feedback, so that we can reopen this issue.

**Closed by jacekbogdanski** 2020-08-11 06:40 UTC
Labels: status:pending, type:bug

**Comment by HuangBuxin-Glority** [comment] 2020-08-11 06:54
@Dumluregn @jacekbogdanski Sorry for not noticed your previous reply.
Later I discovered that this was actually a issue with the confighelper plugin, and found that someone had reported the same issue(https://github.com/AlfonsoML/confighelper/issues/20), but it was not processed. It seems that this plugin is no longer updated.
In addition, I would like to ask whether CKEditor has other ways to set placeholder(the hint of the input)?

**Comment by jacekbogdanski** [comment] 2020-08-11 07:00
@HuangBuxin-Glority we've recently introduced `editorplaceholder` plugin which does exactly what you are looking for: https://github.com/ckeditor/ckeditor4/pull/3898

It will be available in the next `4.15.0` release, which is scheduled for the 3rd of September (note that this date may change a bit).

**Comment by HuangBuxin-Glority** [comment] 2020-08-11 07:05
@jacekbogdanski Thanks for your help! It seems that this is exactly what I want, and I will focus on the release of the new version.
