### ISSUE TITLE
error in pastetools plugin

### ISSUE THREAD

**Issue by WebDev223** [ckeditor/ckeditor4#3535] opened 2019-10-04 02:53 UTC
I was trying to use pastefromword plugin, I added all its dependencies as well. But whenever I try to paste content it give me below error.

Cannot read property 'filter' of undefined at getMatchingHandlers in pastetools/plugin.js

I was trying it on chrome.
![ckeditor](https://user-images.githubusercontent.com/43160500/66177728-20815680-e6bf-11e9-9f75-cbf228e0c0e0.png)

**Comment by jacekbogdanski** [comment] 2019-10-07 08:31
I cannot reproduce the issue, could you tell us more about your CKEditor configuration? Looking at the code https://github.com/ckeditor/ckeditor4/blob/5fa2a5b5f5b06d139ecaf8d47f5444734244e5b9/plugins/pastetools/plugin.js#L178-L188 and provided stack trace it looks like there is an issue with global `CKEDITOR.tools.array.filter`, not `pastetools` itself, but it's just guessing.

It would be great if you could provide demo using https://codepen.io or similar tool with the issue.

**Comment by Dumluregn** [comment] 2019-10-17 15:38
Hi, It's been a while since we last heard from you. We're closing this issue for now. Still, feel free provide us requested feedback, so that we can reopen this issue.

**Closed by Dumluregn** 2019-10-17 15:38 UTC
Labels: status:pending, type:bug
