### ISSUE TITLE
Mouse selection is broken in Chrome

### ISSUE THREAD

**Issue by Fynn96** [ckeditor/ckeditor4#5002] opened 2021-12-16 09:56 UTC
## Type of report

Bug

## Provide detailed reproduction steps (if any)

Can be tested here: https://codepen.io/Fynn96/pen/oNGZrjx

1. Fill the editor with content until a scrollbar appears.
2. Try to select a part of the text with your mouse.

https://user-images.githubusercontent.com/45873523/146401794-31d357ac-0d88-4ad3-b9e0-5e317c3bf0e5.mp4

### Expected result
The chosen part is selected.

### Actual result
Much more content is selected.

## Other details

* Browser: Chrome Version 98.0.4750.0
* CKEditor version: 4.17.1
* OS: Windows 10

**Comment by KarolDawidziuk** [comment] 2021-12-16 14:34
Hi @Fynn96 
Thank you for the report.

Unfortunately, I can't reproduce this issue - tested on macOS and Windows.
Can you provide more information such as plugin list and os (Windows, macOS, other)
If possible, a short video/gif showing the problem would help a lot.

**Comment by Fynn96** [comment] 2021-12-16 15:42
Hi @KarolDawidziuk 
Thanks for checking this issue. I created a small video and added my OS (Win 10). This bug appeared recently. It may have something to do with the new Chrome Version. 
As you can see in the video this problem only appears if there is enough content so a scollbar appears. If you reduce the content it works perfectly fine. You can test this with my Codepen example. I only forked the template and edited the content a bit so there are no further plugins included.

**Comment by KarolDawidziuk** [comment] 2021-12-17 08:34
Thank you for the additional information and screen record.

I can confirm this issue, but...
You use Chrome in version 98 which is a developer version of the browser.
The latest stable version is 96 so I encourage you to use it.

Nevertheless, thank you for your report. We'll monitor the selection behavior in future chrome versions.

I'm closing this issue.

**Closed by KarolDawidziuk** 2021-12-17 08:34 UTC
Labels: type:bug

**Comment by Fynn96** [comment] 2021-12-17 09:16
@KarolDawidziuk Okay, thanks for this hint. I will downgrade my Chrome. Hopefully the problem will not continue to exist in the next stable version.
