### ISSUE TITLE
Remove format misses first element

### ISSUE THREAD

**Issue by colinbernays** [ckeditor/ckeditor4#4909] opened 2021-09-27 01:30 UTC
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. Paste text from Word into CKEditor
2. Select text and click remove format

### Expected result

All formatting is removed from the text.

### Actual result

The first element will still have an inline style applied that needs to be removed manually.

## Other details

This happens in the online demo: https://ckeditor.com/docs/ckeditor4/latest/examples/pastefromword.html

**Comment by sculpt0r** [comment] 2021-09-27 11:11
Hi @colinbernays ,
Thank you for the report. I can confirm this issue. However, it looks like an issue inside style remover, not PFW.
It is reproducible for example on: https://ckeditor.com/docs/ckeditor4/latest/examples/basicstyles.html. Simple select all and try to remove styles. 

The remaining style is for example `style="text-align:justify"` inside `p` element. The issue is present at least back to `4.13.1` - so no regression here. Also, FF, Chrome, and Safari are affected.

**Comment by sculpt0r** [comment] 2022-07-26 08:22
Hi @colinbernays 

It take a while until we return to this report. We try to verify it again - and it seems that there is no bug. I assume your report was about `style="text-align:justify"` attribute set on the first paragraph on the docs page (mentioned in your report). I try to verified it earlier and found the same bug, however...

If we read the [docs](https://ckeditor.com/docs/ckeditor4/latest/features/removeformat.html) for the `Remove Format` plugin, it says:

> [...] remove any text formatting that is applied through inline HTML elements and CSS styles [...]

and then

> [...] Note that it does not change [text formats](https://ckeditor.com/docs/ckeditor4/latest/features/format.html) applied at block level."

So my previous comment is also invalid. Please note, that `text-align` is applied on the block level - so it shouldn't be removed by the `Remove Format` feature.

I'm sorry it took so long and in the end we need to close this issue.

**Closed by sculpt0r** 2022-07-26 08:22 UTC
Labels: type:bug, status:confirmed, plugin:removeformat
