### ISSUE TITLE
Click event on editor source HTML element and parent HTML element not working sometimes randomly.

### ISSUE THREAD

**Issue by syedabdulaala** [ckeditor/ckeditor4#3981] opened 2020-04-10 08:11 UTC
## Type of report

Bug

### Description

I have multiple CKEditor (almost 40) align vertically in HTML, each div is a simple contenteditable div which is initialized as a CKEditor instance when user focuses on it but sometime randomly the click event that is registered either on contenteditable div or it's parent div doesn't fire, it occurs randomly but easily reproducible within 40 CKEditors HTML elements. If CKEditor is not initialized on the div then every thing works normal. only 26 out of 40 click events fire most of the time when CKEditor is intialized on it.

### Expected result

Click event should be fire every time on CKEditor source HTML element and it's parent HTML elements too.

### Actual result

Sometime randomly the click event that is registered on either contenteditable div or it's parent div doesn't fire, it occurs randomly but easily reproducible within 40 CKEditors HTML elements.

### Other details

* Browser: 80.0.3987.163 (64-Bit)
* OS: Linux (Ubuntu 18.04.4 LTS)
* CKEditor version: 4.13.1
* Installed CKEditor plugins: basicstyles, clipboard, contextmenu, enterkey, entities, font, format, indentblock, indentlist, justify, list, sharedspace, showborders, stylescombo, table, tableresize, tableselection, toolbar, undo, widget, wysiwygarea

**Comment by Dumluregn** [comment] 2020-04-10 08:23
Hello, if `click` event on `div` isn't fired, then it's a `div` element's issue, not CKEditor's. From what you wrote I understand, that if an event is triggered CKEditor works fine, so I'm closing this issue.

**Comment by syedabdulaala** [comment] 2020-04-10 08:35
> Hello, if `click` event on `div` isn't fired, then it's a `div` element's issue, not CKEditor's. From what you wrote I understand, that if an event is triggered CKEditor works fine, so I'm closing this issue.

No, the click event work perfectly fine when no CKEditor is initialized on it. I have tried both with and without CKEditor, With CKEditor 40 out 26 events fired only most of time and without CKEditor 40 out of 40 everytime.

**Comment by Dumluregn** [comment] 2020-04-10 08:51
From what you wrote I understood that CKEditor instance is initialised after clicking on div. Could you provide us with a sample to see your case and reproduce an issue?

**Comment by Dumluregn** [comment] 2020-04-29 09:52
Hi, It's been a while since we last heard from you. We're closing this issue for now. Still, feel free provide us requested feedback, so that we can reopen this issue.

**Closed by Dumluregn** 2020-04-29 09:52 UTC
Labels: status:pending, type:bug
