### ISSUE TITLE
Link textbox cannot be focused when ckeditor is opened in a popup

### ISSUE THREAD

**Issue by nicolasiac** [ckeditor/ckeditor4#3827] opened 2020-01-30 08:47 UTC
## Type of report

Bug

## Provide detailed reproduction steps (if any)

We are opening CKEditor in a popup dialog (we are using dojotoolkit)
When we click on the link button the link popup dialog displays but we cannot click on the textbox. 
There are numerous similar issues on stackoverflow for various libraries (bootstrap, jquery ui-dialog, etc) so I don't believe it is a problem with the library but it is something with ckeditor
ex. 
https://stackoverflow.com/questions/20533487/how-to-ensure-that-ckeditor-has-focus-when-displayed-inside-of-jquery-ui-dialog 
### Expected result

*What is the expected result of the above steps?*
To be able to focus on the link textboxes whether is in a popup or not 

### Actual result

*What is the actual result of the above steps?*
It does not focus 
## Other details

* Browser: …
* OS: …
* CKEditor version: 4
* Installed CKEditor plugins: …

**Comment by Dumluregn** [comment] 2020-02-03 08:24
Hello! Thanks for using CKEditor.

I checked the SO issue you mentioned and it turned out, it was jquery issue after all (bumping it's version solved the problem), so it's hard to say what isn't working right now. Could you provide us a demo (e.g. on [CodePen](https://codepen.io/)), where we will be able to reproduce this bug?

**Comment by nicolasiac** [comment] 2020-02-03 09:17
Thanks for the reply.
However, that was just an example. A similar issue is this one:
https://stackoverflow.com/questions/31678662/ckeditor-issue-with-bootstrap-modal

Also, this one using magnific.
https://github.com/ckeditor/ckeditor5/issues/1147

So this is something generic as it happens in dojotoolkit as well which doesn't use bootstrap or jquery at all.

**Comment by Dumluregn** [comment] 2020-02-03 13:01
I see, did you try to use the solution hinted [here](https://stackoverflow.com/a/31679096)? It helps with Bootstrap and jQuery, so it probably can be used also in dojotoolkit. If it doesn't work, please send us code sample to see how exactly does this one work.

**Comment by jacekbogdanski** [comment] 2020-02-17 08:50
Hi, It's been a while since we last heard from you. We're closing this issue for now. Still, feel free provide us requested feedback, so that we can reopen this issue.

**Closed by jacekbogdanski** 2020-02-17 08:50 UTC
Labels: status:pending, type:bug

**Comment by Liero** [comment] 2022-02-28 12:35
I would like to reopen this issue.

Here is a codepen with bootstrap 5 modal without jquery.

**Comment by jacekbogdanski** [comment] 2022-03-01 07:51
@Liere from what I see you are using CKEditor 5, not 4 in the demo. Issues related to CKEditor 5 should be reported at CKEditor 5 issue tracker - https://github.com/ckeditor/ckeditor5/issues
