### ISSUE TITLE
Failing test: /tests/plugins/widget/manual/inline

### ISSUE THREAD

**Issue by KarolDawidziuk** [ckeditor/ckeditor4#4698] opened 2021-05-13 08:47 UTC
## Type of report

Failing test

## Provide detailed reproduction steps (if any)

1. Open `/tests/plugins/widget/manual/inline`.
2. Create new `doublecolumn` widget.
3. Put Lena image into the widget.
4. Double click into Lena image, check `Captioned image` and save it.
5. Try put cursor after/before image.

![screen](https://user-images.githubusercontent.com/18471998/118101361-d2265480-b3d7-11eb-9fb8-25e4af48c8d7.gif)

### Expected result

* Possibility to add cursor after or before image.

### Actual result

* Cursor can be added in whole section.

## Other details

* Browser: tested on: IE9 / Safari / Chrome / Opera / Firefox
* OS: macOS (Safari / Chrome / Opera / Firefox) and VBox(Win7 -> IE9)
* CKEditor version: 4.16.1

**Comment by f1ames** [comment] 2021-05-14 14:30
I think it may get fixed with #4539 which means is in fact duplicate of #4467. @KarolDawidziuk could you confirm it works on the latest `major`?

**Comment by KarolDawidziuk** [comment] 2021-05-14 16:26
You're right. 
It's work with fix from [#4539](https://github.com/ckeditor/ckeditor4/issues/4539), so we can add new line before and after image and I think we can close it.

**Comment by f1ames** [comment] 2021-05-18 07:22
> It's work with fix from [#4539](https://github.com/ckeditor/ckeditor4/issues/4539), so we can add new line before and after image and I think we can close it.

Closing then :+1:

**Closed by f1ames** 2021-05-18 07:22 UTC
Labels: plugin:widget, status:confirmed, type:bug
