### ISSUE TITLE
Upgrade to 4.16.0: plugins/ajax/plugin.js not found

### ISSUE THREAD

**Issue by mrothauer** [ckeditor/ckeditor4#4525] opened 2021-02-05 11:01 UTC
I updated from 4.15.1 to 4.16.0 and some users (mainly firefox) report an error.
I was able to reproduce the error only once and got
`plugins/ajax/plugin.js 404 `
In 4.16.0 this file does not exist any more and probably it's a cache issue.

**Comment by f1ames** [comment] 2021-02-05 13:04
Hello @mrothauer, I can confirm this is a cache issue most probably. Before `4.16.0` the `plugins/ajax/plugin.js` was there as a separate file but since `4.16.0` it is required by one of the "core" (enabled by default) plugins which means it is bundled into main `ckeditor.js` file too.

So the plugin is still there in CKEditor 4 preset but its files are now included in `ckeditor.js` file. This means that after updating to recent `4.16.0` version the browser may look for mentioned file (due to cache) but it won't be there.

I'm closing this issue, but feel free to add any comments if anything new comes up.

**Closed by f1ames** 2021-02-05 13:04 UTC
Labels: type:bug

**Comment by mrothauer** [comment] 2021-02-05 16:21
Hello @f1ames, thanks for your quick answer.
do you see any possibility to disable that cache problem? I don't want to tell my users that they have to clear their browser cache manually. I usually change CKEDITOR.timestamp when I upgrade to a newer version, all requested files then have an additional timestamp-get-parameter that forces the browser not to use the cached file. but this time it did not work.
see https://github.com/foodcoopshop/foodcoopshop/commit/8df31e6b0c4ba2bfcf625591cdbf820258d1f27c

**Comment by f1ames** [comment] 2021-02-08 08:56
Hi again @mrothauer,

From what I see this issue may be caused by the fact that `CKEDITOR.timestamp` is added to all resources loaded by CKEditor 4, but at the same time, the main/entry file (`ckeditor.js`) lacks this timestamp since it is loaded externally (by integration / integrator).

The list of plugins is held in `ckeditor.js` which means it may be cached and so it may try load some non-existent files as in your case. **The solution here would be adding timestamp to `ckeditor.js` file too.**

**Comment by mrothauer** [comment] 2021-02-08 09:14
Hi @f1ames,
thank's a lot for your hint. There was already a timestamp added to ckeditor.js, but it was the same that in v4.15.0 (I guess because the file itself has not changed).
I manually added a new parameter to the file and theoretically the problem should be solved with that.
If I don't comment again, you can consider this issue as solved.
Have a good day!
Mario
