### ISSUE TITLE
Failing test: `/tests/core/editor/detaching`

### ISSUE THREAD

**Issue by sculpt0r** [ckeditor/ckeditor4#5191] opened 2022-05-10 09:15 UTC
## Type of report

Failing test

## Provide detailed reproduction steps (if any)

1. Run tests in IE11

### Expected result

*What is the expected result of the above steps?*

All tests passed.

### Actual result

*What is the actual result of the above steps?*

![image](https://user-images.githubusercontent.com/6498567/167593996-72825b4a-f14c-4562-99f7-26b9f31affe2.png)

## Other details

* Browser: IE11
* OS: Win10
* CKEditor version: 4.19.0 (pre-release)
* Installed CKEditor plugins: development

**Comment by sculpt0r** [comment] 2022-05-10 10:13
Looks similar to https://github.com/ckeditor/ckeditor4/issues/3426

**Comment by sculpt0r** [comment] 2022-05-11 07:59
The same on chrome - mobile (android). Those tests fail only when run in a group. When you run them separately - they pass.

**Comment by KarolDawidziuk** [comment] 2022-08-09 07:34
I cannot reproduce this. All tests passed.
@sculpt0r could you check if these tests are still failing?

**Comment by sculpt0r** [comment] 2022-08-11 08:40
For example in safari, using current `master`
![Screenshot 2022-08-11 at 10 40 18](https://user-images.githubusercontent.com/6498567/184095902-02266c07-dc91-4f4a-b764-ff4a4a85ff0a.png)

https://user-images.githubusercontent.com/6498567/184095782-52142bfb-f8df-4ed2-b72a-7609b8cdf433.mov

**Comment by sculpt0r** [comment] 2022-08-11 08:44
But @KarolDawidziuk - as you can see I used `ngrok` here, when tested via `localhost` on safari - it's fine 🤔

**Comment by sculpt0r** [comment] 2022-08-11 08:44
Some time-dependent factors?

**Comment by KarolDawidziuk** [comment] 2022-08-11 09:17
> Some time-dependent factors?

Probably yes, because after I added throttling on Chrome(browser that has not been reported) I can reproduce it.

**Comment by jacekbogdanski** [comment] 2022-08-24 09:52
Seems like the issue is only visible when using an additional proxy for running tests - and that's not recommended way to run tests, so I'm closing that issue.

**Closed** 2022-08-24 09:53 UTC
Labels: status:confirmed, browser:safari, browser:ie11, browser:android, plugin:wysiwygarea, type:failingtest
