### ISSUE TITLE
Error in adding links 

### ISSUE THREAD

**Issue by thilinadinith** [ckeditor/ckeditor4#3677] opened 2019-11-22 01:43 UTC
## Type of report

Links adding with CKEditor in chrome 78.0.3904.97  gives an  error of following 
and i have checked latest firefox also and i can reproduce this

```
link.js?t=J8Q8:27 Uncaught TypeError: Cannot read property 'length' of undefined
    at CKEDITOR.dialog.onOk (link.js?t=J8Q8:27)
    at CKEDITOR.dialog.<anonymous> (ckeditor.js:613)
    at CKEDITOR.dialog.l (ckeditor.js:10)
    at CKEDITOR.dialog.fire (ckeditor.js:12)
    at button.onClick (ckeditor.js:637)
    at button.<anonymous> (ckeditor.js:575)
    at button.l (ckeditor.js:10)
    at button.fire (ckeditor.js:12)
    at button.click (ckeditor.js:574)
    at CKEDITOR.dom.element.<anonymous> (ckeditor.js:566)
```

##  reproduction steps (if any)

1. enable links for CKeditor
2. click the link icon in ckeditor toolbar
3. it opens a dialog to add display name and the link
4. adding link and display name
5.click ok

### Expected result

close the dialog box and adding the link to the ckeditor text area

### Actual result

dialog box is not closing and console gives 

```
link.js?t=J8Q8:27 Uncaught TypeError: Cannot read property 'length' of undefined
    at CKEDITOR.dialog.onOk (link.js?t=J8Q8:27)
    at CKEDITOR.dialog.<anonymous> (ckeditor.js:613)
    at CKEDITOR.dialog.l (ckeditor.js:10)
    at CKEDITOR.dialog.fire (ckeditor.js:12)
    at button.onClick (ckeditor.js:637)
    at button.<anonymous> (ckeditor.js:575)
    at button.l (ckeditor.js:10)
    at button.fire (ckeditor.js:12)
    at button.click (ckeditor.js:574)
    at CKEDITOR.dom.element.<anonymous> (ckeditor.js:566)
```

## Other details

* Browser: chrome 78.0.3904.97  / firefox
* OS:MAC
* CKEditor version: 4.13.0
* Installed CKEditor plugins:

**Comment by f1ames** [comment] 2019-11-22 09:02
Hello @thilinadinith,
I'm not able to reproduce this issue on our official samples (e.g. https://ckeditor.com/docs/ckeditor4/latest/examples/standardpreset.html). Could you confirm it happens for you there too? Or maybe you have specific config / 3rd-party plugins which causes this issue?

Checked with Chrome `78.0.3904.108 (Official Build) (64-bit)` on macOS `10.14.5`.

**Comment by Comandeer** [comment] 2019-12-06 12:53
Hi, It's been a while since we last heard from you. We're closing this issue for now. Still, feel free provide us requested feedback, so that we can reopen this issue.

**Closed by Comandeer** 2019-12-06 12:53 UTC
Labels: status:pending, type:bug
