### ISSUE TITLE
It is not possible to drag inline widget out of table or edit it.

### ISSUE THREAD

**Issue by jswiderski** [ckeditor/ckeditor4#2190] opened 2018-06-29 10:26 UTC
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. Empty editor contents
2. Insert image2. Next insert table (you can create some additional text around and inside the table);
3. Drag image2 inside the table.
4. Try dragging image2 out of table
5 .Open image2 dialog and change it size
6. Try resizing the image2 or dragging i out of table

Please see attached screen cast: 
[image2 table.zip](https://github.com/ckeditor/ckeditor-dev/files/2148921/image2.table.zip)

### Expected result

It is possible to dgar image out of table and resize it.

### Actual result

It is not possible to drag image out of table.
After editing the image, it is not possible to edit it at all.

## Other details

Problem can be reproduced from CKEditor 4.7.0 when tableselection was introduced.
Editor works when tableselection plugin is off.

* Browser: Drag out problem can be reproduced in any browser but image edit freeze can only be reproduced in Firefox.
* OS: Any
* CKEditor version: 4.7.0+
* Installed CKEditor plugins: table, tableselection, widget

**Comment by ZY0118** [comment] 2018-12-21 08:00
Has this problem been solved?or will resolved in the future? I'm writing this part of the code and i can't find the solution. If resolved,tell me please!

**Comment by f1ames** [comment] 2020-04-30 13:46
Duplicate of #710.

**Closed as completed by f1ames** 2020-04-30 13:46 UTC
Labels: type:bug, resolution:duplicate, status:confirmed, plugin:tableselection

**Comment by nuander** [comment] 2021-02-06 00:28
jswiderski - THANK YOU for providing a solution.  I see lots of comments/threads getting marked as closed or duplicates and no mention of a solution.  Turning off the Table Selection plugin solved this for me.
