### ISSUE TITLE
Perform differently on SQL in different browser.

### ISSUE THREAD

**Issue by xthboy** [ckeditor/ckeditor4#3916] opened 2020-03-06 08:44 UTC
## Type of report

Bug

## Provide detailed reproduction steps (if any)
I was trying to add text in the CKEditor4 into a MySQL database. If some of words appear in the textbox, then it would not let the page go through and will be like the following screenshot. 
![Screen Shot 2020-03-06 at 12 33 58 AM](https://user-images.githubusercontent.com/21693554/76067412-2916db00-5f44-11ea-9fe4-66d16fd47c14.png)

An interesting thing is that when I use firefox or brave browser, it works fine, but chrome and saferi will have the situation in the screenshot. I suspect whether it would be a problem in the ckeditor working with different browsers differently?

### Expected result
I expected to have the page go through and inserted into db successfully. 

## Other details

* Browser : chrome. saferi
* OS: access from macos; the server is in linux
* CKEditor version: 
* Installed CKEditor plugins:none

**Comment by f1ames** [comment] 2020-03-09 08:08
@xthboy can you provide step by step scenario how this issue can be reproduced? I'm not sure what is the exact issue based on your description.

**Comment by jacekbogdanski** [comment] 2020-03-23 10:40
Hi, It's been a while since we last heard from you. We're closing this issue for now. Still, feel free provide us requested feedback, so that we can reopen this issue.

**Closed by jacekbogdanski** 2020-03-23 10:40 UTC
Labels: status:pending, type:bug
