### ISSUE TITLE
Default plugin tries to init on .destroy() in IE11

### ISSUE THREAD

**Issue by brunis** [ckeditor/ckeditor4#3826] opened 2020-01-29 07:17 UTC
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. On a heavy page, i create a ckeditor in jquery ui dialog
2. .destroy() the editor

### Expected result

No plugins should initialize on .destroy() (i assume?)

### Actual result

When i .destroy() the dialog, the "deselect" plugin initializes in a setTimeout() and tries to attach a click handler to the cke_contents area, but since the editor has already been destroyed it fails with a console error (Unable to get property 'lastChild' of undefined or null reference).

I'm gonna make the assumption it triggers because IE's JS engine is slow and on large pages with lots of frameworks, the setTimeout issue triggers.

## Other details

* Browser: IE11
* OS: Windows
* CKEditor version: 4.8-4.13.1
* Installed CKEditor plugins: Can't get rid of "deselect"

**Comment by brunis** [comment] 2020-01-29 07:19
Workaround is wrapping the contents of the setTimeout() function with a check for the editors status:
`                    if (a.status !== "destroyed") {
                        document.getElementById(a.id + "_contents").lastChild.contentDocument.addEventListener("click", function (a) {
                            var b = document.getElementById(a.id + "_contents").lastChild.contentDocument;
                            return function (c) { var e = b.lastChild.offsetHeight; a.config.height > e && e < c.clientY && a.execCommand("deselectRange") }
                        }(a));
                    }`

**Comment by jacekbogdanski** [comment] 2020-01-30 09:55
Could you provide a minimal demo sample with the issue? You could use https://jsbin.com which supports IE11.

**Comment by brunis** [comment] 2020-02-06 06:16
> 
> 
> Could you provide a minimal demo sample with the issue? You could use https://jsbin.com which supports IE11.

No, i've tried. Also i was mistaken. "deselect" is not standard in any of the packages provided. But it would be interesting to find out why ckeditor runs init on destroy, could probably destroy the editor much faster if you didn't re-initialize (all?) plugins.

**Comment by jacekbogdanski** [comment] 2020-02-06 08:50
Since 4.13.0 plugins are not initialized if an editor has been already destroyed, with this issue fix: https://github.com/ckeditor/ckeditor4/issues/3115

As I understand your issue is third party one so I'm closing this ticket. If you find out that there is still an issue on the CKEditor 4 side, please report a new ticket with reproduction steps/demo allowing us to investigate it.

**Closed by jacekbogdanski** 2020-02-06 08:50 UTC
Labels: status:pending, type:bug

**Comment by brunis** [comment] 2020-02-06 09:36
> 
> 
> Since 4.13.0 plugins are not initialized if an editor has been already destroyed, with this issue fix: #3115
> 
> As I understand your issue is third party one so I'm closing this ticket. If you find out that there is still an issue on the CKEditor 4 side, please report a new ticket with reproduction steps/demo allowing us to investigate it.

I don't know if it's third party, it's in the list in the online-builder. It's a fix for an old IE11 issue.

**Comment by brunis** [comment] 2020-02-06 09:44
> 
> 
> Since 4.13.0 plugins are not initialized if an editor has been already destroyed, with this issue fix: #3115
> 
> As I understand your issue is third party one so I'm closing this ticket. If you find out that there is still an issue on the CKEditor 4 side, please report a new ticket with reproduction steps/demo allowing us to investigate it.

So if you don't support this plugin, maybe you should remove it from the list?

**Comment by jacekbogdanski** [comment] 2020-02-06 10:02
Could you tell me which plugin you are referencing to? I didn't catch the plugin name and from:

>No, i've tried. Also i was mistaken. "deselect" is not standard in any of the packages provided

I supposed you were writing about a 3rd party plugin.

Also, note that you have an option in CKEditor 4 builder to enable only plugins authored by CKSource:

![image](https://user-images.githubusercontent.com/10279586/73926602-2c309400-48d0-11ea-9f41-d60ce61d9643.png)
