### ISSUE TITLE
CKEditor 4.8.0 failing to load due to language file redirect

### ISSUE THREAD

**Issue by Zuluru** [ckeditor/ckeditor4#5175] opened 2022-05-01 23:24 UTC
## Type of report

Bug

## Provide detailed reproduction steps (if any)

I have been using CKEditor v4.8.0 in my application for quite some time. Recently, it's started to fail to load the editor. I haven't changed anything about my implementation of it.

### Expected result

It should load the editor.

### Actual result

I just get a blank space where the editor should be. Checking into the dev tools, I see that it's trying to load `https://cdn.ckeditor.com/4.8.0/full/lang/en-ca.js?t=HBDD`, but this is being redirected to `http://ckeditor.com/fckeditor-old-site`. Which is not only not a useful page in this context, but it's HTTP instead of HTTPS, so it's just rejected outright by browsers. Note that `https://cdn.ckeditor.com/4.8.0/full/lang/en.js?t=HBDD` works fine. That is "en" is okay, "en-ca" is not. I also tried "en-us" and "en-uk" and "es" and "de", and those all redirected.

## Other details

* Browser: Firefox, Chrome and Edge. Presumably all others too, as this looks like a CDN issue, not code.
* OS: N/A
* CKEditor version: 4.8.0
* Installed CKEditor plugins: None, I think. Just using https://cdn.ckeditor.com/4.8.0/full/ckeditor.js

**Comment by shota-yamashita** [comment] 2022-05-02 04:11
Relatedly, a 301 redirect is also performed when loading the following files. (confirmed in v4.16.2)

https://cdn.ckeditor.com/4.16.2/standard-all/skins/moono-lisa/dialog.css?t=L7C8
ref: https://support.ckeditor.com/hc/en-us/requests/74436

**Comment by shota-yamashita** [comment] 2022-05-02 04:13
Relatedly, a 301 redirect is also performed when loading the following files. (confirmed in [ckeditor4-vue](https://github.com/ckeditor/ckeditor4-vue) v4.16.2)

https://cdn.ckeditor.com/4.16.2/standard-all/skins/moono-lisa/dialog.css?t=L7C8
ref: https://support.ckeditor.com/hc/en-us/requests/74436

**Comment by pradeep-gururani-incaendo** [comment] 2022-05-02 07:18
I'm facing the similar issue with the **CDN**, did you guys find any workarounds for this ?

**Comment by jgrehling** [comment] 2022-05-02 07:47
We are having the same issue with the CDN for Version 4.16.1 loading from https://cdn.ckeditor.com/4.16.1/full-all/ckeditor.js

The load of the following resources fails:
* https://cdn.ckeditor.com/4.16.1/full-all/skins/moono/skin.js?t=L4K9
* https://cdn.ckeditor.com/4.16.1/full-all/lang/de.js?t=L4K9

We receive a 301 Response with location: http://ckeditor.com/fckeditor-old-site

Any idea about workarounds here?

**Comment by dipesh112** [comment] 2022-05-02 08:34
We are having the same issue with the CDN for Version 4.6.2 loading from https://cdn.ckeditor.com/4.6.2/standard-all/ckeditor.js

**Comment by jgrehling** [comment] 2022-05-02 08:42
To whom it may concern: We include CKEditor now locally, after downloading it from https://ckeditor.com/ckeditor-4/download/ as a workaround until the CDN is fixed.

**Comment by davelens** [comment] 2022-05-02 08:47
Same here. 4.15.1, using NL locale. Changing it to EN temporarily works (or hosting it locally).

**Comment by pradeep-gururani-incaendo** [comment] 2022-05-02 08:50
looks like the CDN is fixed

<img width="507" alt="image" src="https://user-images.githubusercontent.com/58684557/166208921-37ca26f0-01cc-4f75-b405-06fa3ddb442c.png">

**Comment by Comandeer** [comment] 2022-05-02 11:56
As the issue seems to be fixed, I'm going to close the issue.

**Closed by Comandeer** 2022-05-02 11:56 UTC
Labels: type:bug
