### ISSUE TITLE
You can copy only one image, but you can't add text to it. It comes with formatted text

### ISSUE THREAD

**Issue by Hubmayun123** [ckeditor/ckeditor4#3692] opened 2019-11-29 01:57 UTC
You can copy only one image, but you can't add text to it. It comes with formatted text

Titles like the following
![QQ截图20191129095508](https://user-images.githubusercontent.com/25675858/69838422-76711580-128e-11ea-80b0-58098a5f9d74.png)

1.Just copy one image
![QQ截图20191129095302](https://user-images.githubusercontent.com/25675858/69838329-17ab9c00-128e-11ea-87f8-9c1397326ed3.png)
2.Add words
![QQ截图20191129095001](https://user-images.githubusercontent.com/25675858/69838289-e92dc100-128d-11ea-85b7-80a67b43f1be.png)

testfile
[test.docx](https://github.com/ckeditor/ckeditor4/files/3903394/test.docx)

**Comment by jacekbogdanski** [comment] 2019-11-29 09:33
Duplicate of #2800

**Closed by jacekbogdanski** 2019-11-29 09:33 UTC
Labels: type:bug
