### ISSUE TITLE
Copy paste bug browser type

### ISSUE THREAD

**Issue by Davlatmurod** [ckeditor/ckeditor4#3993] opened 2020-04-17 21:48 UTC
## Google browsers differences

Bug
Copy-Paste from Word file (here [stack_last.docx](https://github.com/ckeditor/ckeditor4/files/4495339/stack_last.docx)) contain more images and text. Pasting not uploaded image files on Google Chrome browser x64

But, Google Chrome browser x32 working. Process same
 
Browser type differences bit x64 and x32. I don't understand.

### Error result
On browser Google Chrome browser x64
![image](https://user-images.githubusercontent.com/16939012/79615175-901ad880-811b-11ea-8a57-f6e2de1960a1.png)
*I don't understand why????. 
If pasting less images both worked*

### But working 
On browser Google Chrome browser x32 

## Details
My configuration
`CKEDITOR.replace( 'editor1' ,{
    toolbar:[
        '/',
        { name: 'basicstyles', groups: [ 'basicstyles', 'cleanup' ], items: [ 'Bold', 'Italic', 'Underline', 'Strike', 'Subscript', 'Superscript' ] },
        { name: 'insert', items: [ 'Image'] },
        '/',
    ],
    filebrowserImageUploadUrl : 'upload?Type=Image',
    language: 'en'

});`

* Browser: Google Chrome browser x64, Google Chrome browser x32
* OS:Windows 7/10 x64. 
* CKEditor version: CKEditor 4.8

**Comment by jacekbogdanski** [comment] 2020-05-04 06:35
The attached document has a lot of images, so processing them takes a while, but I see that testing it on Windows 10 machine with Google Chrome 81.0.4044.129 (Official Build) (64-bit) gives the correct POST request to the endpoint server. Could you make sure to disable all addons and open a browser instance in private mode, to make sure no extension produces the error? `other:blocked` error is pretty common to be caused by tools like AdBlocker.

**Comment by Comandeer** [comment] 2020-05-18 12:28
Hi, It's been a while since we last heard from you. We're closing this issue for now. Still, feel free provide us requested feedback, so that we can reopen this issue.

**Closed by Comandeer** 2020-05-18 12:28 UTC
Labels: status:pending, type:bug
