### ISSUE TITLE
Pasting the content all inline styles are removed into Ckeditor

### ISSUE THREAD

**Issue by mathan05** [ckeditor/ckeditor4#3504] opened 2019-09-27 06:37 UTC
We have integrate the CKEditor in our project. Instead of table plugin we have create a table using java code and automatically appear in CKEditor with 1 row and 3 columns. Type the content inside table and select the whole table Ctrl + A and cut the table Ctrl + X again paste same content but inline styles are removed in IE only, Chrome and Firefox working fine.

All <td> ,<tr> inline styles are removed after pasted.

My configuration config.js Below

CKEDITOR.editorConfig = function( config ) {
	config.extraPlugins = 'mdximage,timestamp,mdxwysiwygarea';
	config.allowedContent = true;
	config.height = 500; 
	config.copyFormatting_allowRules = false;
	config.copyFormatting_allowedContexts = true;	
	config.fullPage = true;
	config.removePlugins = 'wysiwygarea,link,about,forms,wsc,scayt,image,elementspath';
	config.removeButtons = 'Iframe,Flash,Replace,PageBreak,Smiley,SpecialChar,Language,NewPage,Save,Templates,SelectAll,CreateDiv,ShowBlocks,PasteFromWord,PasteText,Table';
	config.menu_groups='Table';
	CKEDITOR.config.copyFormatting_keystrokePaste ="plain-text";
	config.pasteFilter = 'semantic-content';
	config.extraAllowedContent = '*{*}';
};

## Provide detailed reproduction steps (if any)

1. Select table content Ctrl+A
2. Cut using Ctrl + X and paste Ctrl + v

### Expected result

All inline styles are needed after pasting

### Actual result

Inline styles are removed after pasting

## Other details

* Browser: Internet Explorer 11
* OS: Windows 7
* CKEditor version: 4.11.4

**Comment by f1ames** [comment] 2019-09-27 06:49
Hello @mathan05,
I see you are using 3rd-party plugins `mdximage,timestamp,mdxwysiwygarea`. Are you able to reproduce this issue on any official build without 3rd-party plugins?

**Comment by mathan05** [comment] 2019-09-27 07:09
I reproduce same thing without third party plugin still same problem happening. All styles are removed after pasting.

**Comment by f1ames** [comment] 2019-10-03 08:00
@mathan05 could you provide your table HTML? How the content with the table is set in CKEditor (with `setData()` call maybe)?

I assume your issue may be caused by using `semantic-content` paste filter:

> 'semantic-content' – Known tags (except `div`, `span`) with all attributes (except `style` and `class`) will be kept.

What was the reason for setting such config explicitly in your case?

**Comment by Dumluregn** [comment] 2019-10-17 09:18
Hi, It's been a while since we last heard from you. We're closing this issue for now. Still, feel free provide us requested feedback, so that we can reopen this issue.

**Closed by Dumluregn** 2019-10-17 09:18 UTC
Labels: status:pending, type:bug
