### ISSUE TITLE
emoji smiling face with id ":smiling_face:" isn't rendered correctly

### ISSUE THREAD

**Issue by weichuan-dong** [ckeditor/ckeditor4#4064] opened 2020-05-19 20:16 UTC
Type :smiling_face: or search for the smiling face emoji and select it. the emoji is black and white. 
Colorful emoji is expected. The other emojis are rendered correctly, e.g., the ":grinning_face:" is a colorful emoji.

<img width="1173" alt="smiling_face" src="https://user-images.githubusercontent.com/55892307/82373687-296b3200-99db-11ea-93e9-5b8cc85b3962.png">

**Comment by f1ames** [comment] 2020-05-20 06:25
Duplicate of #4046.

**Closed by f1ames** 2020-05-20 06:25 UTC
