### ISSUE TITLE
2 bugs with the editor

### ISSUE THREAD

**Issue by MickeSha** [ckeditor/ckeditor4#3507] opened 2019-09-27 11:34 UTC
## Type of report

Bug

## Provide detailed reproduction steps (if any)

When I start to edit the text, "backspace" can delete everything with a single click. 
In addition, attempting to correct the first line may result a "&nbsp;" appearing in the code and pushing back some of the already written letters in the right.

### Expected result

I need to delete one letter
I want to edit some words in the text

### Actual result

It delete all text
It pushing back some of the already written letters

## Other details

* Browser: Google Chrome
* OS: Windows 10
* CKEditor version: 4
* Installed CKEditor plugins: jsplus_backup, autoembed, embed, image2

**Comment by f1ames** [comment] 2019-09-27 13:30
Hello @MickeSha,
are you able to reproduce mentioned issues on official samples - https://ckeditor.com/docs/ckeditor4/latest/examples/fullpreset.html? It seems it may be caused by 3rd-party plugins you are using (e.g. ` jsplus_backup`) 🤔

**Comment by Comandeer** [comment] 2019-10-13 17:05
Hi, It's been a while since we last heard from you. We're closing this issue for now. Still, feel free provide us requested feedback, so that we can reopen this issue.

**Closed by Comandeer** 2019-10-13 17:05 UTC
Labels: status:pending, type:bug
