### ISSUE TITLE
Toolbar buttons state does not update according to the formatting of the selected text in iOS/Safari

### ISSUE THREAD

**Issue by thomas-cas** [ckeditor/ckeditor4#1796] opened 2018-03-14 13:32 UTC
## Are you reporting a feature request or a bug?
bug

## Provide detailed reproduction steps (if any)

1. Open a page containing ckeditor on a iPhone or iPad in the Safari browser (The bug does not occur on desktop versions of Safari). For a test you can use the sample page at https://cdn.ckeditor.com/4.8.0/full-all/samples/
2. Type in some lines of text with formatting, for example bold, italic, etc.
3. Move the cursor to the formatted text

### Expected result
The buttons in the toolbar should update their state according to the formatting of the selected text. For example if the cursor is moved to bold text, the bold button should be highlighted/selected in the toolbar. If the cursor is moved to italic text the italic button should be hightlighted/selected and so on. This is how it works on other browsers.

### Actual result
The toolbar buttons do not update (only once, when you first tap inside the editing area of ckeditor, after that this state stays regardless of the currently selected text). 
For example when you move the cursor from italic text to bold text, still the italic button is selected in the toolbar.

## Other details

* Browser: mobile Safari on iPhone or iPad
* OS: iOS
* CKEditor version: 4.8.0
* Installed CKEditor plugins: The ones included in the basic package. No additional plugins installed.

**Comment by jacekbogdanski** [comment] 2018-03-20 13:54
Hello,

I can reproduce the issue using iPad with iOS. `basicstyles` buttons state is not updated when changing selection inside editor. Interestingly buttons have correct state when you close keyboard and click inside editor again.

**Comment by f1ames** [comment] 2020-04-20 07:49
This turned out to be a feature request as we reviewed it again with another similar report #3724. Since mentioned issue is more up to date I'm closing this one as a duplicate. @thomas-cas please follow #3724 to see if there is any progress or if you would like to provide more information.

**Closed by f1ames** 2020-04-20 07:49 UTC
Labels: browser:ios, plugin:basicstyles, status:confirmed, type:bug
