### ISSUE TITLE
Table column resize doesn't work with table selection plugin

### ISSUE THREAD

**Issue by f1ames** [ckeditor/ckeditor4#3298] opened 2019-07-24 12:38 UTC
## Type of report

Bug

## Provide detailed reproduction steps (if any)

Extracted from https://github.com/ckeditor/ckeditor-dev/issues/3152#issuecomment-514602041:

1. Go to https://codepen.io/f1ames/pen/ymORXO?editors=1010.
2. Try to resize column which has merged rows.

### Expected result

Resizer appears and column is correctly resized.

### Actual result

Column is incorrectly resize. Table selection is visible upon resizing instead of table resizer.

## Other details

* Browser: All
* OS: All
* CKEditor version: Looks like it started to fail in 4.10.0 (could be related to https://github.com/ckeditor/ckeditor-dev/issues/1467 fix)
* Installed CKEditor plugins: `tableselection`, `tableresize`

**Comment by jacekbogdanski** [comment] 2020-09-11 12:42
Duplicate of https://github.com/ckeditor/ckeditor4/issues/3961

**Closed by jacekbogdanski** 2020-09-11 12:42 UTC
Labels: plugin:tableresize, plugin:tableselection, status:confirmed, type:bug
