### ISSUE TITLE
Support for pasting equations from Word

### ISSUE THREAD

**Issue by pedped** [ckeditor/ckeditor4#2263] opened 2018-07-26 19:18 UTC
when I copy and paste the equation from word to the CKEditor, it will paste the equation as text and as image of converted equation

![](https://i.stack.imgur.com/rYteH.png)

1. write a formula in word
2.copy and paste it to ckeditor 
3.see the result

### Actual result
the text with image after that

*What is the actual result of the above steps?*
I only need image not the text.

Browser: Google Chrome 68
* OS:Windows 10
* CKEditor version: 4.7

**Comment by msamsel** [comment] 2018-08-14 07:33
I can confirm the case.
Paste From Word plugin might be improved to handle pasting equation from Word.

**Comment by pedped** [comment] 2018-11-15 17:42
it seem that Migueeeeel has fixed the problem, please attach that code in next release

https://github.com/ckeditor/ckeditor-dev/issues/1720#issuecomment-418318600

**Comment by Comandeer** [comment] 2021-09-01 14:08
Duplicate of #1720.

**Closed by Comandeer** 2021-09-01 14:08 UTC
Labels: type:feature, status:confirmed, plugin:pastefromword
