### ISSUE TITLE
Table caption get disabled on applying style formats

### ISSUE THREAD

**Issue by usmannoor10p** [ckeditor/ckeditor4#5310] opened 2022-08-16 12:07 UTC
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. Drop dynamic table and add Caption
2. Once the Caption is added, apply any kind of **style format** (Font style, Bold, Italic, etc )
3. Then again open the **Table Properties** by right-clicking the table, the Caption field would be disabled this time
4. I have verified it on this link: https://ckeditor.com/docs/ckeditor4/latest/examples/table.html

Please see the attached gif below.

![Table caption issue1](https://user-images.githubusercontent.com/74644877/184875695-74ea1032-8b60-4d6d-a83b-902b3f39e7a0.gif)

### Expected result

- Caption field should not get disabled

### Actual result

- Caption field gets disabled after applying style formats

## Other details

* Browser: Version 101.0.4951.54 (Official Build) (64-bit)
* OS: Windows 10 Version 1090 (OS Build 18363.836)
* CKEditor version: 4.14.1

**Comment by sculpt0r** [comment] 2022-08-22 09:04
Hi @usmannoor10p 

It would be impossible to edit 'rich text' inside a simple text area. When you decide to mix styling and change the content it would be impossible to apply those changes back as the content of the Editor. Such a possibility would require another 'rich text editor` inside properties.

I'm closing this issue as `by design` since it is not a bug. However - feel free to open another one with `feature request` if you still it could be a good idea to edit styled content inside properties fields.

**Closed by sculpt0r** 2022-08-22 09:04 UTC
Labels: type:bug
