### ISSUE TITLE
Uncaught TypeError: Cannot read property 'clientTop' of undefined

### ISSUE THREAD

**Issue by darmawan01** [ckeditor/ckeditor4#3635] opened 2019-11-08 06:17 UTC
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. Write some text
2. Select all and set align center/right/justified

### Expected result

Back focus at end of text

### Actual result

When set cursor at end or else of the text, cursor back again to first line and can't set the focus again except we set first line align to left, the editor will normal again
```
Uncaught TypeError: Cannot read property 'clientTop' of undefined
    at window.CKEDITOR.window.CKEDITOR.dom.CKEDITOR.dom.element.getDocumentPosition (ckeditor.js:114)
    at z (ckeditor.js:1018)
    at y (ckeditor.js:1020)
    at window.CKEDITOR.window.CKEDITOR.dom.CKEDITOR.dom.element.mouseNear (ckeditor.js:1007)
    at ckeditor.js:1025
```

Related issues: https://github.com/ckeditor/ckeditor4/issues/3512
## Other details

* Browser: All
* OS: …
* CKEditor version: 4.11.2
* Installed CKEditor plugins: …

**Comment by jacekbogdanski** [comment] 2019-11-08 09:24
Please, provide more details about the issue. Preferably screencast with available application demo (e.g. on https://codepen.io), so we will be able to reproduce the issue. Align plugin works fine for me with our sample (https://ckeditor.com/latest/samples):

![align](https://user-images.githubusercontent.com/10279586/68464797-88244780-0211-11ea-9e46-5dc3ca068a6b.gif)

**Comment by darmawan01** [comment] 2019-11-10 13:22
![lose-client-top](https://user-images.githubusercontent.com/23370707/68544637-3392ef00-0400-11ea-9b35-9b8c6012aad2.gif)

**Comment by jacekbogdanski** [comment] 2019-11-12 08:28
I'm sorry @darmawan01 but your gif doesn't show up anything which could help to reproduce the issue except the information that you are using some custom features (or 3rd party). Please, provide working demo e.g. using https://codepen.io which could help us to reproduce issue steps.

**Comment by jacekbogdanski** [comment] 2019-11-26 07:54
Hi, It's been a while since we last heard from you. We're closing this issue for now. Still, feel free provide us requested feedback, so that we can reopen this issue.

**Closed by jacekbogdanski** 2019-11-26 07:54 UTC
Labels: status:pending, type:bug
