### ISSUE TITLE
Focus changes to the first table column on changing CKEditor's text styling, when using Small restored window

### ISSUE THREAD

**Issue by Vivek2393** [ckeditor/ckeditor4#3615] opened 2019-10-31 09:27 UTC
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. Create table 10*10, put some data in each cell
2. Restore the window to half of its size or even more smaller.
3. select text on (10*10)th cell, change its styling to _ITALIC_
4. cell text will change to italic. BUT focus will come back to (10*1)th cell

### Expected result

*After changing styling to Italic, focus should not change and it should remain on that particular cell itself

### Actual result

*Focus changes and comes back to 10th cell of 1st column, that is (10*1)th cell

## Other details

* Browser : Chrome, Firefox
* OS: Windows 10/8
* CKEditor version: 4.11.4
* Installed CKEditor plugins: …

**Comment by Comandeer** [comment] 2019-11-04 13:56
I can't reproduce it. Can you provide more details about reproducing the bug? Especially about the window – what do you refer by this name and what dimensions it has at the beginning?

**Comment by msamsel** [comment] 2019-11-18 14:27
Hi, It's been a while since we last heard from you. We're closing this issue for now. Still, feel free provide us requested feedback, so that we can reopen this issue.

**Closed by msamsel** 2019-11-18 14:27 UTC
Labels: status:pending, type:bug
