### ISSUE TITLE
Unable to click in the last header cell of a table

### ISSUE THREAD

**Issue by idabarbour** [ckeditor/ckeditor4#4523] opened 2021-02-04 17:09 UTC
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. Create the table below in CKEditor
![image](https://user-images.githubusercontent.com/78554945/106928839-a3feed80-66e1-11eb-8da4-9df13c2b2723.png)
2. Try clicking in the 'Remarks' cell 

### Expected result

The cursor is placed in the cell allowing modifications to the text.

### Actual result

Unable to place the cursor in the cell.

## Other details
CKEditor v4.15
Browser - Edge, Chrome

**Comment by Dumluregn** [comment] 2021-02-05 15:50
I didn't have a problem with clicking the last header:
![last-header](https://user-images.githubusercontent.com/10883184/107055658-cf610580-67d1-11eb-91d7-06e4f3c5c237.gif)

Please, provide a demo using one of the following templates:
* CodePen: https://codepen.io/Comandeer/pen/ExaMgpz?editors=1010
* JSFiddle: https://jsfiddle.net/Comandeer/d6ey8a2w
* JSBin: https://jsbin.com/keqekef/1/edit?html,js,output
* StackBlitz: https://stackblitz.com/edit/js-vcqfw3

or at least share the source code of the table you created.

**Comment by idabarbour** [comment] 2021-02-05 16:25
Hello. Thanks so much for looking into this issue. It seems as though there are two types of cursors available when clicking into a header cell. Please see the below images. The first image contains a non-standard cursor, which prevents me from modifying text in the cell. The second image demonstrates the results of clicking in the cell with the non-standard cursor.

Image #1
[cid:image003.png@01D6FBB1.68970840]

Image #2
[cid:image004.png@01D6FBB1.92263910]

Below is the source code.

<table border="1" cellpadding="1" cellspacing="1" style="width:608px">
                <thead>
                                <tr>
                                                <th colspan="1" rowspan="2" scope="col" style="width: 157px; background-color: rgb(102, 204, 102);">Name</th>
                                                <th colspan="1" rowspan="2" scope="col" style="width: 70px; background-color: rgb(102, 204, 102);">Length</th>
                                                <th colspan="1" rowspan="2" scope="col" style="width: 48px; background-color: rgb(102, 204, 102);">Depth</th>
                                                <th colspan="3" rowspan="1" scope="col" style="width: 223px; background-color: rgb(102, 204, 102);">Maximum</th>
                                                <th colspan="1" rowspan="2" scope="col" style="width: 102px; background-color: rgb(102, 204, 102);">Remarks</th>
                                </tr>
                                <tr>
                                                <th scope="col" style="width: 76px; background-color: rgb(102, 204, 102);">LOA</th>
                                                <th scope="col" style="width: 68px; background-color: rgb(102, 204, 102);">Draft</th>
                                                <th scope="col" style="width: 76px; background-color: rgb(102, 204, 102);">Beam</th>
                                </tr>
                </thead>
                <tbody>
                                <tr>
                                                <td style="width:157px">&nbsp;</td>
                                                <td style="width:70px">&nbsp;</td>
                                                <td style="width:48px">&nbsp;</td>
                                                <td style="width:76px">&nbsp;</td>
                                                <td style="width:68px">&nbsp;</td>
                                                <td style="width:76px">&nbsp;</td>
                                                <td style="width:102px">&nbsp;</td>
                                </tr>
                                <tr>
                                                <td style="width:157px">&nbsp;</td>
                                                <td style="width:70px">&nbsp;</td>
                                                <td style="width:48px">&nbsp;</td>
                                                <td style="width:76px">&nbsp;</td>
                                                <td style="width:68px">&nbsp;</td>
                                                <td style="width:76px">&nbsp;</td>
                                                <td style="width:102px">&nbsp;</td>
                                </tr>
                </tbody>
</table>

Ida


[FIS-xSM]

4443 Brookfield Corp Dr. Suite 105
Chantilly, VA 20151

Ida Barbour, CSM, CSPO, ITIL
ida.barbour@fisconsulting.net<mailto:ida.barbour@fisconsulting.net>
Cell:  571-330-4147
Office: 703-378-5055
Fax: 703-378-5255

**Comment by Dumluregn** [comment] 2021-02-08 10:09
I copied the code you provided and it works as expected for me:
![last-header-example](https://user-images.githubusercontent.com/10883184/107204839-7675b500-69fd-11eb-8f74-f20ad61b9029.gif)

This means that the problem is visible only if you run a particular sequence of commands. So without recording a demo or writing the exact reproduction steps list we're unfortunately unable to debug it further. Also, the images you provided unfortunately didn't upload correctly, so I can't take a look at them.

**Comment by idabarbour** [comment] 2021-02-08 16:50
Please see the attached video. A gray box is displayed whenever I attempt to click in the 'Remarks' cell outside of the text.

https://user-images.githubusercontent.com/78554945/107252913-cbb4c500-6a03-11eb-9295-271a391016d4.mp4

**Comment by Dumluregn** [comment] 2021-02-12 10:10
Thank you for recording, also here I'd like to ask you if you can reproduce this issue in our [official demo](https://ckeditor.com/docs/ckeditor4/latest/examples/table.html).

**Comment by idabarbour** [comment] 2021-02-23 18:28
I could not reproduce this issue in CKEditor's demo site. See attached screen recording.

https://user-images.githubusercontent.com/78554945/108890033-0d846480-75db-11eb-9e5c-f3cb00f72c21.mp4

**Comment by Dumluregn** [comment] 2021-02-24 09:30
Hello, we are unable to debug or work on the issues that are not reproducible in our official demos, therefore I'm closing this issue. However if you manage to find a way for us to reproduce it, feel free to provide additional feedback so that we could reopen this issue.

**Closed by Dumluregn** 2021-02-24 09:30 UTC
Labels: type:bug
