### ISSUE TITLE
PasteFromWord Can't Copy/Paste images + other content from Word (most browsers)

### ISSUE THREAD

**Issue by MicahBrown** [ckeditor/ckeditor4#5489] opened 2023-06-06 20:35 UTC
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. Take a word document with at least some text and an image (or just a doc with 2 images)
2. Then select the whole document (Ctrl+A)
3. Then paste in the editor (Ctrl+P) 
<sup>It's currently broken on the [plugin demo page](https://ckeditor.com/docs/ckeditor4/latest/examples/pastefromword.html)</sup>
4. The images show broken like so: 
![brave](https://github.com/ckeditor/ckeditor4/assets/4249414/f5da47ba-9887-4b03-8a58-78872cd92f1e)

I noticed this behavior on Chrome/Brave, Firefox. But weirdly, it works fine on Safari. 

### Expected result

The images should copy fine, like they do in Safari:
![safari](https://github.com/ckeditor/ckeditor4/assets/4249414/9860231c-2b42-406a-9a3f-20698607cc22)

### Actual result

Images copy broken like the example in step 4 above. 

## Other details

* Browser: Brave, Chrome, Firefox, Safari
* OS: MacOS 12.6
* CKEditor version: 4
* Installed CKEditor plugins: pastefromword

Sidenote: It looks as if the images also don't copy over in the appropriate order as you can see from my gifs.

**Comment by KarolDawidziuk** [comment] 2023-06-07 20:47
Hi @MicahBrown

Could you provide a `.docx` file with images that are not possible to paste? Currently, I am not able to reproduce this issue, and copying and pasting two images from Word to the editor works well.

**Comment by MicahBrown** [comment] 2023-06-07 20:55
@KarolDawidziuk Sure, this doc doesn't work for me: [example.docx](https://github.com/ckeditor/ckeditor4/files/11681861/example.docx)

**Comment by MicahBrown** [comment] 2023-06-07 20:56
Also, we initially got this report on this issue from some end-users. So it doesn't seem isolated to my environment.

**Comment by MicahBrown** [comment] 2023-06-07 20:58
And one more thing, copying one image at a time still does work. It just seems to be when you copy an image with text or other content.

**Comment by KarolDawidziuk** [comment] 2023-06-07 21:25
It does not work because the image format is not supported. These images are in `image/emf` format. In addition, if you check the browser's console you'll see an appropriate [error](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_errors.html#pastetools-unsupported-image) regarding this.

**Comment by KarolDawidziuk** [comment] 2023-06-07 21:39
Since a feature request for [EMF file support](https://github.com/ckeditor/ckeditor4/issues/4290) already exists. I am closing this issue.

**Closed by KarolDawidziuk** 2023-06-07 21:39 UTC
Labels: type:bug
