### ISSUE TITLE
unwanted iFrame appended

### ISSUE THREAD

**Issue by theseafoxx** [ckeditor/ckeditor4#5450] opened 2023-03-24 15:53 UTC
The example shows this problem in action:
https://ckeditor.com/docs/ckeditor4/latest/examples/editorplaceholder.html

Click the source button prior to making any edits to the content. Why is there an iframe? 
Worse, in my install of ckeditor 4.21 if I repeatedly open the source this iframe as appended each time.

**Comment by jacekbogdanski** [comment] 2023-03-24 15:56
Could you share the reproduction steps and what's wrong with this docs example?

**Comment by jacekbogdanski** [comment] 2023-03-24 15:58
I see you edited your post. I don't see any additional iframe in the source area. Please, share more details about the issue, including some screencast.

https://user-images.githubusercontent.com/10279586/227577714-780deb5a-b513-4c07-bc99-939b0dc95abc.mov

**Comment by theseafoxx** [comment] 2023-03-24 16:05
I am on a Mac using Google Chrome Version 111.0.5563.110 (Official Build) (x86_64)

![Screenshot 2023-03-24 at 11 59 27 AM](https://user-images.githubusercontent.com/15451476/227578536-885dbc08-b881-455e-bb19-e5481e97bae8.png)

And this looks like a Chrome issue. I looked at this page in Firefox Browser 111.0.1 (64-bit) and the iframe was not appended.

**Comment by jacekbogdanski** [comment] 2023-03-27 12:00
It looks like some Chrome extension problem, I can recommend opening the same page in incognito mode with all extensions disabled. As it doesn't look like the editor issue, I'm closing that ticket.

**Closed by jacekbogdanski** 2023-03-27 12:00 UTC
